### ISSUE TITLE
use GitHub pages for adding a documentation

### ISSUE THREAD

**Issue by 0xMRTT** [topgrade-rs/topgrade#1]
I would suggest to use mdbook and GitHub pages for adding documentation.

So, user will just be able to go to the documentation website instead of the wiki. Maybe a repo in the org for a short URL. I'll glad to work on that if you approve

**Comment by 0xMRTT** [comment]
I was thinking as using mdbook as a website for configuration without need to now all internal stuff, just information about usage and configuration

**Comment by DottoDev** [comment]
Sounds good for me.

**Comment by DottoDev** [comment]
I would go with a dedicated repository then. What do you need for that? New repo with read/write rights?

**Comment by 0xMRTT** [comment]
Yes, a repo called `topgrade-rs.github.io` with github workflow, pages, commit acceess

**Comment by DottoDev** [comment]
I set you as a maintainer of the new repository. It should for now.
