### ISSUE TITLE
asdf no longer supports upgrading itself

### ISSUE THREAD

**Issue by rosstimson** [topgrade-rs/topgrade#1007]
## Erroneous Behavior

```
── 20:49:05 - asdf  ────────────────────────────────────
Upgrading asdf via asdf update is no longer supported. Please use your OS
package manager (Homebrew, APT, etc...) to upgrade asdf or download the
latest asdf binary manually from the asdf website.

Please visit https://asdf-vm.com/ or https://github.com/asdf-vm/asdf for more
details.
asdf failed:
   0: Command failed: `/opt/homebrew/opt/asdf/libexec/bin/asdf update`
   1: `/opt/homebrew/opt/asdf/libexec/bin/asdf` failed: exit status: 1

Location:
   src/executor.rs:182
Retry? (y)es/(N)o/(s)hell/(q)uit
```

## Expected Behavior

Topgrade should not attempt to use asdf to self upgrade.

## Steps to reproduce

Install https://asdf-vm.com/ and then try `topgrade`.

## Possible Cause (Optional)

Self explanatory, asdf have stopped allowing it to upgrade itself. 

## Problem persists without calling from topgrade

- [x] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Additional Details
- Operation System/Version: macOS 15.2
- Installation: Homebrew - `brew install topgrade`
- Topgrade version: `topgrade 16.0.2`

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Detected "/opt/homebrew/opt/asdf/libexec/bin/asdf" as "asdf"

── 21:02:32 - asdf ─────────────────────────────────────────────────────────────
DEBUG Executing command `/opt/homebrew/opt/asdf/libexec/bin/asdf update`
Upgrading asdf via asdf update is no longer supported. Please use your OS
package manager (Homebrew, APT, etc...) to upgrade asdf or download the
latest asdf binary manually from the asdf website.

Please visit https://asdf-vm.com/ or https://github.com/asdf-vm/asdf for more
details.
DEBUG Command failed: Err(
   0: Command failed: `/opt/homebrew/opt/asdf/libexec/bin/asdf update`
   1: `/opt/homebrew/opt/asdf/libexec/bin/asdf` failed: exit status: 1

Location:
   src/executor.rs:182)
DEBUG Step "asdf" failed:
   0: Command failed: `/opt/homebrew/opt/asdf/libexec/bin/asdf update`
   1: `/opt/homebrew/opt/asdf/libexec/bin/asdf` failed: exit status: 1

Location:
   src/executor.rs:182
asdf failed:
   0: Command failed: `/opt/homebrew/opt/asdf/libexec/bin/asdf update`
   1: `/opt/homebrew/opt/asdf/libexec/bin/asdf` failed: exit status: 1

Location:
   src/executor.rs:182
</pre>
</details>

**Comment by SteveLauC** [comment]
Thanks for reporting this to us! Looks like asdf >= 0.15.0 would not allow self-update, I will fix this.
