### ISSUE TITLE
Not working in FreeBSD if sudo not available

### ISSUE THREAD

**Issue by jupiter126** [topgrade-rs/topgrade#11]
In followup to https://github.com/r-darwish/topgrade/issues/1023<br><br>

I was trying out topgrade and getting polkit errors, preventing topgrade from running.<br>
Installing sudo solved the issue - but not sure topgrade should depend on sudo<br>
(FreeBSD 13.1-RELEASE-p2)<br><br>

I do not have doas installed!<br><br>

desinstalled sudo to reproduce error:<br>
root#: topgrade<br>
―― 13:57:08 - FreeBSD Packages <br>
Error checking for authorization org.freedesktop.policykit.exec: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: get_kinfo_proc() failed for pid 3001: No such process<br>

Retry? (y)es/(N)o/(s)hell/(q)uit<br>

―― 13:57:16 - Composer <br>

Changed current directory to /root/.composer<br>
Do not run Composer as root/super user! See https://getcomposer.org/root for details<br>
Loading composer repositories with package information<br>
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/<br>
Info from https://repo.packagist.org: #StandWithUkraine<br>
Updating dependencies (including require-dev)<br>
Nothing to install or update<br>
Generating autoload files<br>

―― 13:57:17 - FreeBSD Update <br>
Error checking for authorization org.freedesktop.policykit.exec: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: get_kinfo_proc() failed for pid 3001: No such process<br>

Retry? (y)es/(N)o/(s)hell/(q)uit<br>

―― 13:57:21 - Summary <br>
FreeBSD Packages: FAILED<br>
composer: OK<br>
FreeBSD Upgrade: FAILED<br>

Error checking for authorization org.freedesktop.policykit.exec: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: get_kinfo_proc() failed for pid 3001: No such process<br>

**Comment by DottoDev** [comment]
Currently topgrade only supports privilege elevation with the help of tools like sudo or doas. Currently supported are doas, sudo, gsudo and pkexec as given by the following function.

`
pub fn sudo() -> Option<PathBuf> {
    which("doas")
        .or_else(|| which("sudo"))
        .or_else(|| which("gsudo"))
        .or_else(|| which("pkexec"))
} `

As far as I know there is no way to elevate privileges without those tools. Maybe it's possible through dbus and polkit but this would require a lot of tinkering and is probably not worth the effort.

If you use another piece of software instead of sudo/doas for privilege elevation it could be possible to get it to work as an alternative to sudo.

**Comment by jupiter126** [comment]
No, I was running topgrade as root

**Comment by DottoDev** [comment]
I'll look into that because normally it's not intended to be run directly as root.

**Comment by DottoDev** [comment]
I looked into that but as far as I can tell solving this would require a rework of the way we run code as root.
