### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by 0xMRTT** [topgrade-rs/topgrade#121]
That would be awesome if we can have a logo. I create this issue as a tracker, feel free to comment your ideas.

**Comment by 9999years** [comment]
There is the [original banner image here](https://github.com/topgrade-rs/topgrade/blob/6a6a84b0c511158841a731dda79e4aa4fb0689cd/doc/topgrade.png), though I've never really been a fan of the military / airforce vibes it gives off. +1 for replacing it. Maybe we could make some cute ascii art? :3

**Comment by 9999years** [comment]
(Bedazzles your open source project)

**Comment by SteveLauC** [comment]
Close as this has already been done
