### ISSUE TITLE
Add support of Bedrock Linux

### ISSUE THREAD

**Issue by 0xMRTT** [topgrade-rs/topgrade#125]
### Which tool is this about? Where is its repository?

https://bedrocklinux.org/

### Which operating systems are supported by this tool?

https://bedrocklinux.org/ -> Linux

### What should Topgrade do to figure out if the tool needs to be invoked?

Topgrade needs to invoke `pmm` (package manager manger) and upgrade all strats with (`brl`)

### Which exact commands should Topgrade run?

`sudo pmm -Syu` and `sudo brl update`

---

I would like to work on that (i'm going to submit a PR soon)

**Comment by DottoDev** [comment]
Sounds good

**Comment by 0xMRTT** [comment]
That's my distro if we can call that a distro

**Comment by DottoDev** [comment]
Noticed while writing tests that we already support bedrock linux to at least some extend
