### ISSUE TITLE
Version naming

### ISSUE THREAD

**Issue by 0xMRTT** [topgrade-rs/topgrade#143]
The GH-Action for publishing to the AUR require that each version to follow some rules:
```
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
```

Is it possiible to replace the `-` with a `.` ?

For example : `10.1.0-cd5` will be `10.1.0.cd5`

**Comment by DottoDev** [comment]
Will change it so that it just runs on main releases, not pre releases like -cd5
