### ISSUE TITLE
Getting Failure on Distrobox update when Distrobox is not installed

### ISSUE THREAD

**Issue by mdhankins1** [topgrade-rs/topgrade#158]
## What did you expect to happen?
I expect it would detect that Distrobox is not installed and bypass that section entirely.  Instead it gives a "Retry? (y)es/(N)o/(s)hell/(q)uit" message

## What actually happened?
I am running topgrade update on my Fedora 37 based system and it gives this error message when it gets to the Distrobox section and shows Distrobox Failure at the end.

## Additional Details
- Which operating system or Linux distribution are you using?  RisiOS 37 (based on Fedora 37)
- How did you install Topgrade? cargo
- Which version are you running?  10.1.0

All commands look fine.  It appears that it is just failing when it tries to run "distrobox upgrade --all" because distrobox is not installed.
<details>

<pre>

</pre>
</details>

**Comment by DottoDev** [comment]
Will fix now, thought I fixed everything but I have looked over the return values of the function.

**Comment by jojojojojoj5564656465465** [comment]
`2022-11-05T22:42:54.348Z ERROR topgrade::config > Failed to deserialize /home/endevour/.config/topgrade.toml
 2022-11-05T22:42:54.348Z ERROR topgrade::config > failed to load configuration: invalid TOML value, did you mean to use a quoted string? at line 58 column 2`

Hi do you know why i got those errors ?

**Comment by DottoDev** [comment]
Their seems to be an error in your config file at line 58.
If you can't find one please open a new Issue and include your config file.

**Comment by jojojojojoj5564656465465** [comment]
I delete my previous topgrade.toml and replace by the new one provided i don't know if it's different but now i can disable the git-repos and no more bugs. Thank you for your work topgrade is an amazing software
