### ISSUE TITLE
Paru issue and Distrobox again ! 

### ISSUE THREAD

**Issue by TechXero** [topgrade-rs/topgrade#163]
## What did you expect to happen?

For it to work....

## What actually happened?

Failed for Paru and Distrobox.. 

## Additional Details
- XeroLinux an Arch based disro 
- Installed from AUR
- Topgrade 10.1.2

<details>
<pre>
― 18:02:55 - Distrobox ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-11-06T16:02:55.916Z DEBUG topgrade::executor   > Running "/usr/bin/distrobox" "upgrade" "--all"
Missing dependency: we need a container manager.
Please install one of podman or docker.
You can follow the documentation on:
        man distrobox-compatibility
or:
        https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md

An error occurred
 2022-11-06T16:02:55.923Z DEBUG topgrade::runner     > Step "distrobox" failed: exit status: 127
 2022-11-06T16:02:55.923Z DEBUG topgrade::terminal   > Desktop notification: distrobox failed

―― 18:02:46 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
 2022-11-06T16:02:46.641Z DEBUG topgrade::utils  > Cannot find "powerpill"
 2022-11-06T16:02:46.641Z DEBUG topgrade::utils  > Detected "/usr/bin/paru" as "paru"
/usr/bin/paru: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
 2022-11-06T16:02:46.641Z DEBUG topgrade::executor > Running "/usr/bin/paru" "--pacman" "pacman" "-Syu" "--nodevel" "--noconfirm"
/usr/bin/paru: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
 2022-11-06T16:02:46.641Z DEBUG topgrade::runner   > Step "System update" failed: exit status: 127
 2022-11-06T16:02:46.641Z DEBUG topgrade::terminal > Desktop notification: System update failed
</pre>
</details>

**Comment by DottoDev** [comment]
Paru at least looks more like a dependency error of paru and not like a topgrade error. Distrobox on the other side start to annoy me because it seems as its impossible to just work.

**Comment by TechXero** [comment]
Remove Distrobox it's becoming too annoying.. I agree. Pru just got an update will build now...

**Comment by DottoDev** [comment]
Will put distrobox behind a feature for those who want to use it.

**Comment by TechXero** [comment]
Yeah not by default keep it optional..

**Comment by DottoDev** [comment]
I think I will just make a feature called unstable, where I can put stuff like distrobox or other "untested" features.

**Comment by TechXero** [comment]
> I think I will just make a feature called unstable, where I can put stuff like distrobox or other "untested" features.

Yep sure do that. Coz every time you enable it something goes wrong. Also Paru issue gone now after updating it. 

Btw if you haven't gotten the clue am the maintainer of XeroLinux. I included topgrade as an option aliased to `upall`

**Comment by dylanmtaylor** [comment]
Paru issue is actually an issue w/ paru. Rebuild that from source

**Comment by dylanmtaylor** [comment]
Is it not fixed for you in [10.1.2](https://github.com/topgrade-rs/topgrade/pull/160/commits/c1b85dfd58910ed0b688df7ddc4b15e3958c43b8)?

**Comment by DottoDev** [comment]
> Btw if you haven't gotten the clue am the maintainer of XeroLinux. I included topgrade as an option aliased to `upall`

Haven't heard of it till now, it looks great. Thanks for that :)

**Comment by TechXero** [comment]
> > Btw if you haven't gotten the clue am the maintainer of XeroLinux. I included topgrade as an option aliased to `upall`
> 
> Haven't heard of it till now, it looks great. Thanks for that :)

Great tools should get more users to use them ;)

**Comment by LeSnake04** [comment]
I made the initial implementation of distrobox.

I took a look at my code and aside the missing require, that you fixed already. 
Aside that my implementation looks like the other, that dont have this issue. 

I will investigate further and try a rewrite to make the code easier to understand for better debugging.

**Comment by LeSnake04** [comment]
It might be an issue when distrobox is installed, but no distro is set up.

**Comment by LeSnake04** [comment]
It's an issue where distrobox is installed but does not have a backend configured. 

I will implement a check if "distrobox list" fails. If it fails, it skips with an message saying distrobox is not configured.

**Comment by TechXero** [comment]
I do not have distrobox on my system yet error is there

**Comment by LeSnake04** [comment]
> I do not have distrobox on my system yet error is there

can you please run "distrobox list"?
It should give you the same output.

**Comment by TechXero** [comment]
> distrobox list

I created the distro I should know... But

```
command not found: distrobox
```

**Comment by dylanmtaylor** [comment]
> For me on master it skips when distrobox is not installed.
> 
> When it is installed and fails it might be an issue when distrobox is installed, but no container is set up.
> 
> Update: This is not as Issue.

I am also not seeing the distrobox updater run when it is not installed, on the latest master commit.

**Comment by TechXero** [comment]
Am using latest available version on AUR not -git 10.1.2

**Comment by dylanmtaylor** [comment]
> Am using latest available version on AUR not -git 10.1.2

Can you try building it from source?

**Comment by LeSnake04** [comment]
It must be installed somehow since how it should know an expected program output otherwise.... WTH

**Comment by LeSnake04** [comment]
just for testing: what happens if you install podman (one of the backend options)

**Comment by dylanmtaylor** [comment]
What does command -v distrobox show?

**Comment by TechXero** [comment]
> It must be installed somehow since how it should know an expected program output otherwise.... WTH

Yes but since I built the Distro I never included it coz I don't care for it on Arch this thing is better served on distros with more limited access to stuff..

**Comment by LeSnake04** [comment]
Can you search for the program in the full system: `fd distrobox /usr -H`

**Comment by TechXero** [comment]
> Can you search for the program in the full system: `fd distrobox / -H`

How many times do I have to repeat myself ? It's not included I built the Distro I know what it contains.. Is that in a language unknown ?

And as predicted nothing found..

**Comment by dylanmtaylor** [comment]
> > Can you search for the program in the full system: `fd distrobox / -H`
> 
> How many times do I have to repeat myself ? It's not included I built the Distro I know what it contains.. Is that in a language unknown ?
> 
> And as predicted nothing found..

People are just trying to troubleshoot, there's no need to get upset at them. Regardless of if you built the distro (although it seems to just be a spin of Arch - nothing wrong with it, but you clearly didn't build every single package, and it's impossible for you to know everything about the whole system), it makes sense to try to figure out the characteristics of the system so we know how the code interacts with it.

**Comment by TechXero** [comment]
> there's no need to get upset at them

Not upset but having to repeat oneself when it's right there in plain text ... Am sorry didn't mean to sound that way you guys are doing a great job, other devs just let issues go dormant for ages.. Thanks

**Comment by TechXero** [comment]
Ok gimme a few will prepare access through TeamViewer if you want more proof

**Comment by LeSnake04** [comment]
I dont need more proof. The  fd was enough proof

**Comment by dylanmtaylor** [comment]
You are using paru to manage your topgrade installation from the AUR, correct?

**Comment by TechXero** [comment]
> You are using paru to manage your topgrade installation from the AUR, correct?

Negative. Had Paru installed for testing I use Yay..

**Comment by dylanmtaylor** [comment]
Okay. I think the PKGBUILD is at cat ~/.cache/yay/clone/topgrade/PKGBUILD

Can you paste that so we can see what exactly it built and installed?

**Comment by TechXero** [comment]
U> Okay. I think the PKGBUILD is at cat ~/.cache/yay/clone/topgrade/PKGBUILD
> 
> Can you paste that so we can see what exactly it built and installed?

Well no since I build n package n host on my own repo for users.

**Comment by dylanmtaylor** [comment]
It's odd - I'm on Arch Linux (not a fork), and this is working for me:

―― 11:53:24 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
System update: OK
config-update: OK
oh-my-zsh: OK
pip3: OK
Containers: OK
Flatpak: OK
Firmware upgrades: OK

Distrobox is NOT installed and doesn't run, and my topgrade -V shows

➜  ~ topgrade -V
Topgrade 10.1.2

**Comment by dylanmtaylor** [comment]
This is why I want to make sure you're definitely on the right version as this was fixed recently.

**Comment by LeSnake04** [comment]
I would say IF (which it clearly isn't in this case) distrobox is installed and no backend is installed we should leave the default error message.

BTW I am downloading the ISO rn and will try to recreate it in a vm.

**Comment by TechXero** [comment]
> BTW I am downloading the ISO rn and will try to recreate it in a vm.

My ISO ? If so make sure to update once installed coz that ISO is from September 20th.. I release every 3 months..

**Comment by TechXero** [comment]
> I could not reproduce eighter issues with 10.1.2-1 on your stock ISO after update
> 
> (neighter with the upgrade button)
> 
> _Btw, your distro looks interesting. I am not a macOS UI fan, but the design and tooling you made seems great._

Suddenly issue disappeared here as well ... And thanks for the kind words..

**Comment by DottoDev** [comment]
Issue closed now?

**Comment by TechXero** [comment]
> Issue closed now?

Sure is sorry for any inconvenience dunno why it remained and how it's gone..

**Comment by DottoDev** [comment]
Don't worry
It's solved now so everyone is happy :)
