### ISSUE TITLE
Add Treesitter support for Neovim

### ISSUE THREAD

**Issue by Crazy-Ginger** [topgrade-rs/topgrade#183]
## Add TreeSitter Updates

[Neovim-Treesitter](https://github.com/nvim-treesitter/nvim-treesitter)

This appears to just be a simple addition to the existing vim/neovim commands.

I believe adding this to `src/steps/upgrade.vim`  will add support:
``` vim
if exists(":TSUpdate")
    echo "TreeSitter Update"
    TSUpdate
endif
```

**Comment by 9999years** [comment]
Sure. I've also wanted to make the output of that script visible to users.

**Comment by 9999years** [comment]
Fixed in #184

**Comment by 9999years** [comment]
BTW @DottoDev can you give me maintainer permissions so I can manage issues & stuff?

**Comment by DottoDev** [comment]
> BTW @DottoDev can you give me maintainer permissions so I can manage issues & stuff?

I thought I already did. You should have maintainer rights now.
