### ISSUE TITLE
Have a way to get the last time topgrade was run on the current (or remote) system

### ISSUE THREAD

**Issue by Larandar** [topgrade-rs/topgrade#185]
## I want to suggest some general feature

Topgrade should have a way to print/get the last time it was executed.

### User story

As a topgrade user, I want to be able to get the last time topgrade was executed. Ideally, this feature would be a CLI option that accepts an optional format (for example: `date` for UNIX date style formatting (US style, I guess), `iso` for ISO-8601 format or `human` for https://docs.rs/humantime/latest/humantime/ duration) 

## More information

If you feel this feature fits the topgrade scope, I can implement it and submit a PR relatively quickly. But I would welcome the community's input on a few points:

1. Should this value be global (regardless of modules enabled) or per module, returning the minimum of all last executions? (IMO: MVP global, see if per-module is needed later)
2. Is storing the _state_ in a `topgrade.toml` file [in the appropriate cache directory](https://docs.rs/directories-next/latest/directories_next/struct.ProjectDirs.html#method.cache_dir) appropriate? 
3. How should such an option be named? `--last-check`, `--last-execution`, any other suggestion? 

The second point is why I'm hesitant; topgrade being currently stateless I feel like current contributors' input is needed on whether this feature is in the scope of the project.

**Comment by 9999years** [comment]
What are you planning on using this data for?

I suggest writing a wrapper script that does something like `date > ~/.local/share/topgrade && topgrade` or similar.

**Comment by Larandar** [comment]
I plan to had a line in neofetch/motd indicating the last time topgrade was executed. My use case is indeed small I have to conceed.

Your solution would indeed work, and if I'm alone in the usecase I could do that (or in my case `set -Ux _topgrade_last_exec (date -Iseconds)` to save the time since I use fish it's easier)

**Comment by 9999years** [comment]
Maybe you could also add something to your `topgrade.toml` for this, like
```toml
[commands]
"Save topgrade run time" = "regenerate-motd.sh" # or whatever
```

**Comment by Larandar** [comment]
OMG, I just assumed the link in the README was up to datem and the documentation just lacking. But the wiki https://github.com/r-darwish/topgrade/wiki/Step-list has not been migrated yet after the fork.

It does indeed solve my usecase, I will close this issue and update later with a snippet if someone need the same feature one day.

**Comment by Larandar** [comment]
As promised a sample command to do that:
```toml
# Commands to run at the end of the execution
[commands]
"Topgrade: state update" = """
    touch ~/.local/share/topgrade.toml &&
    dasel put -f ~/.local/share/topgrade.toml string .state.last-execution $(date -Iseconds)
"""
```

On a note: there is `[pre-commands]` and `[commands]` but no `[post-commands]` (macOS steps run after the commands). Also having a `[sucess-commands]` and `[fail-commands]` might be useful to somebody one day :)
