### ISSUE TITLE
Rustup warning, the following packages contain code that will be rejected by a future version of Rust

### ISSUE THREAD

**Issue by CryoRenegade** [topgrade-rs/topgrade#204]
Full Message
```
Finished release [optimized] target(s) in 2m 40s
warning: the following packages contain code that will be rejected by a future version of Rust: ntapi v0.3.7
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```
so yeah, we may want to update dependencies.

**Comment by 9999years** [comment]
How do you get this message? On the `dev` branch I get this:

```ShellSession
$ git rev-parse HEAD
7649b74a8d1e52be17253bb3e35683f375c13f87

$ cargo report future-incompatibilities
error: no reports are currently available
```

**Comment by CryoRenegade** [comment]
Ok, i found the problem, tokio 1.8 includes mio which depends on ntapi@0.3.7, which will be rejected by cargo eventually, a possible solution is to update our tokio to a version made after November 2021, which was when mio was last updated with. This only affects targets that use x86_64-pc-windows-msvc, as mio isn't targeted to x86_64-pc-windows-gcc.

**Comment by DottoDev** [comment]
Every dependency update with a reason makes sense so good for me.

**Comment by CryoRenegade** [comment]
Tested on dev branch, and no errors to be seen. Thanks yall for your hard work!
