### ISSUE TITLE
Directly elevate option

### ISSUE THREAD

**Issue by D3SOX** [topgrade-rs/topgrade#205]
Transfered rom https://github.com/r-darwish/topgrade/issues/972

## I want to suggest some general feature
Topgrade should have an option to instantly elevate at the beginning. I'm used to instantly typing my password after running a command that requires superuser access.

## More information
My current workaround: https://github.com/D3SOX/dotfiles/commit/3c73021a3fe9ed02fd946107f77b69595c39fb0f

Maybe it's just a me-problem, so feel free to reject it

**Comment by 9999years** [comment]
Actually,  I'm pretty used to running `sudo whoami && topgrade` to avoid this, so I think there's genuine user need & this is easy to implement.

Anecdotally, the Homebrew installer also requests `sudo` at the beginning so it can explain the prompt & make sure it arrives early.

**Comment by 9999years** [comment]
🤔 should this go before or after `pre_commands`?

**Comment by DottoDev** [comment]
Definitely after pre commands else it could be used more easily to run malicious code because the user can be tricked into running own malicious or harmful pre commands under root, which is not as easy to do for native in topgrade integrated commands.

**Comment by DottoDev** [comment]
Closed with #219
