### ISSUE TITLE
Add makedeb/MPR support

### ISSUE THREAD

**Issue by sbstn87** [topgrade-rs/topgrade#207]
Hi,

will it be possible to add support for makedeb/MPR? 

Link: https://mpr.makedeb.org/

It is like AUR for Debian based systems: 
makedeb creates packages through the use of [PKGBUILDs](https://docs.makedeb.org/makedeb/pkgbuild-syntax): a packaging format designed to be concise, simple, and easy to pick up, all the while remaining powerful enough to match the flexibility of standard Debian packaging tools.

There is Mist, an MPR helper, which works like yay for AUR.

Link: https://github.com/makedeb/mist

**Comment by DottoDev** [comment]
Could you please post the commands required for updating with `mist`, because their documentation is unclear about that. Also does it replace `apt` for you, because in theory it should.

**Comment by sbstn87** [comment]
mist works just like apt, so the commands are: mist update && mist upgrade.

Yes, it does replace apt if used as above. I do not know if there is a way to use to update only the packages installed from MPR. 

But if apt/aptitude/nala are launched before mist when using topgrade, it would update only the MPR packages.
