### ISSUE TITLE
Exclusions?

### ISSUE THREAD

**Issue by badummtss** [topgrade-rs/topgrade#211]
I use topgrade on macOS (Ventura) and searching for a solution to exclude different apps which are installed over brew cask.

How can I do that?

**Comment by 9999years** [comment]
What do you mean? Which apps, and are they getting upgraded with something other than the Brew Cask step?

Maybe you can use the `disable` setting in `~/.config/topgrade.toml`:

https://github.com/topgrade-rs/topgrade/blob/b4407963ad828cc7ef41077d70a71f9806ef6c30/config.example.toml#L4-L5

**Comment by badummtss** [comment]
Hey @9999years I meant what I could do to exclude apps from upgrading.
The Scenario:

I have cask apps for which I have a license, if the developer update the app to a newer version, for which you need a newer license, it is unneccessary to update / upgrade the version for which I have already a license. 

Or if I wan't to stay on a different Version like an older Chromium or something else.

What I wish is to activate something in the topgrade.toml to say top grade "hey don't upgrade Version X from chromium, till I say it's okay to do that".

I hope this clarify your question.

**Comment by DottoDev** [comment]
The only way how this could work would be to have a config option to pass through arguments to brew, if brew has support for a argument like --skip-package or something like that.

**Comment by badummtss** [comment]
ok I found a solution. home-brew-cask-upgrade have a solution for pinning selected apps.
It works also with topgrade.

Thank you Guys.
