### ISSUE TITLE
Mark check_run() as depreceated.

### ISSUE THREAD

**Issue by DottoDev** [topgrade-rs/topgrade#214]
Currently check_run() is getting replaced by status_checked(). It would be a nice to have if check_run() would be marked as depreceated so it won't get used especially in newly written code.

**Comment by 9999years** [comment]
We could probably just replace it. `topgrade` isn't a huge codebase so it's pretty easy to refactor the entire thing to remove a method like this.

**Comment by aadi58002** [comment]
I ripgrep to see all occurances of the `check_run()` function in the project there seem to be no such function named `check_run()` currently in the code. So this issue should probably be closed.
![Screenshot_20221127_100322](https://user-images.githubusercontent.com/96418027/204119360-148b1805-a60b-44fe-a28e-ad90043580da.png)

**Comment by sankalp-khare** [comment]
@9999years I'm not seeing any usages of `check_run()` in master. Infact there's no declaration either, @DottoDev. Looks like it has been removed then?

**Comment by DottoDev** [comment]
Thx for checking.
