### ISSUE TITLE
antigen update is skipped when antigen selfupdate failed

### ISSUE THREAD

**Issue by xyz1001** [topgrade-rs/topgrade#22]
See [r-darwish/topgrade issue](https://github.com/r-darwish/topgrade/issues/1031) for details.

**Comment by DottoDev** [comment]
Could you try out if this branch works for you? https://github.com/DottoDev/topgrade-dev/tree/fixes-antigen

**Comment by xyz1001** [comment]
It seems that the left parenthesis is wrong. It should be 
```
let cmd = format!("source {} && (antigen selfupdate ; antigen update)", zshrc.display());
```

**Comment by DottoDev** [comment]
Thank you, will merge the corrected PR
