### ISSUE TITLE
Repo packages error Paru/Yay

### ISSUE THREAD

**Issue by TechXero** [topgrade-rs/topgrade#220]
## What did you expect to happen?

For it to work lol...

## What actually happened?

It error-ed out on system update with Paru n Yay. Works fine without them

## Additional Details
- Which operating system or Linux distribution are you using? +> ArchLinux (XeroLinux)
- How did you install Topgrade? => AUR
- Which version are you running? => 10.2.0

<details>
<pre>
-> error installing repo packages
System update failed: 
   0: Command failed: `/usr/bin/yay --pacman pacman -Syu`
   1: `/usr/bin/yay` failed: exit status: 1

Location:
   src/steps/os/archlinux.rs:49

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

System update failed: 
   0: Command failed: `/usr/bin/paru -Pw`
   1: `/usr/bin/paru` failed: exit status: 1

Location:
   src/steps/os/archlinux.rs:34

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
</pre>
</details>

**Comment by alsoGAMER** [comment]
```
―― 23:05:30 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
no new news
System update failed: 
   0: Command failed: /usr/bin/paru -Pw
   1: /usr/bin/paru failed: exit status: 1

Location:
   src/steps/os/archlinux.rs:34

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

**Comment by ahuston-0** [comment]
It looks like `paru -Pw` is actually just returning 1. Tried running it with `RUST_BACKTRACE=full` in the event that there was a silent error and I'm not seeing anything.

![image](https://user-images.githubusercontent.com/43225907/203869823-027b9928-fd8a-4130-ab82-d61df015915e.png)

**Comment by ahuston-0** [comment]
Further update:

It looks like this isn't new behavior from paru. `fn news` returns `Ok(1)` if there is no news, and this is from a commit from November 2020 (792e15c9d723f1061171a093c5e7cef673942531). 

![image](https://user-images.githubusercontent.com/43225907/203870901-f2a71468-8df4-4ca1-8571-ff12834315d2.png)

**Comment by ahuston-0** [comment]
Okay so I figured out it had something to do with the recent addition of `.status_checked()?` to the news check in `steps/os/archlinux.rs`. Also, `status_checked_with_codes` used elsewhere in the project would work great here to check for either a status code of 0 or 1, but that doesn't seem to seem to be available to the command implementation. With that in mind I wrote a really quick hack that seems to work. Haven't contributed to topgrade before though so there may be a better way of doing this.

![image](https://user-images.githubusercontent.com/43225907/203879553-0ffb193d-9829-4f98-9bd6-3603c66bf124.png)

**Comment by TechXero** [comment]
Wow... Well we now wait for devs to see your work... Am sticking with 10.1.0 for now... Thanks..

**Comment by DottoDev** [comment]
We had an internal change to a new function that handles the return codes of running commands but the default function expects the value of the return codes to be Unix Standard compliant which is not the case for some tools. We have another function that handles non-standard return codes and there will be a change to this function.

**Comment by DottoDev** [comment]
Could you please try out the changes in PR #228 .

**Comment by TechXero** [comment]
> Could you please try out the changes in PR #228 .

How ? Sorry am no dev, I just report issues lol..

**Comment by ahuston-0** [comment]
@DottoDev Looks like it works for me!

**Comment by DottoDev** [comment]
@ahuston-0 Great

@TechXero doesn't matter anymore, someone else already checked. But only that you know it, this would require you to checkout the branch the PR tries to merge and then run cargo run in this branch.

**Comment by TechXero** [comment]
> @ahuston-0 Great
> 
> @TechXero doesn't matter anymore, someone else already checked. But only that you know it, this would require you to checkout the branch the PR tries to merge and then run cargo run in this branch.

Again dunno how. am not a github pro.. I only know how to push n pull.. Testing PRs runing cargo dunno all that..

**Comment by DottoDev** [comment]
>@TechXero Again dunno how. am not a github pro.. I only know how to push n pull.. Testing PRs runing cargo dunno all that..

No Problem ;)

**Comment by guihkx** [comment]
For anyone that might need a workaround until the next release of topgrade:

Add the following to `~/.config/topgrade.toml`:

```toml
[linux]
show_arch_news = false
```
