### ISSUE TITLE
Dotnet update fails

### ISSUE THREAD

**Issue by BackSpace54** [topgrade-rs/topgrade#225]
## What did you expect to happen?
Updating Dotnet if necessary

## What actually happened?
The update command fails

## Additional Details
- Which operating system or Linux distribution are you using?
Manjaro Linux 22
- How did you install Topgrade?
Tested fresh extraction of topgrade-v10.2.0-x86_64-unknown-linux-gnu.tar.gz and selfupdate of topgrade
- Which version are you running? 
Topgrade 10.2.0

Got this error
.NET failed: 
   0: Command failed: `/usr/bin/dotnet tool list --global`

      Stderr:
      The command could not be loaded, possibly because:
        * You intended to execute a .NET application:
            The application 'tool' does not exist.
        * You intended to execute a .NET SDK command:
            No .NET SDKs were found.

      Download a .NET SDK:
      https://aka.ms/dotnet/download

      Learn about SDK resolution:
      https://aka.ms/dotnet/sdk-not-found
   1: `/usr/bin/dotnet` failed: exit status: 145

Location:
   src/steps/generic.rs:455

<details>

<pre>
DEBUG Step ".NET"
DEBUG Detected "/usr/bin/dotnet" as "dotnet"
DEBUG Executing command `/usr/bin/dotnet tool list --global`
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/dotnet tool list --global`

      Stderr:
      The command could not be loaded, possibly because:
        * You intended to execute a .NET application:
            The application 'tool' does not exist.
        * You intended to execute a .NET SDK command:
            No .NET SDKs were found.

      Download a .NET SDK:
      https://aka.ms/dotnet/download

      Learn about SDK resolution:
      https://aka.ms/dotnet/sdk-not-found
   1: `/usr/bin/dotnet` failed: exit status: 145

Location:
   src/steps/generic.rs:455

</pre>
</details>
Hello,

the problem seems to be this the command dotnet tool list is part of dotnet SDK and is not included in Dotnet runtime, see https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-list

Btw the dotnet update step was ok in topgrade 10.1.2

**Comment by DottoDev** [comment]
If I understand that right the command fails due to the command `dotnet` being available and `dotnet tools` being not available, because `dotnet` is provided by the dotnet runtime and `dotnet tool` is provided by the dotnet SDK`

**Comment by BackSpace54** [comment]
That's it.
I only have Dotnet runtime, dotnet tool is a command of the SDK.

**Comment by DottoDev** [comment]
I hope #229 solves it

**Comment by DottoDev** [comment]
@BackSpace54 could you try out PR #229 if it solves the problem for you?

**Comment by dtantono** [comment]
on Ubuntu 22.04 I find same issues
![2022-11-28_11-46](https://user-images.githubusercontent.com/29157187/204180750-16996afb-d632-4ba8-af10-ce92a596adcb.png)
 
![2022-11-28_11-46_1](https://user-images.githubusercontent.com/29157187/204180743-4c25b949-d678-4340-804d-8c896a00b5f4.png)

**Comment by BackSpace54** [comment]
Hi,

i've checked your changes and the problem is on some values you tested, i'll try to explain what i've found.

DotNet RunTime CLI commands output are invariably in english but it's not the same with DotNet SDK.

SDK is localized by default so once the SDK is installed the output will change (**all was tested on Manjaro**, DotNet SDK AUR).
If you install DotNet SDK on a german distro the output will be in german and so on with at least the following languages (cs, de, en, es, fr, it, ja, ko, pl, pt-BR, ru, zh-Hans, zh-Hant)
ie with DotNet SDK installled:

- german output

```
    dotnet --help
    Syntax: dotnet [runtime-options] [path-to-application] [arguments]

    Hiermit wird eine .NET-Anwendung ausgeführt.

    runtime-options:
    --additionalprobingpath <path>   Pfad, der die Suchrichtlinie und die zu suchenden Assemblys enthält.
    --additional-deps <path>         Pfad zur zusätzlichen Datei "deps.json".
    --depsfile                       Pfad zur Datei "<anwendung>.deps.json".
```

- italian output
```

    dotnet --help
    Sintassi: dotnet [runtime-options] [path-to-application] [arguments]

    Esegue un'applicazione .NET.

    runtime-options:
    --additionalprobingpath <path>   Percorso che contiene i criteri di esecuzione probe e gli assembly per cui eseguire il probe.
    --additional-deps <path>         Percorso del file deps.json aggiuntivo.
    --depsfile                       Percorso del file <applicazione>.deps.json
```


So in src/steps/generic.rs at line #488 you check the string "Package Id" in the result of the command `dotnet tool list--global` but with german language Package Id is spelled "Paket-ID" and in italian the output is "ID pacchetto".

- italian

```
dotnet tool list --global
ID pacchetto      Versione      Comandi
```

- german

```
dotnet tool list --global                                                           
Paket-ID      Version      Befehle
```

The workaroud could be to use the env variable DOTNET_CLI_UI_LANGUAGE to set the language in 'en' then do the topgrade dotnet update step then unset the env variable at the end of the process.
I've checked, set the 'en' language by `export DOTNET_CLI_UI_LANGUAGE=en` so `dotnet tool list--global` output is
```
dotnet tool list --global
Package Id      Version      Commands
```
At the end of dotnet update unset the env variable by `unset DOTNET_CLI_UI_LANGUAGE` to get it back to the default language.

Note: i use the DOTNET_CLI_UI_LANGUAGE env variable to get the german and italian output above.

I've not tested on Windows machines or Debian based distro, i can give it a try if you want.

Bye.
