### ISSUE TITLE
Topgrade not detecting Linux distribution OpenMandriva Lx 4.90 (Nickel) Cooker

### ISSUE THREAD

**Issue by lisandrocarmona** [topgrade-rs/topgrade#23]
## What did you expect to happen?
Topgrade to update OpenMandriva Lx 4.90 (Nickel) Cooker (openmandriva.org)

## What actually happened?
Error detecting current distribution: Unknown Linux Distribution

## Additional Details
- Which operating system or Linux distribution are you using? OpenMandriva Lx 4.90 (Nickel) Cooker
- How did you install Topgrade? cargo install topgrade
- Which version are you running?  Topgrade 9.0.1

Everything runs fine, except the distro update.
Rustup, Cargo, pip3, Vim, Containers, Flatpak, Firmware run ok.

<details>

<pre>
topgrade --dry-run
Error detecting current distribution: Unknown Linux Distribution

―― 09:03:35 - rustup ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /home/technical/.cargo/bin/rustup self update
Dry running: /home/technical/.cargo/bin/rustup update

―― 09:03:35 - Cargo ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /home/technical/.cargo/bin/cargo-install-update install-update --git --all
Dry running: /usr/bin/go env GOPATH

―― 09:03:35 - pip3 ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/python3 -m pip install --upgrade --user pip

―― 09:03:35 - Vim ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/vim -u /home/technical/.vimrc -U NONE -V1 -nNesS /tmp/.tmpyagdEz

―― 09:03:35 - Containers ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/docker pull ubuntu:22.04
Dry running: /usr/bin/docker pull portainer/portainer-ce:latest

―― 09:03:35 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/flatpak update --user -y

―― 09:03:35 - Flatpak System Packages ――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/flatpak update --system -y

―― 09:03:35 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/fwupdmgr refresh
Dry running: /usr/bin/fwupdmgr get-updates

―― 09:03:35 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
config-update: OK
rustup: OK
cargo: OK
pip3: OK
vim: OK
Containers: OK
Flatpak: OK
Firmware upgrades: OK
</pre>
</details>

**Comment by lisandrocarmona** [comment]
```
NAME="OpenMandriva Lx"
VERSION="4.90 (Nickel) Cooker"
ID="openmandriva"
VERSION_ID="4.90"
PRETTY_NAME="OpenMandriva Lx 4.90 (Nickel) Cooker"
BUILD_ID="20221008.17"
VERSION_CODENAME="nickel"
ANSI_COLOR="1;43"
LOGO="openmandriva"
CPE_NAME="cpe:/o:openmandriva:openmandriva_lx:4.90"
HOME_URL="http://openmandriva.org/"
BUG_REPORT_URL="https://github.com/OpenMandrivaAssociation/distribution/issues/"
SUPPORT_URL="https://forum.openmandriva.org"
PRIVACY_POLICY_URL="https://www.openmandriva.org/tos"
```

**Comment by DottoDev** [comment]
Could you pull and try out this branch?
https://github.com/DottoDev/topgrade-dev/tree/openmandriva

**Comment by lisandrocarmona** [comment]
> Could you pull and try out this branch? https://github.com/DottoDev/topgrade-dev/tree/openmandriva
**It worked like a charm!** Thanks.
Would I have to return to non-git (branch) version later?

Although I have (probably a non-specific distro) error:
$HOME/.cargo/bin/cargo-install-update: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: cannot open shared object file: No such file or directory
Any hint on how to move this on?

**Comment by DottoDev** [comment]
OpenMandriva support will be available through crates.io and as an official release later this week.

Currently no, sorry. Maybe you are missing the openssl or libressl dev package.

**Comment by lisandrocarmona** [comment]
> libressl

At the last attempt, I was almost giving up, it worked. It's just installing **lib64ssl1.1**
```

―― 15:04:35 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
System update: OK
rustup: OK
cargo: OK
pip3: OK
vim: OK
Containers: OK
Flatpak: OK
```

Thanks for your hard work.
