### ISSUE TITLE
Topgrade doesn't work with paru

### ISSUE THREAD

**Issue by eperulli** [topgrade-rs/topgrade#234]
Topgrade doesn't perform any update and exits with code status 1
Screenshot follows

Steps to reproduce:
run topgrade with paru installed

![Screenshot_20221127_183303](https://user-images.githubusercontent.com/52085800/204150856-82c4264c-4727-41ab-b13c-bf67baa4bb36.png)

**Comment by guihkx** [comment]
Thanks for reporting. It should be fixed by #235.

For now, as a workaround, you can prevent topgrade from checking for Arch Linux news by adding the following to `~/.config/topgrade.toml`:

```toml
[linux]
show_arch_news = false
```

**Comment by guihkx** [comment]
Actually, @DottoDev already worked on a fix in #228.

Additionally, this is a duplicate of #220.
