### ISSUE TITLE
AUR PKGBUILD outdated 

### ISSUE THREAD

**Issue by TechXero** [topgrade-rs/topgrade#24]
Hey

I was wondering how to build package from this fork. PKGBUILD on AUR still points to old Git repo... Am not good at making PKGBUILD files...

Thanks...

**Comment by DottoDev** [comment]
Currently you can only install it through cargo but I will contact the maintainer of the AUR package so that he maybe can change to our repo.

**Comment by TechXero** [comment]
Ok thanks.. Just update readme to remove AUR link until that happens just a recommendation...

**Comment by yochananmarqos** [comment]
@TechXero Since there are no releases yet, it would be better to contact the `topgrade-git` package maintainer instead.

**Comment by TechXero** [comment]
Just did that now.. Fingers crossed...

**Comment by DottoDev** [comment]
@TechXero give it one or two days and their will be a release and following that an AUR update.

**Comment by stefanhusmann** [comment]
Maintainer of AUR-package topgrade-git here. I have updated the PKGBUILD to point to this repo now. Strangely I had to create the directory target/release explicitely to make the build step work.

**Comment by TechXero** [comment]
> Maintainer of AUR-package topgrade-git here. I have updated the PKGBUILD to point to this repo now. Strangely I had to create the directory target/release explicitely to make the build step work.

Error 
![error](https://i.imgur.com/mpKivZp.png)

**Comment by DottoDev** [comment]
9.1.0 got released now

**Comment by DottoDev** [comment]
9.1.0 got released now

**Comment by yochananmarqos** [comment]
@DottoDev Please import the tags from darwish's repo and properly tag 9.1.0 here.

**Comment by yochananmarqos** [comment]
@stefanhusmann 

> I had to create the directory target/release 

@DottoDev That should not be necessary. The binary should go there, but using `export CARGO_TARGET_DIR=target` should work. It's not.

**Comment by DottoDev** [comment]
@yochananmarqos I don't know what I can do about that.

**Comment by yochananmarqos** [comment]
@DottoDev Sorry, I edited my message and didn't meant to tag you. It's fine.

Here's my Manjaro [PKGBUILD](https://gitlab.manjaro.org/packages/community/topgrade/-/blob/master/PKGBUILD) for reference.

**Comment by DottoDev** [comment]
@stefanhusmann it would be great if you would point the topgrade-git package to the dev branch because the dev branch will get new features earlier and not just bug fixes between two major releases.

**Comment by stefanhusmann** [comment]
I do not see a dev branch. Where is it?

**Comment by DottoDev** [comment]
Sorry, deleted it till I have set up some branch rules and a God CD pipeline. Will notice you when it's there again.
