### ISSUE TITLE
Newest version is apparently too demanding to compile on Raspberry Pi 3

### ISSUE THREAD

**Issue by Auravendill** [topgrade-rs/topgrade#240]
When upgrading from version 10.1.2 to 10.2.0 the compilation fails on Raspberry Pi 3 (with Raspian 11 32bit)

All the dependencies compile just fine, just the last step, where it compiles topgrade itself, fails. It seems the RAM usage gets to high.

That is really unfortunate, since topgrade is great for keeping pihole up to date as well. (And the Raspberry Pi 4 is basically unobtainable rn)

Maybe the newer versions can be tweaked to be as efficient to install as the older ones or there needs to be some alternative installation method for Raspberry Pi (and similar ARM boards).

**Comment by guihkx** [comment]
See if it helps if you build with `codegen-units=1`, e.g.:

```bash
RUSTFLAGS='-C codegen-units=1' cargo install topgrade
```

**Comment by Auravendill** [comment]
That did indeed work. Would it be possible to add this into topgrade, when it detects that the host has very limited RAM (if that is, what caused it)?

**Comment by guihkx** [comment]
I think something like that would only be possible if we had a custom build program (usually `build.rs`), that would detect the host's total RAM and then apply custom compiler flags based on that.

Another option is to set `codegen-units=1` by default for the `release` profile. The upside is having better code generation overall, although I hardly believe we'll see some obvious improvement, since `topgrade` is mostly about spawning other programs...

But the downside of that is having to wait even more for `topgrade` to compile, so... I don't know.

**Comment by DottoDev** [comment]
> I think something like that would only be possible if we had a custom build program (usually `build.rs`), that would detect the host's total RAM and then apply custom compiler flags based on that information.
> 
> 
> 
> Another option is to set `codegen-units=1` by default for the `release` profile in `Cargo.toml`. One of the upsides (besides less RAM usage), is an overall better code generation, although I hardly believe we'll see obvious improvements, since `topgrade` is mostly about spawning other programs...
> 
> 
> 
> But the downside of that is having to wait even more for `topgrade` to compile, so... I don't know.
> 
There is no real reason to set this for everyone except those on raspberry pis. But I think there is a possibility to set flags per architecture, so this could be a possibility.
> 
> This whole thing can also be avoided once (or if?) we provide pre-built binaries for common OSes/CPU architectures...
We do have them but currently not for raspberry.

**Comment by guihkx** [comment]
Oh, nice! I hadn't noticed that.

Shouldn't the `aarch64` build (or, in @Auravendill's case, the `armv7` build, due to him using the 32-bit version of Raspbian) run on the Pi 3? 🤔

**Comment by onemoz** [comment]
> Shouldn't the [pre-built](https://github.com/topgrade-rs/topgrade/releases/tag/v10.2.0) aarch64 package (or, in @Auravendill's case, the armv7 package, due to him using the 32-bit version of Raspbian) run on the Pi 3? 🤔

That works for me. Downloading `topgrade-v10.2.4-armv7-unknown-linux-gnueabihf.tar.gz` from the release works, and can self update on my raspberry pi 3.
