### ISSUE TITLE
Error while updating pnpm

### ISSUE THREAD

**Issue by uwussimo** [topgrade-rs/topgrade#241]
## What did you expect to happen?
Upgrade the pnpm packages which was installed via scoop

## What actually happened?
Throws error...

## Additional Details
- Windows with Arch WSL
- scoop installed topgrade
- Topgrade 10.2.0

<details>
<pre>
―― (Arch) 22:20:05 - Node Package Manager ――――――――――――――――――――――――――――――――――――――
pnpm failed:
   0: Failed to execute `/mnt/c/Users/papa/scoop/apps/volta/current/appdata/bin/pnpm root -g`
   1: Exec format error (os error 8)

Location:
   src/steps/node.rs:81

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.ERROR
   0: Command failed: `/usr/sbin/notify-send -a Topgrade Topgrade 'pnpm failed'`

      Stderr:
      GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
   1: `/usr/sbin/notify-send` failed: exit status: 1

Location:
   src/terminal.rs:107

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.</pre>
</details>

**Comment by guihkx** [comment]
Does it work if you manually run `pnpm root -g`?

**Comment by uwussimo** [comment]
> Does it work if you manually run `pnpm root -g`?

seems like the problem with that i didn't run pnpm setup to initialize global dir and export it in my bashrc. my sincere apologies.
