### ISSUE TITLE
Error while updating Flatpak

### ISSUE THREAD

**Issue by uwussimo** [topgrade-rs/topgrade#242]
## What did you expect to happen?
Update the flatpack packages in WSL.

## What actually happened?
Throws error...

## Additional Details
- Windows with Arch WSL
- scoop installed topgrade
- Topgrade 10.2.0

<details>
<pre>
―― (Arch) 22:20:33 - Flatpak System Packages ―――――――――――――――――――――――――――――――――――

Note that the directories

'/var/lib/flatpak/exports/share'
'/home/uwussimo/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: While opening repository /var/lib/flatpak/repo: opening repo: opendir(/var/lib/flatpak/repo): No such file or directory
Flatpak failed:
   0: Command failed: `/usr/sbin/flatpak update --system`
   1: `/usr/sbin/flatpak` failed: exit status: 1

Location:
   src/steps/os/linux.rs:593

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.ERROR
   0: Command failed: `/usr/sbin/notify-send -a Topgrade Topgrade 'Flatpak failed'`

      Stderr:
      GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
   1: `/usr/sbin/notify-send` failed: exit status: 1

Location:
   src/terminal.rs:107

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.</pre>
</details>

**Comment by guihkx** [comment]
Can you please share the output of:

```bash
flatpak remote-list
```

**Comment by DottoDev** [comment]
Could you please try it out with `skip_notify=true` set in the config file.

**Comment by uwussimo** [comment]
Got it. I'll post the result as soon as I'll get to home

**Comment by uwussimo** [comment]
Oops, my apologiess

**Comment by uwussimo** [comment]
> ```shell
> flatpak remote-list
> ```

seems like i was experiencing internal problems with flatpak due to missing repos

**Comment by DottoDev** [comment]
No problem mate
