### ISSUE TITLE
Upgrading `ruby_gems` step fails

### ISSUE THREAD

**Issue by mheob** [topgrade-rs/topgrade#246]
## What did you expect to happen?

`topgrade` should run without errors and upgrade my system.

## What actually happened?

I get an error at the `upgrade ruby_gems` step.
No matter if I run `topgrade` or `topgrade --only ruby_gems`.

## Additional Details
- Which operating system or Linux distribution are you using?
  > macOS Ventura 13.0.1
  > MacBook Pro 2019 (Intel)

- How did you install Topgrade?
  > Homebrew

- Which version are you running?
  > `Topgrade 10.2.1`

<details>
<pre>
topgrade --only ruby_gems -v
DEBUG Configuration at /Users/a.boehm/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { pre_sudo: None, pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: Some(true), autoremove: Some(true) }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }) }
DEBUG Version: 10.2.1
DEBUG OS: x86_64-apple-darwin
DEBUG Args { inner: ["topgrade", "--only", "ruby_gems", "-v"] }
DEBUG Binary path: Ok("/usr/local/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/local/bin/git" as "git"
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/Users/a.boehm/.config/emacs" doesn't exist
DEBUG Path "/Users/a.boehm/.emacs.d" doesn't exist
DEBUG /Users/a.boehm/.ideavimrc does not exists
DEBUG /Users/a.boehm/.intellimacs does not exists
DEBUG /Users/a.boehm/dev/tools/macos/dotfiles/.zshrc is a file. Checking /Users/a.boehm/dev/tools/macos/dotfiles
DEBUG Checking if /Users/a.boehm/dev/tools/macos/dotfiles is a git repository
DEBUG Executing command `/usr/local/bin/git rev-parse --show-toplevel`
DEBUG Checking if /Users/a.boehm/.config/fish is a git repository
DEBUG Executing command `/usr/local/bin/git rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `/usr/local/bin/git rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any of the parent directories): .git
   1: `/usr/local/bin/git` failed: exit status: 128

Location:
   src/steps/git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG /Users/a.boehm/Library/Application Support/openbox does not exists
DEBUG /Users/a.boehm/Library/Application Support/bspwm does not exists
DEBUG /Users/a.boehm/Library/Application Support/i3 does not exists
DEBUG /Users/a.boehm/Library/Application Support/sway does not exists
DEBUG Step "rubygems"
DEBUG Detected "/usr/local/opt/ruby/bin/gem" as "gem"
DEBUG Path "/Users/a.boehm/.gem" exists

―― 07:05:08 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Detected rbenv. Avoiding --user-install
DEBUG Executing command `/usr/local/opt/ruby/bin/gem 'update --system' --user-install`
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command update --system
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:198:in `find_command'
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:183:in `process_args'
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:51:in `run'
	/usr/local/opt/ruby/bin/gem:13:in `<main>'
DEBUG Command failed: Err(
   0: Command failed: `/usr/local/opt/ruby/bin/gem 'update --system' --user-install`
   1: `/usr/local/opt/ruby/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "rubygems" failed:
   0: Command failed: `/usr/local/opt/ruby/bin/gem 'update --system' --user-install`
   1: `/usr/local/opt/ruby/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
rubygems failed:
   0: Command failed: `/usr/local/opt/ruby/bin/gem 'update --system' --user-install`
   1: `/usr/local/opt/ruby/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.DEBUG Desktop notification: rubygems failed

Retry? (y)es/(N)o/(s)hell/(q)uit%                                                                                                                                     
</pre>
</details>

**Comment by DottoDev** [comment]
Thanks for reporting this. Could you please run topgrade with the environment variable `RUST_BACKTRACE=1` set and post the output. You can set it with `export RUST_BACKTRACE=1 `.
Also could you run `gem update --system --user-install ` directly and see if it works.

**Comment by mheob** [comment]
Sure. Here are the outputs.

```console
$ RUST_BACKTRACE=1 topgrade --only ruby_gems

―― 08:31:58 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ERROR:  While executing gem ... (Gem::UnknownCommandError)
    Unknown command update --system
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:198:in `find_command'
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:183:in `process_args'
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
	/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:51:in `run'
	/usr/local/opt/ruby/bin/gem:13:in `<main>'
rubygems failed:
   0: Command failed: `/usr/local/opt/ruby/bin/gem 'update --system' --user-install`
   1: `/usr/local/opt/ruby/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:100

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮
   3: <E as eyre::context::ext::StdError>::ext_report::h7c058fe09910d455
      at <unknown source file>:<unknown line>
   4: <std::process::Command as topgrade::command::CommandExt>::status_checked_with::h23298938ae8b8b2c
      at <unknown source file>:<unknown line>
   5: topgrade::runner::Runner::execute::hc84ec70a679ad14d
      at <unknown source file>:<unknown line>
   6: topgrade::run::h15bb5368c692e375
      at <unknown source file>:<unknown line>
   7: topgrade::main::hfbd329ac486d7044
      at <unknown source file>:<unknown line>
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::h0c9eaf12ed8e1105
      at <unknown source file>:<unknown line>
   9: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit

―― 08:32:30 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
rubygems: FAILED
```

```console
$ gem update --system --user-install

Installing RubyGems 3.3.26
  Successfully built RubyGem
  Name: bundler
  Version: 2.3.26
  File: bundler-2.3.26.gem
Bundler 2.3.26 installed
RubyGems 3.3.26 installed
Regenerating binstubs
Regenerating plugins
/Users/mheob/.gem/ruby/3.1.0/gems/bundler-2.3.26/lib/bundler/version.rb:4: warning: already initialized constant Bundler::VERSION
/usr/local/lib/ruby/gems/3.1.0/gems/rubygems-update-3.3.26/bundler/lib/bundler/version.rb:4: warning: previous definition of VERSION was here
Parsing documentation for rubygems-3.3.26
Installing ri documentation for rubygems-3.3.26

 # 3.3.26 / 2022-11-16

## Enhancements:

* Upgrade rb-sys to 0.9.37. Pull request #6047 by ianks
* Installs bundler 2.3.26 as a default gem.

[... and more ouput here]
```

**Comment by DottoDev** [comment]
I don't think I have a clue why topgrade fails xD
What's the location of your gem binary. Could you run `which gem` please.

**Comment by mheob** [comment]
```console
$ which gem
/usr/local/opt/ruby/bin/gem
```

**Comment by DottoDev** [comment]
Why does the command fail, I have to look into that more closely.
