### ISSUE TITLE
macOS system update stuck on "downloaded"

### ISSUE THREAD

**Issue by piersandro** [topgrade-rs/topgrade#258]
## What did you expect to happen?
`topgrade` should complete the _macOS system update_ and ask to reboot the system.

## What actually happened?
After downloading the update it remains stuck on _Downloaded_ step. 
To complete the operation I need to use the graphical interface in System Preferences.

## Additional Details
- Which operating system or Linux distribution are you using? **macOS 13.1 beta 4** (I have the same problem by months)
- How did you install Topgrade? `brew install topgrade`
- Which version are you running? **Topgrade 10.2.2**

<details>
<pre>
―― 19:09:45 - macOS system update ――――――――――――――――――――――――――――――――――――――――――――――
Finding available software
DEBUG Executing command `softwareupdate --list`
DEBUG Utf8Output { status: ExitStatus(unix_wait_status(0)), stdout: "Software Update Tool\n\nFinding available software\nSoftware Update found the following new or updated software:\n* Label: macOS Ventura 13.1-22C65\n\tTitle: macOS Ventura 13.1, Version: 13.1, Size: 1050528K, Recommended: YES, Action: restart, \n", stderr: "" }
A system update is available. Do you wish to install it? (y)es/(N)o
DEBUG Executing command `softwareupdate --install --all --no-scan`
Software Update Tool

Finding available software
Downloading macOS Ventura 13.1
Password: 

Downloaded: macOS Ventura 13.1
</pre>
</details>

**Comment by DottoDev** [comment]
This is all which is possible over the command line as far as I know. Closing as won't fix.

**Comment by piersandro** [comment]
Is it normal for topgrade to remain blocked for hours requesting a CTRL+C from the terminal?
If the macOS system update from the terminal will end like this, it is not possible to continue to the next step after downloading the update?

**Comment by DottoDev** [comment]
I have no clue why macos is doing this tbh. I can't really do more then read the man page and try to implement what it says because I'm not on OSX
