### ISSUE TITLE
Crash @ line #491 in generic.rs - unwrap() function - DotNet step

### ISSUE THREAD

**Issue by BackSpace54** [topgrade-rs/topgrade#273]
## What did you expect to happen?
No crashing

## What actually happened?
Show this message: "The application panicked (crashed)."

## Additional Details
- Which operating system or Linux distribution are you using?
- How did you install Topgrade?
- Which version are you running? 

EndeavourOS Linux
Self update of Topgrade
Topgrade 10.2.3

―― 16:04:45 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/paru -Pw
Dry running: /usr/bin/paru --pacman pacman -Syu

―― 16:04:45 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: zsh /home/flo/.oh-my-zsh/tools/upgrade.sh

―― 16:04:45 - TLDR ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/tldr --update
Dry running: /usr/bin/dotnet -h
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/steps/generic.rs:491

<details>

<pre>
DEBUG Step ".NET"
DEBUG Detected "/usr/bin/dotnet" as "dotnet"
DEBUG Executing command `/usr/bin/dotnet -h`
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/steps/generic.rs:491
</pre>
</details>

**Comment by DottoDev** [comment]
I know why this has happened, sorry, will fix

**Comment by DottoDev** [comment]
Closed by #274
