### ISSUE TITLE
Crash @ line #491 in generic.rs - unwrap() function an `Err` value - DotNet step

### ISSUE THREAD

**Issue by BackSpace54** [topgrade-rs/topgrade#276]
## What did you expect to happen?
No crashing

## What actually happened?
Show this message: "The application panicked (crashed)."

## Additional Details
- Which operating system or Linux distribution are you using?
- How did you install Topgrade?
- Which version are you running? 
Linux Mint 21 Vanessa
Self update of Topgrade
Topgrade 10.2.4
Note: the Dotnet Runtime 5.0.17 is a snap package

Dry running: /snap/bin/dotnet -h
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: 
   0: Dry running

Location:
   /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/convert/mod.rs:726

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: src/steps/generic.rs:491

<details>

<pre>
DEBUG Step ".NET"
DEBUG Detected "/snap/bin/dotnet" as "dotnet"
DEBUG Executing command `/snap/bin/dotnet -h`
DEBUG Command failed: Err(
   0: Command failed: `/snap/bin/dotnet -h`

      Stdout:
      Usage: dotnet [host-options] [path-to-application]

      path-to-application:
        The path to an application .dll file to execute.

      host-options:
        --additionalprobingpath <path>  Path containing probing policy and assemblies to probe for.
        --depsfile <path>               Path to <application>.deps.json file.
        --runtimeconfig <path>          Path to <application>.runtimeconfig.json file.
        --fx-version <version>          Version of the installed Shared Framework to use to run the application.
        --roll-forward <value>          Roll forward to framework version (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable)
        --additional-deps <path>        Path to additional deps.json file.
        --list-runtimes                 Display the installed runtimes
        --list-sdks                     Display the installed SDKs

      Common Options:
        -h|--help                           Displays this help.
        --info                              Display .NET information.
   1: `/snap/bin/dotnet` failed: exit status: 129

Location:
   src/steps/generic.rs:491

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: 
   0: Command failed: `/snap/bin/dotnet -h`

      Stdout:
      Usage: dotnet [host-options] [path-to-application]

      path-to-application:
        The path to an application .dll file to execute.

      host-options:
        --additionalprobingpath <path>  Path containing probing policy and assemblies to probe for.
        --depsfile <path>               Path to <application>.deps.json file.
        --runtimeconfig <path>          Path to <application>.runtimeconfig.json file.
        --fx-version <version>          Version of the installed Shared Framework to use to run the application.
        --roll-forward <value>          Roll forward to framework version (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable)
        --additional-deps <path>        Path to additional deps.json file.
        --list-runtimes                 Display the installed runtimes
        --list-sdks                     Display the installed SDKs

      Common Options:
        -h|--help                           Displays this help.
        --info                              Display .NET information.
   1: `/snap/bin/dotnet` failed: exit status: 129

Location:
   src/steps/generic.rs:491

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: src/steps/generic.rs:491
</pre>
</details>

Hi,

i don't understand why `/snap/bin/dotnet -h` failed on my system, in a terminal the same command runs without error...

Note:
`/snap/bin/dotnet --info

Host (useful for support):
  Version: 5.0.17
  Commit:  6a98414363

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.17 [/snap/dotnet-runtime-50/24/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download`

Bye.

**Comment by DottoDev** [comment]
I don't get why it does that but I'll look into it

**Comment by loehden** [comment]
This seems to be an error again if the .NET SDK is not installed (see #225). After installing .NET SDK the error does not appear anymore.

**Comment by DottoDev** [comment]
I still don't know why it doesn't work. There is an error, I fix it, it works for someone and then it doesn't work for the next person.

**Comment by DottoDev** [comment]
Could you try out the dev branch, could be that the fixes are not in the release branch, if they aren't that's my mistake and I'm sorry.

**Comment by loehden** [comment]
> I still don't know why it doesn't work. There is an error, I fix it, it works for someone and then it doesn't work for the next person.

I do not think it is the same error, since #225 has been fixed for me for some time and now a similar error occurred and I installed the SDK again to check if it fixes the new error. Also topgrade completely crashed and closes after this error, while for #225 one could continue as far as i remember.

**Comment by loehden** [comment]
> Could you try out the dev branch, could be that the fixes are not in the release branch, if they aren't that's my mistake and I'm sorry.

Is there a way to install the dev branch via cargo, or do I have to build it myself?

**Comment by DottoDev** [comment]
@loehden you have to build it yourself, if you don't know how just tell me and I'll explain it to you.

**Comment by loehden** [comment]
I manged to build from the dev tree. But the weird thing is, even the release version is working now after having uninstalled the SDK with chocolatey. Maybe there is some configuration step in the installation of the SDK (ENV variable?) that fixes the problem and remains after the removal of teh SDK. So I am afraid, that I cannot compare both builds this way.

**Comment by loehden** [comment]
It looks like uninstalling via `choco install dotnet-sdk` did not removed the DK completly, I had to remove two other chocolatey packages. Now the error appears again, for both the release and the dev build.
