### ISSUE TITLE
Topgrade on Windows can't self-upgrade due to missing release binary on release page

### ISSUE THREAD

**Issue by ffloimair** [topgrade-rs/topgrade#277]
## What did you expect to happen?
Topgrade should self-upgrade

## What actually happened?
Error message
`Self update error: ReleaseError: No asset found for target: x86_64-pc-windows-msvc`

## Additional Details
- Which operating system or Linux distribution are you using?
Microsoft Windows -> topgrade 10.2.2 x86_64-pc-windows-msvc
- How did you install Topgrade?
Downloaded earlier release from github releases page of this project
- Which version are you running? 
Topgrade 10.2.2

<details>

<pre>

</pre>
</details>

As I interpret it, release 10.2.3 and 10.2.4 there is no x86_64-pc-windows-msvc package available therefore topgrade self-upgrade rightfully throws the above error.

**Comment by Lim-Dul** [comment]
Confirming the issue. I checked the official build script in this repo ([build-all.sh](https://github.com/topgrade-rs/topgrade/blob/master/build-all.sh)) and there's no msvc-target in there by default. The build script hasn't been updated for 2 months though, so I have no idea where the msvc builds came from before.
Built from source myself via ` cross build --release --target x86_64-pc-windows-msvc` (already had the build environment set up) and it works just fine.

**Comment by DottoDev** [comment]
The release comes from the CD Pipeline but it failed for some reason for this release.

**Comment by ffloimair** [comment]
> The release comes from the CD Pipeline but it failed for some reason for this release.

As far as I see it the error has been introduced in this commit e84173be8f7583833c6d01c68a7ab26a32031d6c

The error seems to be executing the .execute() method with the parameter "&winget" instead of "winget" which is clearly shown in the build log of 10.2.4 on Windows.

**Comment by DottoDev** [comment]
This is strange because every release till now seems to not have problem even tho this commit has already been made a long time ago.
