### ISSUE TITLE
Error detecting current distribution: PCLinuxOS (uses APT-RPM)

### ISSUE THREAD

**Issue by hunter2k01** [topgrade-rs/topgrade#278]
## What did you expect to happen?
To upgrade since the same commands for apt to update and upgrade work in apt-rpm.

## What actually happened?
Although Flatpak successfully updated, the PCLinuxOS packages did not because I receive the following error: `Error detecting current distribution: Unknown Linux Distribution`

## Additional Details
- Which operating system or Linux distribution are you using?
PCLinuxOS x86_64
- How did you install Topgrade?
With `cargo install topgrade`
- Which version are you running? 
Topgrade 10.2.4

<details>

<pre>
DEBUG Configuration at /home/hunter/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { pre_sudo: None, pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: Some(false), yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None }), npm: Some(NPM { use_sudo: Some(false) }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: Some(false) }), distrobox: Some(Distrobox { use_root: None, containers: None }) }
DEBUG Detected "/usr/bin/notify-send" as "notify-send"
DEBUG Version: 10.2.4
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/home/hunter/.cargo/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "doas"
DEBUG Cannot find "sudo"
DEBUG Cannot find "gsudo"
DEBUG Detected "/usr/bin/pkexec" as "pkexec"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
Error detecting current distribution: Unknown Linux Distribution
DEBUG Step "config-update"
DEBUG Step "Brew"
DEBUG Step "yadm"
DEBUG Step "nix"
DEBUG Step "guix"
DEBUG Step "home-manager"
DEBUG Step "asdf"
DEBUG Step "pkgin"
DEBUG Step "bun"
DEBUG Path "/home/hunter/.config/emacs" doesn't exist
DEBUG Path "/home/hunter/.emacs.d" doesn't exist
DEBUG /home/hunter/.doom.d does not exists
DEBUG /home/hunter/.vim does not exists
DEBUG /home/hunter/.config/nvim does not exists
DEBUG /home/hunter/.ideavimrc does not exists
DEBUG /home/hunter/.intellimacs does not exists
DEBUG /home/hunter/.dotfiles does not exists
DEBUG /home/hunter/.zshrc does not exists
DEBUG /home/hunter/.tmux does not exists
DEBUG /home/hunter/.config/fish does not exists
DEBUG /home/hunter/.config/openbox does not exists
DEBUG /home/hunter/.config/bspwm does not exists
DEBUG /home/hunter/.config/i3 does not exists
DEBUG /home/hunter/.config/sway does not exists
DEBUG Step "Git repositories"
DEBUG Step "zr"
DEBUG Step "antibody"
DEBUG Step "antigen"
DEBUG Step "zgenom"
DEBUG Step "zplug"
DEBUG Step "zinit"
DEBUG Step "zi"
DEBUG Step "zim"
DEBUG Step "oh-my-zsh"
DEBUG Step "fisher"
DEBUG Step "bash-it"
DEBUG Step "oh-my-fish"
DEBUG Step "fish-plug"
DEBUG Step "fundle"
DEBUG Step "tmux"
DEBUG Step "TLDR"
DEBUG Step "pearl"
DEBUG Step "Gnome Shell Extensions"
DEBUG Detected "/usr/bin/gdbus" as "gdbus"
DEBUG Step "SDKMAN!"
DEBUG Detected "/bin/bash" as "bash"
DEBUG Step "rcm"
DEBUG Step "apm"
DEBUG Step "fossil"
DEBUG Step "rustup"
DEBUG Step "juliaup"
DEBUG Step ".NET"
DEBUG Step "choosenim"
DEBUG Step "cargo"
DEBUG Path "/home/hunter/.cargo" exists
DEBUG Detected "/usr/bin/cargo" as "cargo"
DEBUG Path "/home/hunter/.cargo/.crates.toml" exists

―― 10:41:42 - Cargo ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Path "/home/hunter/.cargo/bin/cargo-install-update" doesn't exist
cargo-update isn't installed so Topgrade can't upgrade cargo packages.
Install cargo-update by running `cargo install cargo-update`
DEBUG Step "Flutter"
DEBUG Step "go-global-update"
DEBUG Step "gup"
DEBUG Step "Emacs"
DEBUG Step "opam"
DEBUG Step "vcpkg"
DEBUG Step "pipx"
DEBUG Step "conda"
DEBUG Step "pip3"
DEBUG Detected "/usr/bin/python3" as "python3"
DEBUG Executing command `/usr/bin/python3 -m pip`

―― 10:41:42 - pip3 ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/python3 -m pip install --upgrade --user pip`
Requirement already satisfied: pip in ./.local/lib/python3.10/site-packages (22.3.1)
DEBUG Step "ghcup"
DEBUG Step "stack"
DEBUG Step "tlmgr"
DEBUG Step "myrepos"
DEBUG Step "chezmoi"
DEBUG Step "jetpack"
DEBUG Step "vim"
DEBUG Detected "/bin/vim" as "vim"
DEBUG Executing command `/bin/vim --version`
DEBUG Step "Neovim"
DEBUG Step "The Ultimate vimrc"
DEBUG Step "voom"
DEBUG Step "Kakoune"
DEBUG Step "helix"
DEBUG Step "npm"
DEBUG Step "yarn"
DEBUG Step "pnpm"
DEBUG Step "Containers"
DEBUG Step "deno"
DEBUG Step "composer"
DEBUG Step "krew"
DEBUG Step "helm"
DEBUG Step "gem"
DEBUG Step "rubygems"
DEBUG Step "julia"
DEBUG Step "haxelib"
DEBUG Step "sheldon"
DEBUG Step "rtcl"
DEBUG Step "bin"
DEBUG Step "gcloud"
DEBUG Step "micro"
DEBUG Step "raco"
DEBUG Step "spicetify"
DEBUG Step "GitHub CLI Extensions"
DEBUG Step "deb-get"
DEBUG Step "toolbx"
DEBUG Step "Flatpak"
DEBUG Detected "/usr/bin/flatpak" as "flatpak"

―― 10:41:43 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/flatpak update --user`
Looking for updates…

Nothing to do.

―― 10:41:43 - Flatpak System Packages ――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/flatpak update --system`
Looking for updates…

(/usr/bin/flatpak update:5354): dconf-WARNING **: 10:41:43.950: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user: Permission denied

Nothing to do.
DEBUG Step "snap"
DEBUG Step "pacstall"
DEBUG Step "pacdef"
DEBUG Step "protonup"
DEBUG Step "distrobox"
DEBUG Step "pihole"
DEBUG Step "Firmware upgrades"
DEBUG Step "Restarts"
DEBUG Step "Vagrant boxes"

―― 10:41:44 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
config-update: OK
Brew: SKIPPED: Cannot find "brew" in PATH
yadm: SKIPPED: Cannot find "yadm" in PATH
nix: SKIPPED: Cannot find "nix" in PATH
guix: SKIPPED: Cannot find "guix" in PATH
home-manager: SKIPPED: Cannot find "home-manager" in PATH
asdf: SKIPPED: Cannot find "asdf" in PATH
pkgin: SKIPPED: Cannot find "pkgin" in PATH
bun: SKIPPED: Cannot find "bun" in PATH
Git repositories: SKIPPED: No repositories to pull
zr: SKIPPED: Cannot find "zsh" in PATH
antibody: SKIPPED: Cannot find "zsh" in PATH
antigen: SKIPPED: Cannot find "zsh" in PATH
zgenom: SKIPPED: Cannot find "zsh" in PATH
zplug: SKIPPED: Cannot find "zsh" in PATH
zinit: SKIPPED: Cannot find "zsh" in PATH
zi: SKIPPED: Cannot find "zsh" in PATH
zim: SKIPPED: Cannot find "zsh" in PATH
oh-my-zsh: SKIPPED: Cannot find "zsh" in PATH
fisher: SKIPPED: Cannot find "fish" in PATH
bash-it: SKIPPED: Path "/home/hunter/.bash_it" doesn't exist
oh-my-fish: SKIPPED: Cannot find "fish" in PATH
fish-plug: SKIPPED: Cannot find "fish" in PATH
fundle: SKIPPED: Cannot find "fish" in PATH
tmux: SKIPPED: Path "/home/hunter/.tmux/plugins/tpm/bin/update_plugins" doesn't exist
TLDR: SKIPPED: Cannot find "tldr" in PATH
pearl: SKIPPED: Cannot find "pearl" in PATH
Gnome Shell Extensions: SKIPPED: Desktop doest not appear to be gnome
SDKMAN!: SKIPPED: Path "/home/hunter/.sdkman/bin/sdkman-init.sh" doesn't exist
rcm: SKIPPED: Cannot find "rcup" in PATH
apm: SKIPPED: Cannot find "apm" in PATH
fossil: SKIPPED: Cannot find "fossil" in PATH
rustup: SKIPPED: Cannot find "rustup" in PATH
juliaup: SKIPPED: Cannot find "juliaup" in PATH
.NET: SKIPPED: Cannot find "dotnet" in PATH
choosenim: SKIPPED: Cannot find "choosenim" in PATH
cargo: SKIPPED: cargo-update isn't installed so Topgrade can't upgrade cargo packages.
Install cargo-update by running `cargo install cargo-update`
Flutter: SKIPPED: Cannot find "flutter" in PATH
go-global-update: SKIPPED: Cannot find "go" in PATH
gup: SKIPPED: Cannot find "go" in PATH
Emacs: SKIPPED: Cannot find "emacs" in PATH
opam: SKIPPED: Cannot find "opam" in PATH
vcpkg: SKIPPED: Cannot find "vcpkg" in PATH
pipx: SKIPPED: Cannot find "pipx" in PATH
conda: SKIPPED: Cannot find "conda" in PATH
pip3: OK
ghcup: SKIPPED: Cannot find "ghcup" in PATH
stack: SKIPPED: Cannot find "stack" in PATH
tlmgr: SKIPPED: tlmgr must be explicity enabled in the configuration to run in Android/Linux
myrepos: SKIPPED: Cannot find "mr" in PATH
chezmoi: SKIPPED: Cannot find "chezmoi" in PATH
jetpack: SKIPPED: Cannot find "jetpack" in PATH
vim: SKIPPED: Path "/home/hunter/.vim/vimrc" doesn't exist
Neovim: SKIPPED: Cannot find "nvim" in PATH
The Ultimate vimrc: SKIPPED: Path "/home/hunter/.vim_runtime" doesn't exist
voom: SKIPPED: Cannot find "voom" in PATH
Kakoune: SKIPPED: Cannot find "kak" in PATH
helix: SKIPPED: Cannot find "helix" in PATH
npm: SKIPPED: Cannot find "npm" in PATH
yarn: SKIPPED: Cannot find "yarn" in PATH
pnpm: SKIPPED: Cannot find "pnpm" in PATH
Containers: SKIPPED: Cannot find "docker" in PATH
deno: SKIPPED: Cannot find "deno" in PATH
composer: SKIPPED: Cannot find "composer" in PATH
krew: SKIPPED: Cannot find "kubectl-krew" in PATH
helm: SKIPPED: Cannot find "helm" in PATH
gem: SKIPPED: Cannot find "gem" in PATH
rubygems: SKIPPED: Cannot find "gem" in PATH
julia: SKIPPED: Cannot find "julia" in PATH
haxelib: SKIPPED: Cannot find "haxelib" in PATH
sheldon: SKIPPED: Cannot find "sheldon" in PATH
rtcl: SKIPPED: Cannot find "rupdate" in PATH
bin: SKIPPED: Cannot find "bin" in PATH
gcloud: SKIPPED: Cannot find "gcloud" in PATH
micro: SKIPPED: Cannot find "micro" in PATH
raco: SKIPPED: Cannot find "raco" in PATH
spicetify: SKIPPED: Cannot find "spicetify" in PATH
GitHub CLI Extensions: SKIPPED: Cannot find "gh" in PATH
deb-get: SKIPPED: Cannot find "deb-get" in PATH
toolbx: SKIPPED: Cannot find "toolbox" in PATH
Flatpak: OK
snap: SKIPPED: Cannot find "snap" in PATH
pacstall: SKIPPED: Cannot find "pacstall" in PATH
pacdef: SKIPPED: Cannot find "pacdef" in PATH
protonup: SKIPPED: Cannot find "protonup" in PATH
distrobox: SKIPPED: Cannot find "distrobox" in PATH
pihole: SKIPPED: Cannot find "pihole" in PATH
Firmware upgrades: SKIPPED: Cannot find "fwupdmgr" in PATH
Restarts: SKIPPED: Cannot find "needrestart" in PATH
Vagrant boxes: SKIPPED: Cannot find "vagrant" in PATH
DEBUG Desktop notification: Topgrade finished successfully
DEBUG Executing command `/usr/bin/notify-send -a Topgrade Topgrade 'Topgrade finished successfully'`

</pre>
</details>

**Comment by DottoDev** [comment]
This is due to PcLinuxOS currently beeing not supported by the OS detection subsystem, which chooses which package manager to use for the system update.

**Comment by DottoDev** [comment]
AFAIK there isn't a manual option

**Comment by hunter2k01** [comment]
I'm not sure what command is used for APT-based distros that are supported by topgrade but PCLinuxOS [highly recommends `dist-upgrade` for package upgrades](https://pclinuxoshelp.com/index.php/Update_Your_PCLinuxOS#Updating_using_the_command_line). Just a future note.

**Comment by DottoDev** [comment]
@hunter2k01 apt dist-upgrade has some advantages but due to it installing and removing packages without user interactions it is not considered good to run all the time. Maybe we could do a config setting to enable it but I don't feel comfortable to enable it by default.
This article summarizes it good: [It's Foss What’s the difference between apt-get upgrade vs dist-upgrade?](https://itsfoss.com/apt-get-upgrade-vs-dist-upgrade/)

**Comment by DottoDev** [comment]
Should be fixed with #283 and also this uses `dist-upgrade` because of the recommendation. It still uses `upgrade` for all other apt distros

**Comment by hunter2k01** [comment]
> @hunter2k01 apt dist-upgrade has some advantages but due to it installing and removing packages without user interactions it is not considered good to run all the time. Maybe we could do a config setting to enable it but I don't feel comfortable to enable it by default. This article summarizes it good: [It's Foss What’s the difference between apt-get upgrade vs dist-upgrade?](https://itsfoss.com/apt-get-upgrade-vs-dist-upgrade/)

Texstar, the creator of PCLOS, [recommends dist-upgrade](https://www.pclinuxos.com/forum/index.php/topic,63199.msg511493.html#msg511493) because upgrade can result in broken packages (I have found this out the hard way). PCLOS is a rolling release that has snapshots every couple months.

This commit works.

**Comment by DottoDev** [comment]
Dist-upgrade is used for PCLINUXOS now but for every other apt distro I won't change it for now.
