### ISSUE TITLE
topgrade does not work after updating nala to 0.12

### ISSUE THREAD

**Issue by sbstn87** [topgrade-rs/topgrade#280]
As in the title. After updating nala to the latest version 0.12, topgrade does not work with it any more. Error message I get:

Traceback (most recent call last):
  File "/home/$USER/.local/bin/nala", line 5, in <module>
    from nala.cli import main
ModuleNotFoundError: No module named 'nala.cli

Nala by itself works fine.

**Comment by DottoDev** [comment]
This seems to be a problem with your Nala installation.

**Comment by sbstn87** [comment]
I have created a ticket in nala's issue tracker.

**Comment by DottoDev** [comment]
Closed as not planned as long as no new information comes up
