### ISSUE TITLE
Missing "dnf_arguments" example in config

### ISSUE THREAD

**Issue by Moitaeel** [topgrade-rs/topgrade#285]
Hello mate,

On this [commit](https://github.com/r-darwish/topgrade/commit/819447dcdf7abcc4d0d7b536d184b7a0351790ef) from 2020 two arguments were created, ``yay_argument`` and ``dnf_arguments`` so that you could pass specific commands to the programs, but on the config.example there's no mention of **dnf**, only **yay**, so I just found out I could also pass commands to dnf, like ``dnf_arguments = --refresh``.

I guess adding these lines on the config.example would help.

```
# Arguments to pass dnf when updating packages
#dnf_arguments = "--refresh"
```

**Comment by DottoDev** [comment]
Closed by #292
