### ISSUE TITLE
MacOS Macports rubygems not updated

### ISSUE THREAD

**Issue by mouse07410** [topgrade-rs/topgrade#286]
```
/opt/local/bin/gem update --system
```
fails on MacOS with Macports-installed Ruby.

## What did you expect to happen?
```
$ sudo /opt/local/bin/gem update --system
Enter PIN for 'Certificate For PIV Authentication (XXXXXX)': 
Updating rubygems-update
Fetching rubygems-update-3.4.1.gem
Successfully installed rubygems-update-3.4.1
Parsing documentation for rubygems-update-3.4.1
Installing ri documentation for rubygems-update-3.4.1
Done installing documentation for rubygems-update after 33 seconds
Parsing documentation for rubygems-update-3.4.1
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.4.1
  Successfully built RubyGem
  Name: bundler
  Version: 2.4.1
  File: bundler-2.4.1.gem
Bundler 2.4.1 installed
RubyGems 3.4.1 installed
Regenerating binstubs
.  .  .  .  .
------------------------------------------------------------------------------

RubyGems installed the following executables:
	/opt/local/bin/gem
	/opt/local/bin/bundle
	/opt/local/bin/bundler

Ruby Interactive (ri) documentation was installed. ri is kind of like man 
pages for Ruby libraries. You may access it like this:
.  .  .  .  .

RubyGems system software updated
```

## What actually happened?
```
 /opt/local/bin/gem update --system
Updating rubygems-update
Fetching rubygems-update-3.4.1.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/local/lib/ruby3.1/gems/3.1.0 directory.
	/opt/local/lib/ruby3.1/3.1.0/rubygems/installer.rb:712:in `verify_gem_home'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/installer.rb:902:in `pre_install_checks'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/installer.rb:302:in `install'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/resolver/specification.rb:104:in `install'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/request_set.rb:194:in `block in install'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/request_set.rb:182:in `each'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/request_set.rb:182:in `install'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/dependency_installer.rb:252:in `install'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/commands/update_command.rb:246:in `update_gem'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/commands/update_command.rb:282:in `update_rubygems'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/commands/update_command.rb:98:in `execute'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/command_manager.rb:185:in `process_args'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/command_manager.rb:149:in `run'
	/opt/local/lib/ruby3.1/3.1.0/rubygems/gem_runner.rb:51:in `run'
	/opt/local/bin/gem:21:in `<main>'
```

## Additional Details
- Which OS? _MacOS Monterey 12.6.2, MacPorts v2.8.0_
- How did you install Topgrade? _cargo install topgrade_
- Which version are you running? _Topgrade 10.2.4_

The problem appears to be that system-level Gems are installed in subdirectories of `/opt/local/lib/` that require privileged access. In other words, `/opt/local/bin/gem update --system` in this case must be executed with `sudo`. Otherwise, it fails with `FilePermissionError`.

On an unrelated topic, another problem:

On MacOS, `pre_sudo = true` has no effect, and if operations prior to TeX Live updates took longer time, the update pauses to prompt me for a password to invoke `sudo`. Instead of caching the password, or the state, or whatever it is supposed to do to preserve elevated privilege and avoid pausing in the mid-process and prompting the user.

**Comment by roock** [comment]
Same (or similar) similar is here. On my Mac it tries to write to `/Library/Ruby/Gems/2.6.0` directory.

## Additional Details
- Which operating system or Linux distribution are you using? MacOS 13.1
- How did you install Topgrade? homebrew
- Which version are you running? 10.2.4

<details>
<pre>
―― 14:48:31 - RubyGems ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Executing command `/usr/bin/gem update --system`
Ignoring bigdecimal-3.1.2 because its extensions are not built. Try: gem pristine bigdecimal --version 3.1.2
Ignoring date-3.2.2 because its extensions are not built. Try: gem pristine date --version 3.2.2
Ignoring dbm-1.1.0 because its extensions are not built. Try: gem pristine dbm --version 1.1.0
Ignoring etc-1.3.0 because its extensions are not built. Try: gem pristine etc --version 1.3.0
Ignoring fcntl-1.0.1 because its extensions are not built. Try: gem pristine fcntl --version 1.0.1
Ignoring io-console-0.5.11 because its extensions are not built. Try: gem pristine io-console --version 0.5.11
Ignoring json-2.6.1 because its extensions are not built. Try: gem pristine json --version 2.6.1
Ignoring libxml-ruby-3.2.2 because its extensions are not built. Try: gem pristine libxml-ruby --version 3.2.2
Updating rubygems-update
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/gem update --system`
   1: `/usr/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:93

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮
   3: <E as eyre::context::ext::StdError>::ext_report::ha909a204625de591
      at <unknown source file>:<unknown line>
   4: <std::process::Command as topgrade::command::CommandExt>::status_checked_with::hf8d2cd24e3979cfb
      at <unknown source file>:<unknown line>
   5: topgrade::runner::Runner::execute::h52d79f95aa13bd6d
      at <unknown source file>:<unknown line>
   6: topgrade::run::hb7eabe3dbf8bb1cd
      at <unknown source file>:<unknown line>
   7: topgrade::main::hc983cd830641c1ab
      at <unknown source file>:<unknown line>
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::h5eafc3e8f02db0a9
      at <unknown source file>:<unknown line>
   9: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.)
DEBUG Step "rubygems" failed:
   0: Command failed: `/usr/bin/gem update --system`
   1: `/usr/bin/gem` failed: exit status: 1

Location:
   src/steps/generic.rs:93
</pre>
</details>

**Comment by mouse07410** [comment]
I suggest adding a configuration parameter to `$HOME/.config/topgrade.toml`, something like
```
# Run gem --update --system under sudo (true) or not (false)?
gem_sudo = false
```
being `false` by default.

Also, `topgrade` checks the versions of executables installed in `$HOME/.cargo/bin` and updates those that have newer versions on `https://crates.io`. It would be nice if similar functionality is added to Cabal-built Haskell stuff that lives in `$HOME/.cabal/bin`.

**Comment by reini-1** [comment]
It would be nice to have the possibility to exclude system ruby and only update user local ruby gems ...

Updating Mac system ruby out of Mac updates maybe causes problems.

**Comment by reini-1** [comment]
Also adding "gem" to "disabled" in topgrade.toml seems to be ignored.

**Comment by DottoDev** [comment]
@mouse07410 please open up a new issue for this
> Also, `topgrade` checks the versions of executables installed in `$HOME/.cargo/bin` and updates those that have newer versions on `https://crates.io`. It would be nice if similar functionality is added to Cabal-built Haskell stuff that lives in `$HOME/.cabal/bin`.

**Comment by mouse07410** [comment]
> @mouse07410 Could you check out #317

Still not good.

```
── 23:36:04 - RubyGems ─────────────────────────────────────────────────────────
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Net::OpenTimeout: Failed to open TCP connection to rubygems.org:443 (https://rubygems.org/specs.4.8.gz) (Gem::RemoteFetcher::FetchError)
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/remote_fetcher.rb:261:in `rescue in fetch_path'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/remote_fetcher.rb:241:in `fetch_path'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/remote_fetcher.rb:285:in `cache_update_path'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/source.rb:187:in `load_specs'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/spec_fetcher.rb:256:in `tuples_for'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/spec_fetcher.rb:222:in `block in available_specs'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/source_list.rb:94:in `each'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/source_list.rb:94:in `each_source'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/spec_fetcher.rb:216:in `available_specs'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/spec_fetcher.rb:90:in `search_for_dependency'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/commands/update_command.rb:142:in `fetch_remote_gems'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/commands/update_command.rb:167:in `highest_remote_name_tuple'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/commands/update_command.rb:230:in `rubygems_target_version'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/commands/update_command.rb:275:in `update_rubygems'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/commands/update_command.rb:98:in `execute'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/command.rb:323:in `invoke_with_build_args'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/command_manager.rb:251:in `invoke_command'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/command_manager.rb:191:in `process_args'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/command_manager.rb:149:in `run'
	/opt/local/lib/ruby3.2/site_ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
	/opt/local/bin/gem:10:in `<main>'
rubygems failed: 
   0: Command failed: `/usr/bin/sudo /opt/local/bin/gem update --system`
   1: `/usr/bin/sudo` failed: exit status: 1

Location:
   src/steps/generic.rs:96

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 2 frames hidden ⋮                               
   3: <E as eyre::context::ext::StdError>::ext_report::hedacb05139840fae
      at <unknown source file>:<unknown line>
   4: topgrade::command::CommandExt::status_checked::h2072e716bf2d619b
      at <unknown source file>:<unknown line>
   5: topgrade::runner::Runner::execute::h9cf1097f33afce77
      at <unknown source file>:<unknown line>
   6: topgrade::run::h080e45f0210dc1e6
      at <unknown source file>:<unknown line>
   7: topgrade::main::h7ea1920038480384
      at <unknown source file>:<unknown line>
   8: std::sys_common::backtrace::__rust_begin_short_backtrace::h483910d125fb8718
      at <unknown source file>:<unknown line>
   9: std::rt::lang_start::{{closure}}::h35e3255ed30a66e9
      at <unknown source file>:<unknown line>
  10: std::rt::lang_start_internal::haf0419567751b65f
      at <unknown source file>:<unknown line>
  11: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
```

Invocation should include `sudo` flags `-EH`, at least for deployments that are behind corporate firewalls. So, not `sudo gem update --system`, but `sudo -EH gem update --system`.
