### ISSUE TITLE
The path of `topgrade.toml`

### ISSUE THREAD

**Issue by 5ouma** [topgrade-rs/topgrade#287]
## Change path to `~/.config/topgrade/topgrade.toml`
I think it's better the default config file path is this not `~/.config/topgrade.toml`.
A number of tools have a directory in `~/.config` and some config files are in there.
Also, it becomes a better appearance when seeing the directory.

**Comment by Locutus64** [comment]
After all this time and you want to suggest a folder for one file? Sorry but that's laughable.

**Comment by DottoDev** [comment]
I do not know what the advantage of this would be. I mean if someone wants to implement it with priorities on which path is preferred just open a PR, but I don't see it necessary.
