### ISSUE TITLE
`rustup` fails

### ISSUE THREAD

**Issue by Marin-Kitagawa** [topgrade-rs/topgrade#289]
## What did you expect to happen?
`rustup` command executed via `topgrade` must have succeeded

## What actually happened?
<details>
<summary>Following error occurred</summary>

―― 13:49:55 - rustup ―――――――――――――――――――――――――――――――――
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.66.0 (69f9c33d7 2022-12-12)

info: cleaning up downloads & tmp directories
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
   0: Command failed: `C:\Program Files\dotnet\dotnet.EXE -h`

      Stdout:
      Usage: dotnet [host-options] [path-to-application]

      path-to-application:
        The path to an application .dll file to execute.

      host-options:
        --additionalprobingpath <path>  Path containing probing policy and assemblies to probe for.
        --depsfile <path>               Path to <application>.deps.json file.
        --runtimeconfig <path>          Path to <application>.runtimeconfig.json file.
        --fx-version <version>          Version of the installed Shared Framework to use to run the application.
        --roll-forward <value>          Roll forward to framework version (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable)
        --additional-deps <path>        Path to additional deps.json file.
        --list-runtimes                 Display the installed runtimes
        --list-sdks                     Display the installed SDKs

      Common Options:
        -h|--help                       Displays this help.
        --info                          Display .NET information.
   1: C:\Program Files\dotnet\dotnet.EXE` failed: exit code: 0x80008081

</details>
<br/>
<details>
<summary> Full stacktrace <code>RUST_BACKTRACE=full</code></summary>
―― 14:26:00 - rustup ―――――――――――――――――――――――――――――――――――――――――――
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.66.0 (69f9c33d7 2022-12-12)

info: cleaning up downloads & tmp directories
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
   0: Command failed: `C:\Program Files\dotnet\dotnet.EXE -h`

      Stdout:
      Usage: dotnet [host-options] [path-to-application]

      path-to-application:
        The path to an application .dll file to execute.

      host-options:
        --additionalprobingpath <path>  Path containing probing policy and assemblies to probe for.
        --depsfile <path>               Path to <application>.deps.json file.
        --runtimeconfig <path>          Path to <application>.runtimeconfig.json file.
        --fx-version <version>          Version of the installed Shared Framework to use to run the application.
        --roll-forward <value>          Roll forward to framework version (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable)
        --additional-deps <path>        Path to additional deps.json file.
        --list-runtimes                 Display the installed runtimes
        --list-sdks                     Display the installed SDKs

      Common Options:
        -h|--help                       Displays this help.
        --info                          Display .NET information.
   1: `C:\Program Files\dotnet\dotnet.EXE` failed: exit code: 0x80008081

Location:
   C:\Users\quant\.cargo\registry\src\github.com-1ecc6299db9ec823\topgrade-10.2.4\src\steps\generic.rs:491

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: BaseThreadInitThunk<unknown>
      at <unknown source file>:<unknown line>
   2: RtlUserThreadStart<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Location: C:\Users\quant\.cargo\registry\src\github.com-1ecc6299db9ec823\topgrade-10.2.4\src\steps\generic.rs:491

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: BaseThreadInitThunk<unknown>
      at <unknown source file>:<unknown line>
   2: RtlUserThreadStart<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
</details>

## Additional Details
- Which operating system or Linux distribution are you using?
```
Edition	Windows 11 Pro
Version	22H2
OS build	22621.963
Experience	Windows Feature Experience Pack 1000.22638.1000.0
```
- How did you install Topgrade?
```
cargo install topgrade
```
- Which version are you running? 
```
Topgrade 10.2.4
```

<details>

<pre>
―― 14:02:24 - rustup ―――――――――――――――――――――――――――――――――――――――――――
Dry running: C:\Users\quant\.cargo\bin\rustup.EXE update
Dry running: C:\Program Files\dotnet\dotnet.EXE -h
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
   0: Dry running

Location:
   /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\convert\mod.rs:726
</pre>
</details>

**Comment by ngmisl** [comment]
yep, getting the same on Linux

**Comment by bbx0** [comment]
This seems to happen, when the `dotnet-runtime` is installed without the `dotnet-sdk`. `dotnet -h` returns with code `129` in this case and causes the call to `output_checked_utf8` to return with error.

```bash
$ dotnet --version 
7.0.101
```

<details><summary>No SDK installed</summary>
<p>

```bash
# No SDK installed
$ dotnet --help
Usage: dotnet [host-options] [path-to-application]

path-to-application:
  The path to an application .dll file to execute.

host-options:
  --additionalprobingpath <path>  Path containing probing policy and assemblies to probe for.
  --depsfile <path>               Path to <application>.deps.json file.
  --runtimeconfig <path>          Path to <application>.runtimeconfig.json file.
  --fx-version <version>          Version of the installed Shared Framework to use to run the application.
  --roll-forward <value>          Roll forward to framework version (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable)
  --additional-deps <path>        Path to additional deps.json file.
  --list-runtimes                 Display the installed runtimes
  --list-sdks                     Display the installed SDKs

Common Options:
  -h|--help                       Displays this help.
  --info                          Display .NET information.

$ echo $?
129
```

</p>
</details>

<details><summary>SDK installed</summary>
<p>

```bash
$ dotnet --help
Usage: dotnet [runtime-options] [path-to-application] [arguments]

Execute a .NET application.

runtime-options:
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.
  --additional-deps <path>         Path to additional deps.json file.
  --depsfile                       Path to <application>.deps.json file.
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --roll-forward <setting>         Roll forward to framework version  (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable).
  --runtimeconfig                  Path to <application>.runtimeconfig.json file.

path-to-application:
  The path to an application .dll file to execute.

Usage: dotnet [sdk-options] [command] [command-options] [arguments]

Execute a .NET SDK command.

sdk-options:
  -d|--diagnostics  Enable diagnostic output.
  -h|--help         Show command line help.
  --info            Display .NET information.
  --list-runtimes   Display the installed runtimes.
  --list-sdks       Display the installed SDKs.
  --version         Display .NET SDK version in use.

SDK commands:
  add               Add a package or reference to a .NET project.
  build             Build a .NET project.
  build-server      Interact with servers started by a build.
  clean             Clean build outputs of a .NET project.
  format            Apply style preferences to a project or solution.
  help              Show command line help.
  list              List project references of a .NET project.
  msbuild           Run Microsoft Build Engine (MSBuild) commands.
  new               Create a new .NET project or file.
  nuget             Provides additional NuGet commands.
  pack              Create a NuGet package.
  publish           Publish a .NET project for deployment.
  remove            Remove a package or reference from a .NET project.
  restore           Restore dependencies specified in a .NET project.
  run               Build and run a .NET project output.
  sdk               Manage .NET SDK installation.
  sln               Modify Visual Studio solution files.
  store             Store the specified assemblies in the runtime package store.
  test              Run unit tests using the test runner specified in a .NET project.
  tool              Install or manage tools that extend the .NET experience.
  vstest            Run Microsoft Test Engine (VSTest) commands.
  workload          Manage optional workloads.

Additional commands from bundled tools:
  dev-certs         Create and manage development certificates.
  fsi               Start F# Interactive / execute F# scripts.
  user-jwts         Manage JSON Web Tokens in development.
  user-secrets      Manage development user secrets.
  watch             Start a file watcher that runs a command when files change.

Run 'dotnet [command] --help' for more information on a command.
$ echo $?
0
```

</p>
</details>

**Comment by DottoDev** [comment]
`dotnet -h` is required to run because of the output it creates topgrade can guess if dotnet tools is installed or not. It seems like I have made an error in the implementation tho.

**Comment by bbx0** [comment]
Just checking for result of `dotnet tool list` should be fine, I guess. (Skip in case the command failed and skip in case of no packages.)

I can turn the following  into a merge request, if you like.

```rust
pub fn run_dotnet_upgrade(ctx: &ExecutionContext) -> Result<()> {
    let dotnet = utils::require("dotnet")?;

    if let Ok(output) = ctx
        .run_type()
        .execute(dotnet)
        .args(["tool", "list", "--global"])
        .output_checked_utf8()
    {
        if !output.stdout.starts_with("Package Id") {
            return Err(SkipStep(String::from("dotnet did not output packages")).into());
        }

        let mut packages = output.stdout.lines().skip(2).filter(|line| !line.is_empty()).peekable();

        if packages.peek().is_none() {
            return Err(SkipStep(String::from("No dotnet global tools installed")).into());
        }

        print_separator(".NET");

        for package in packages {
            let package_name = package.split_whitespace().next().unwrap();
            ctx.run_type()
                .execute("dotnet")
                .args(["tool", "update", package_name, "--global"])
                .status_checked()
                .with_context(|| format!("Failed to update .NET package {package_name}"))?;
        }
    } else {
        return Err(SkipStep(String::from("Failed to execute `dotnet tool list` subcommand.")).into());
    }

    Ok(())
}
```

**Comment by DottoDev** [comment]
This approach is way better then mine. PR would be great

**Comment by CryoRenegade** [comment]
Still broken on latest commit
```
topgrade on  master is 📦 v10.2.4 via 🦀 v1.66.0
❯ .\target\release\topgrade.exe

―― 14:33:17 - Scoop ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Updating Scoop...
Updating 'extras' bucket...
Updating 'games' bucket...
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'nerd-fonts' bucket...
Updating 'nonportable' bucket...
Scoop was updated successfully!
Latest versions for all apps are installed! For more information try 'scoop status'
Everything is shiny now!

―― 14:33:24 - winget ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Winget is disabled by default. Enable it by setting enable_winget=true in the [windows] section in the configuration.

―― 14:33:24 - Powershell Modules Update ――――――――――――――――――――――――――――――――――――――――
Updating modules...

―― 14:33:26 - rustup ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.66.0 (69f9c33d7 2022-12-12)

info: cleaning up downloads & tmp directories
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
   0: Command failed: `C:\Program Files\dotnet\dotnet.EXE -h`

      Stdout:
      Usage: dotnet [host-options] [path-to-application]

      path-to-application:
        The path to an application .dll file to execute.

      host-options:
        --additionalprobingpath <path>  Path containing probing policy and assemblies to probe for.
        --depsfile <path>               Path to <application>.deps.json file.
        --runtimeconfig <path>          Path to <application>.runtimeconfig.json file.
        --fx-version <version>          Version of the installed Shared Framework to use to run the application.
        --roll-forward <value>          Roll forward to framework version (LatestPatch, Minor, LatestMinor, Major, LatestMajor, Disable)
        --additional-deps <path>        Path to additional deps.json file.
        --list-runtimes                 Display the installed runtimes
        --list-sdks                     Display the installed SDKs

      Common Options:
        -h|--help                       Displays this help.
        --info                          Display .NET information.
   1: `C:\Program Files\dotnet\dotnet.EXE` failed: exit code: 0x80008081

Location:
   src\steps\generic.rs:491

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Location: src\steps\generic.rs:491

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
