### ISSUE TITLE
Self update error: ReleaseError: No asset found for target: `x86_64-pc-windows-msvc`

### ISSUE THREAD

**Issue by reini-1** [topgrade-rs/topgrade#294]
## What did you expect to happen?
topgrade gets updated on windows to the latest version

## What actually happened?
topgrade is not updated and the following error is shown.
Self update error: ReleaseError: No asset found for target: `x86_64-pc-windows-msvc`

## Additional Details
- Which operating system or Linux distribution are you using? Windows 11
- How did you install Topgrade? Copy file from Github repo
- Which version are you running? Topgrade 10.2.2

<details>

<pre>

</pre>
</details>

**Comment by reini-1** [comment]
Seems windows build fails for a while ...

https://github.com/topgrade-rs/topgrade/actions/runs/3725509667/jobs/6318356110

**Comment by katsuki-yuri** [comment]
since December mine haven't upgraded

**Comment by luciodaou** [comment]
Shouldn't this be closed since Windows package is already being normally rebuild after PR https://github.com/topgrade-rs/topgrade/pull/303 ?

**Comment by DottoDev** [comment]
Yes, is Closed by #303
