### ISSUE TITLE
Problem updating node under nvm: `ERR_PNPM_NO_PKG_MANIFEST`

### ISSUE THREAD

**Issue by joshualex** [topgrade-rs/topgrade#297]
I installed nvm and under it node v16. Running on macOS Ventura 13.1.

When I run topgrade it fails like so:
```
―― 08:23:26 - Node Package Manager ―――――――――――――――――――――――――――――――――――――――――――――
 ERR_PNPM_NO_PKG_MANIFEST  No package.json found in /Users/josh/Library/pnpm/global/5
pnpm failed:
   0: Command failed: `/Users/josh/.nvm/versions/node/v16.19.0/bin/pnpm update -g`
   1: `/Users/josh/.nvm/versions/node/v16.19.0/bin/pnpm` failed: exit status: 1

Location:
   src/steps/node.rs:101
```

It reproduces when I completely wipe `~/.nvm` and reinstall it...

This happens with topgrade 10.2.4

**Comment by DottoDev** [comment]
Could you checkout #182 and see if something helps you.

**Comment by joshualex** [comment]
@DottoDev indeed the instructions on #182 helped me and now everything works. Thanks!
