### ISSUE TITLE
Snapshots via topgrade

### ISSUE THREAD

**Issue by musicfunfan** [topgrade-rs/topgrade#300]
## I want to suggest some general feature

Hello there, topgrade works fine for me. Any time i upgrade my system how ever i like to take snapshot of the previews working state of the system. As we all know some updates may brake the system or something useful in the system. Is nice to have a snapshot to just re roll an update. Topgrade can update all the system witch is nice i would like from topgrade also to have a snapshot system integration. Topgrade can use something like timeshift for that. My Idea is to have a flag to create a snapshot before the update. 

For example if i run something like  ``topgrade -cs`` s=snapshot
Topgrade will run ``timeshift --create``. And then will do all the topgrade magic with all the package managing systems. 

I think this is a very cool idea for topgrade 😃.

**Comment by DottoDev** [comment]
For simplicity you can just add time shift under `pre_commands` in the config file.

**Comment by musicfunfan** [comment]
Ok i will do that. I guess this issue can close now. But i still thing that topgrade should have a way to roll back the updates. Like some other front ends to package managers. For example nala does this. 

Anyway thenx for the replay take care.
