### ISSUE TITLE
Pip modules update

### ISSUE THREAD

**Issue by luciodaou** [topgrade-rs/topgrade#304]
## I want to suggest a new step
Topgrade currently updates pip itself. My suggestion is to add an optional feature to update installed modules, through `pip-review`.
### Which tool is this about? Where is its repository?
pip-review https://github.com/jgonggrijp/pip-review

### Which operating systems are supported by this tool?
All where python/pip works - both tools are pip modules

### What should Topgrade do to figure out if the tool needs to be invoked?
Same as pip.
`pipupgrade` should be explicited declared on command-line or `topgrade.toml`
**Maybe** add a message just like `winget` is "disabled by default" when running on Windows.

### Which exact commands should Topgrade run?

`pip-review -a -C`

```
  --auto, -a            Automatically install every update found
  --continue-on-fail, -C
                        Continue with other installs when one fails

```

**Comment by luciodaou** [comment]
There's also another tool for pip modules upgrade, named `pipupgrade` https://github.com/achillesrasquinha/pipupgrade .

It's way more powerful but more complex too. I believe `pip-review` is more straightforward and easier to implement considering the objective of updating all modules.

**Comment by DottoDev** [comment]
@luciodaou Could you please try out #316 and also check if the options in the config file work

**Comment by luciodaou** [comment]
Just did it, but it's not working: https://github.com/topgrade-rs/topgrade/pull/316#pullrequestreview-1252671696
