### ISSUE TITLE
Support for apx

### ISSUE THREAD

**Issue by Zahrun** [topgrade-rs/topgrade#306]
### Which tool is this about? Where is its repository?
https://github.com/Vanilla-OS/apx
### Which operating systems are supported by this tool?
Linux
### What should Topgrade do to figure out if the tool needs to be invoked?
apx command exists
### Which exact commands should Topgrade run?
apx update
apx upgrade

**Comment by jim3692** [comment]
It's more complicated than that. You also need to specify which distro you want to update (ex `apx --dnf update ; apx --dnf upgrade`), or which named container you want to update (ex `apx --dnf --name fedora_1 update ; apx --dnf --name fedora_1 upgrade`)

**Comment by Zahrun** [comment]
Actually the distrobox step might already do the work if it functions well

**Comment by jim3692** [comment]
Which distrobox step? Is there already a better way to do that?

**Comment by Zahrun** [comment]
See https://github.com/topgrade-rs/topgrade/blob/master/src/steps/os/linux.rs#L638
It runs `/usr/bin/distrobox upgrade --all`
Will this upgrade apx installed packages automatically?

**Comment by jim3692** [comment]
I was not aware of that. Thank you for pointing it. However I spotted a small issue that should be solved on distobox's side. It looks like they do not support yay, which is used for AUR packages.

https://github.com/89luca89/distrobox/blob/0e24aae53ae6e2fd6901db3556de9e6b261e7a6f/distrobox-init#L458

**Comment by DottoDev** [comment]
Can I close this issue? @jim3692

**Comment by jim3692** [comment]
@DottoDev we can probably close it for now, and we will open it again when the work in apx side is complete, or I will try to make a PR for apx support

**Comment by DottoDev** [comment]
👍
