### ISSUE TITLE
Fedora Silverblue not properly detected

### ISSUE THREAD

**Issue by PieroSimonet** [topgrade-rs/topgrade#308]
Fedora silverblue uses rpm-ostee command to update itself with the command "rpm-ostree update" but the program tries to use "sudo yum upgrade" which is the old way to update the normal fedora linux. The old unmaintained code by r-darwish works fine, so I gave a quick look if there were some changes in linux.rs but I did not find any relevant difference.

**Comment by DottoDev** [comment]
Could you share the os-release file?

**Comment by DottoDev** [comment]
@PieroSimonet Could you please try out #313 313

**Comment by PieroSimonet** [comment]
Ok I tested it, but it does not entirely solve the issue, but I found the problem: The configuration file set the variable rpm-ostree = false as default, so it does not activate the command. Also in /src/config.rs (https://github.com/topgrade-rs/topgrade/blob/cba9dc1c2ce8b37e0dca5e3288f753b1fb6483e4/src/config.rs#L934) in line 934 the default value is settled to false (but in the comment before the function is explicitly reported that is should be true. Changing one of these two setting lead to a working code but I cannot say which one is the best. 

I have a comment on the piece of code that your commit propose to modify, but since I am not a rust developer it can be a wrong one. 
`fn upgrade_redhat(ctx: &ExecutionContext) -> Result<()> {
    if let Some(ostree) = which("rpm-ostree") {
        if ctx.config().rpm_ostree() {
            let mut command = ctx.run_type().execute(ostree);
            command.arg("upgrade");
            command.status_checked()?; /////// <- here it is not better to use this instead of the return? because if not the OK() function will not be called (I did not check what it does)
        }
   } else {
        if let Some(sudo) = &ctx.sudo() {
            let mut command = ctx.run_type().execute(sudo);
            command
                .arg(which("dnf").unwrap_or_else(|| Path::new("yum").to_path_buf()))
                .arg(if ctx.config().redhat_distro_sync() {
                    "distro-sync"
                } else {
                    "upgrade"
                });

            if let Some(args) = ctx.config().dnf_arguments() {
                command.args(args.split_whitespace());
            }

            if ctx.config().yes(Step::System) {
                command.arg("-y");
            }

            command.status_checked()?;
        } else {
            print_warning("No sudo detected. Skipping system upgrade");
        }
    }

    Ok(())
}`

**Comment by DottoDev** [comment]
I'll look into that, thx
