### ISSUE TITLE
The detection for nala should probably be switched to path instead of which("nala").

### ISSUE THREAD

**Issue by RayJW** [topgrade-rs/topgrade#309]
As discussed in this [issue](https://gitlab.com/volian/nala/-/issues/209) on the nala repo the detection should probably directly look for the nala binary path instead of searching for commands with ```which("nala")``` as this means that other packages with the name nala like the pip one could take priority over the actual tool one would want to call with Topgrade.

**Comment by DottoDev** [comment]
The problem we have in this situation is that it can't be assumed that Nala is located in /usr/bin/Nala, even if it normaly is. but due to it Beeing an apt package manager I think it would be possible to just assume it.

**Comment by DottoDev** [comment]
Could you please test #314

**Comment by RayJW** [comment]
@DottoDev I'm sorry, I was away for some time, but it seems like you already released the fix and I can confirm, it is still working on all my systems so far :)

**Comment by DottoDev** [comment]
Good to hear that everything works
