### ISSUE TITLE
Support for openSUSE MicroOS 

### ISSUE THREAD

**Issue by szaun** [topgrade-rs/topgrade#311]
openSUSE MicroOS [1] is currently detected as openSUSE Tumbleweed. A different command is needed in order to refresh repositories and update the system on MicroOS.

_Current command:_
sudo zypper refresh
sudo zypper dist-upgrade

_Required command:_ [2]
sudo transactional-update dup

Any chance this could be added? Many thanks for your work on topgrade, it's a fantastic tool!

```
$ cat /etc/os-release
NAME="openSUSE MicroOS"
# VERSION="20230107"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20230107"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20230107"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo-MicroOS"

```
[1] https://microos.opensuse.org/
[2] https://en.opensuse.org/Portal:MicroOS/Desktop#transactional-update_-_Example_commands

**Comment by DottoDev** [comment]
Could you check out #315
