### ISSUE TITLE
Support running `wsl --update` (optionally with `--pre-release` flag)

### ISSUE THREAD

**Issue by pavelxdd** [topgrade-rs/topgrade#321]
Hello. I want to suggest a new step.

Currently wsl step only supports calling topgrade inside wsl distributions.
I want to support calling `wsl --update` (and optionally `wsl --update --pre-release`) to check updates of the WSL subsystem.

And optionally add a config switch to disable running wsl distributions topgrade, because personally I'm interested in `wsl --update` only.

**Comment by luciodaou** [comment]
Isn't WSL updated through Windows Store? 

> And optionally add a config switch to disable running wsl distributions topgrade, because personally I'm interested in `wsl --update` only.

Already available. Add `"wsl"` inside the disable array. This is how it's on my Windows topgrade config file:
```
disable = ["system", "winget","wsl"]
```

This way I can run topgrade independently on my WSL distros as needed.

**Comment by DottoDev** [comment]
Closed because already a feature.

**Comment by pavelxdd** [comment]
| Closed because already a feature.

Am I missing something? Currently topgrade can only upgrade WSL distributions, not the WSL subsystem itself.

**Comment by DottoDev** [comment]
But shouldn't the subsystem be already updatet using A the store or B winget?

**Comment by pavelxdd** [comment]
You can't update pre-release WSL via store or winget for example.

**Comment by DottoDev** [comment]
Will look into that

**Comment by DottoDev** [comment]
@pavelxdd Could you try the PR out?

**Comment by pavelxdd** [comment]
Seems to work, thanks!
