### ISSUE TITLE
Add Maza support

### ISSUE THREAD

**Issue by sbstn87** [topgrade-rs/topgrade#332]
Hi,

will it be possible to add support for Maza Ad Blocker?

Link: https://github.com/tanrax/maza-ad-blocking

Description:
Like Pi-hole but local and using your operating system. Simple, native and efficient local ad blocker. Bash script compatible with MacOS, Linux, BSD and Windows Subsystem for Linux (WSL).

Updating is done by simply typing: maza update

**Comment by DottoDev** [comment]
Will be implemented
