### ISSUE TITLE
Fails if "am" is not present

### ISSUE THREAD

**Issue by yochananmarqos** [topgrade-rs/topgrade#334]
## What did you expect to happen?
Skip the am step if `/usr/bin/am` is not found.

## What actually happened?
It failed because `am` was not found. 

Temporary workaround:

```
disable = ["a_m"]
```

## Additional Details
- Which operating system or Linux distribution are you using?
Manjaro GNOME
- How did you install Topgrade?
Built via Manjaro PKGBUILD
- Which version are you running? 
10.2.6, however `topgrade -V` reports 10.2.5

<details>

<pre>
DEBUG Step "am"
DEBUG Executing command `/usr/bin/sudo am -u`
sudo: am: command not found
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/sudo am -u`
   1: `/usr/bin/sudo` failed: exit status: 1

Location:
   src/steps/os/linux.rs:440

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "am" failed: 
   0: Command failed: `/usr/bin/sudo am -u`
   1: `/usr/bin/sudo` failed: exit status: 1

Location:
   src/steps/os/linux.rs:440

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
am failed: 
   0: Command failed: `/usr/bin/sudo am -u`
   1: `/usr/bin/sudo` failed: exit status: 1

Location:
   src/steps/os/linux.rs:440

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit

</pre>
</details>

**Comment by opentux** [comment]
Hi,
Exatly same problem for me on arch linux

**Comment by yochananmarqos** [comment]
@opentux See https://github.com/topgrade-rs/topgrade/issues/206

**Comment by opentux** [comment]
Ok thanks :)

**Comment by DottoDev** [comment]
Known bug, fix is on the way, till fixed please disable am

**Comment by DottoDev** [comment]
Should be fixed with the latest version, sorry for the inconvenience

**Comment by yochananmarqos** [comment]
@DottoDev Yes, it is. Thank you!

**Comment by ivan-hc** [comment]
https://github.com/topgrade-rs/topgrade/pull/328#issuecomment-1493498789
