### ISSUE TITLE
disable_preamble does not actually disable the preamble

### ISSUE THREAD

**Issue by yochananmarqos** [topgrade-rs/topgrade#337]
## What did you expect to happen?
Setting `display_preamble = false` should have disabled the preamble. It's registered and shows `display_preamble: Some(false),` during verbose output.

## What actually happened?
The preamble is still displayed.

## Additional Details
- Which operating system or Linux distribution are you using?
Manjaro GNOME
- How did you install Topgrade?
Built via Manjaro PKGBUILD
- Which version are you running? 
10.3.0

<details>

<pre>
DEBUG Configuration at /home/yochanan/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { pre_sudo: None, pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: Some([Cargo, Node, Pip3, Rustup]), ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, display_preamble: Some(false), assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, python: Some(Python { enable_pip_review: None, enable_pipupgrade: None }), no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: Some(Paru), show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None, wsl_update_pre_release: None, wsl_update_use_web_download: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: Some(true) }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }) }
DEBUG Detected "/usr/bin/notify-send" as "notify-send"
DEBUG Version: 10.3.0
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/usr/bin/topgrade")
DEBUG Self Update: false
Due to a design issue with notify-send it could be that topgrade hangs when it's finished.
If this is the case on your system add the --skip-notify flag to the topgrade command or set skip_notify = true in the config file.
If you don't want this message to appear any longer set display_preamble = false in the config file.
For more information about this issue see https://askubuntu.com/questions/110969/notify-send-ignores-timeout and https://github.com/topgrade-rs/topgrade/issues/288.

</pre>
</details>

**Comment by pro-sumer** [comment]
Also broken on macOS (Monterey 12.6.3).

**Comment by arctic-penguin** [comment]
The bug is here: https://github.com/topgrade-rs/topgrade/pull/324/commits/f1e4009d355407481aea628ea7f08bece143320b and was introduced by #324. Both conditions must be linked using `&&` instead of `||`.
