### ISSUE TITLE
Gets stuck on Neovim upgrade every time

### ISSUE THREAD

**Issue by MonstrousOgre** [topgrade-rs/topgrade#339]
This started happening after I upgraded to 10.3.0. I was previously on 10.2.4

It's working fine when I use `disable = ["vim"]`

## What did you expect to happen?
Neovim plugins upgrade and topgrade continues like usual

## What actually happened?
Neovim step shows no output and nothing seems to be happening. It seems stuck, which also prevents the following topgrade steps from running

## Additional Details
- Which operating system or Linux distribution are you using? Arch Linux
- How did you install Topgrade? Using cargo
- Which version are you running? 10.3.0

<details>

This is what I get when I run the command myself
<pre>
$ nvim -u /home/ogre/.config/nvim/init.lua --headless -V1 -nS /tmp/.tmpns3oaM
Error detected while processing command line:
E484: Can't open file /tmp/.tmpns3oaM
</pre>
</details>

**Comment by vzze** [comment]
On Windows 11 topgrade (ver 10.3.0) doesn't hang on the Neovim upgrade step.

![image](https://user-images.githubusercontent.com/74437706/215474518-a1ad7d2b-8572-4a86-a570-00551775b96e.png)
I took the liberty to check your dotfiles repository, try to comment out `run=":TSUpdate"` from your Treesitter config and rerun topgrade (topgrade already takes care of updating TS after the plugin update).

Also from my personal experience (at least on Windows 11) Treesitter is really slow when updating depending on the amount of parsers installed.

**Comment by MonstrousOgre** [comment]
Same issue after commenting. Treesitter also shows there are no updates when trying to update from Neovim itself, so it doesn't seem like that's it

**Comment by vzze** [comment]
Hmm.. Can you copy the `src/steps/upgrade.vim` file from the repository and then open up Neovim and run it with the command `:source path/to/upgrade.vim`; if it runs correctly it should boot you out of Neovim once its done.

**Comment by MonstrousOgre** [comment]
I'll do this when I can

**Comment by MonstrousOgre** [comment]
It's working with the latest update. Thanks!
