### ISSUE TITLE
nix: "incompatible with 'nix-env'; please use 'nix profile' instead"

### ISSUE THREAD

**Issue by tennox** [topgrade-rs/topgrade#34]
Using `nix profile` will [obsolete/break `nix-env`](https://nixos.wiki/wiki/Nix_command/profile)

## What did you expect to happen?
Nix upgrade uses `nix profile` when the profile contains `manifest.json` (like [nix-env does the check](https://github.com/NixOS/nix/blob/master/src/nix-env/user-env.cc#L20)):
`/nix/var/nix/profiles/per-user/manu/profile/manifest.json`

The command that is applicable then is:
```
nix profile upgrade '.*'
```

## What actually happened?
```
―― 15:28:57 - Nix ―――――――――
this derivation will be built:
  /nix/store/bc8p7vjvhpfrgv3h12h767yv4kbw1prm-home-manager.drv
building '/nix/store/bc8p7vjvhpfrgv3h12h767yv4kbw1prm-home-manager.drv'...
unpacking channels...
error: profile '/nix/var/nix/profiles/per-user/manu/profile' is incompatible with 'nix-env'; please use 'nix profile' instead
```

## Additional Details
- OS: Fedora beta 37
- How did you install Topgrade? `cargo install topgrade-rs`
- Which version are you running? `Topgrade 9.1.0`

<pre>
Dry running: /nix/var/nix/profiles/default/bin/nix-channel --update
Dry running: /nix/var/nix/profiles/default/bin/nix-env --upgrade
</pre>

**Comment by DottoDev** [comment]
So if I understand that right instead of `nix-env --upgrade` `nix profile upgrade '.*'` should run.

**Comment by DottoDev** [comment]
Could you try out this branch? https://github.com/DottoDev/topgrade-dev/tree/nix-error

**Comment by tennox** [comment]
Well you'd need to change it to
```rust

**Comment by tennox** [comment]
I sent a PR as far as I got, works well with manifest.json and without.
But I'm using a deprecated method and I'm not far enough into rust yet to know what is best instead - just get $HOME (as nix is linux/mac only)?
Or actually use a crate like the deprecation suggests?
