### ISSUE TITLE
Windows 11 UsoClient failed

### ISSUE THREAD

**Issue by vzze** [topgrade-rs/topgrade#345]
## What did you expect to happen?
Windows Update step to successfully exit.

## What actually happened?
UsoClient fails with exit code `0x80070057`.

Snippet from Microsoft support regarding "exit code `0x80070057`":
`there were some problems installing updates, and the system will attempt to try again later`

This issue is caused by Windows itself and not topgrade, a solution would be for topgrade to ignore exit code `0x80070057`.

![image](https://user-images.githubusercontent.com/74437706/215749744-cbe41504-2103-47c0-ab88-2ccd8f8425fe.png)

## Additional Details
OS: Windows 11
Installation: Installed topgrade through scoop.
Version: 10.3.1

EDIT: Wanted to add the fact that when running the command standalone there is no output.
![image](https://user-images.githubusercontent.com/74437706/215752600-348990eb-6d57-439c-8c87-eda9d33a6716.png)

**Comment by DottoDev** [comment]
Imo this is expected behavior because the update wasn't successful.

**Comment by vzze** [comment]
It's still weird that when I run the command there is no faulty return code, but when topgrade runs it it returns that `0x80070057` exit code.

For completions sake I want to mention that while I was on Windows 10 the update step seemed to work fine.

**Comment by DottoDev** [comment]
Could be that windows interprets some error codes different or simply doesn't show them.

**Comment by vzze** [comment]
From my experience Windows is consistent with its return codes, they probably dropped support for UsoClient on Windows 11, the most I could find about USO was [its api](https://learn.microsoft.com/en-us/windows/win32/updateorchestrator/), [docs for server admins](https://learn.microsoft.com/en-us/windows/deployment/update/windows-update-overview) and this [reddit thread](https://www.reddit.com/r/sysadmin/comments/ecrgm/usoclientexe_startinteractivescan_seemingly_does/). 

Since topgrade does report correctly that the update fails I'll close the issue.
