### ISSUE TITLE
Not able to run topgrade

### ISSUE THREAD

**Issue by Marin-Kitagawa** [topgrade-rs/topgrade#357]
## What did you expect to happen?
Topgrade must work. I also tried with `--skip-notify` flag; same error.

## What actually happened?
I got the following error
![image](https://user-images.githubusercontent.com/49131888/217279821-d3808d79-6044-412a-b6dd-d22e83a38fb0.png)

## Additional Details
- Which operating system or Linux distribution are you using? Windows 11
- How did you install Topgrade? `cargo install topgrade`
- Which version are you running?  Topgrade 10.3.1

<details>

<pre>

</pre>
</details>

**Comment by DottoDev** [comment]
Will be fixed in 10.3.2

**Comment by DottoDev** [comment]
Sorry for the delay, could you try out #362
