### ISSUE TITLE
Antidote step not executed?

### ISSUE THREAD

**Issue by pro-sumer** [topgrade-rs/topgrade#373]
I have migrated from the deprecated [antibody](https://github.com/getantibody/antibody) to [antidote](https://github.com/mattmc3/antidote). I see `antidote` references in the Topgrade source code, so I expected this to be seamless migration.

## What did you expect to happen?

Output of `antidote` (similar to output of `antibody`)

## What actually happened?

No output of `antidote` (not even with `-v` parameter; see details)

## Additional Details
- macOS Ventura 13.2.1
- `brew install topgrade`
- Topgrade 10.3.1

<details>
<pre>
...
antibody: SKIPPED: Cannot find "antibody" in PATH
antigen: SKIPPED: Path "/Users/rob/antigen.zsh" doesn't exist<pre>
</pre>
</details>

**Comment by capito27** [comment]
Antidote support was merged last week (https://github.com/topgrade-rs/topgrade/pull/368), and is not part of any release yet.
You must either wait for the next release, or build from source / cargo install the git repo

**Comment by DottoDev** [comment]
Will be released this weekend.

**Comment by pro-sumer** [comment]
Got it in Topgrade 10.3.2 this morning.

Thanks!
