### ISSUE TITLE
System Upgrade failing with an error

### ISSUE THREAD

**Issue by yoshimo** [topgrade-rs/topgrade#377]
## What did you expect to happen?
topgrade updating everything automatically

## What actually happened?

It stopped asking me for a retry or quit

## Additional Details
- Which operating system or Linux distribution are you using?  Kubuntu 22.10
- How did you install Topgrade?  Cargo Install
- Which version are you running? 10.2.4

<details>

<pre>
topgrade -v
DEBUG Configuration at /home/user/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { pre_sudo: None, pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: Some(true) }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: None }
DEBUG Cannot find "notify-send"
DEBUG Version: 10.2.4
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/home/user/.cargo/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Step "System update"

―― 11:50:16 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
DEBUG Cannot find "apt-fast"
DEBUG Cannot find "nala"
DEBUG Executing command `/usr/bin/sudo apt-get update`
OK:1 http://de.archive.ubuntu.com/ubuntu kinetic InRelease
Ign:2 http://ppa.launchpad.net/cybermax-dexter/vkd3d/ubuntu kinetic InRelease                                                                                                                                                  
OK:3 http://de.archive.ubuntu.com/ubuntu kinetic-updates InRelease                                                                                                                                                             
OK:4 https://ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu kinetic InRelease                                                                              
OK:5 https://dl.winehq.org/wine-builds/ubuntu kinetic InRelease                                                                                                    
Holen:6 http://de.archive.ubuntu.com/ubuntu kinetic-backports InRelease [99,9 kB]                                                                                        
Ign:7 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu kinetic InRelease                                                                                           
OK:8 http://security.ubuntu.com/ubuntu kinetic-security InRelease                                                                                                                 
OK:9 http://ppa.launchpad.net/mozillateam/firefox-next/ubuntu kinetic InRelease                                                                                                   
OK:10 https://ppa.launchpadcontent.net/openrazer/stable/ubuntu kinetic InRelease                                          
OK:11 http://ppa.launchpad.net/mozillateam/ppa/ubuntu kinetic InRelease                  
OK:12 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu kinetic InRelease                                           
OK:13 https://ppa.launchpadcontent.net/polychromatic/stable/ubuntu kinetic InRelease                                    
OK:14 http://ppa.launchpad.net/openrazer/stable/ubuntu kinetic InRelease                                                
OK:15 http://ppa.launchpad.net/polychromatic/stable/ubuntu kinetic InRelease
Ign:16 http://ppa.launchpad.net/wireshark-dev/nightly/ubuntu jammy InRelease
Fehl:17 http://ppa.launchpad.net/cybermax-dexter/vkd3d/ubuntu kinetic Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Fehl:18 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu kinetic Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Holen:19 http://de.archive.ubuntu.com/ubuntu kinetic-backports/universe amd64 DEP-11 Metadata [10,9 kB]
Fehl:20 http://ppa.launchpad.net/wireshark-dev/nightly/ubuntu jammy Release
  404  Not Found [IP: 2620:2d:4000:1::3e 80]
Fehl:14 http://ppa.launchpad.net/openrazer/stable/ubuntu kinetic InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 073E051D7B2AEE37
Fehl:15 http://ppa.launchpad.net/polychromatic/stable/ubuntu kinetic InRelease
  Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 96B9CD7C22E2C8C5
Paketlisten werden gelesen… Fertig
W: Ziel Packages (main/binary-amd64/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Packages (main/binary-i386/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Packages (main/binary-all/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Translations (main/i18n/Translation-de_DE) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Translations (main/i18n/Translation-de) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Translations (main/i18n/Translation-en) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11 (main/dep11/Components-amd64.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11 (main/dep11/Components-all.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons-small (main/dep11/icons-48x48.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons (main/dep11/icons-64x64.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons-large (main/dep11/icons-128x128.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel CNF (main/cnf/Commands-amd64) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel CNF (main/cnf/Commands-all) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
E: Das Depot »http://ppa.launchpad.net/cybermax-dexter/vkd3d/ubuntu kinetic Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
E: Das Depot »http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu kinetic Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
E: Das Depot »http://ppa.launchpad.net/wireshark-dev/nightly/ubuntu jammy Release« enthält keine Release-Datei.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://ppa.launchpad.net/openrazer/stable/ubuntu kinetic InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 073E051D7B2AEE37
W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://ppa.launchpad.net/polychromatic/stable/ubuntu kinetic InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 96B9CD7C22E2C8C5
W: Ziel Packages (main/binary-amd64/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Packages (main/binary-i386/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Packages (main/binary-all/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Translations (main/i18n/Translation-de_DE) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Translations (main/i18n/Translation-de) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel Translations (main/i18n/Translation-en) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11 (main/dep11/Components-amd64.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11 (main/dep11/Components-all.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons-small (main/dep11/icons-48x48.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons (main/dep11/icons-64x64.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel DEP-11-icons-large (main/dep11/icons-128x128.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel CNF (main/cnf/Commands-amd64) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
W: Ziel CNF (main/cnf/Commands-all) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/sudo apt-get update`
   1: `/usr/bin/sudo` failed: exit status: 100

Location:
   /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-10.2.4/src/steps/os/linux.rs:325

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "System update" failed: 
   0: Command failed: `/usr/bin/sudo apt-get update`
   1: `/usr/bin/sudo` failed: exit status: 100

Location:
   /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-10.2.4/src/steps/os/linux.rs:325

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
System update failed: 
   0: Command failed: `/usr/bin/sudo apt-get update`
   1: `/usr/bin/sudo` failed: exit status: 100

Location:
   /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-10.2.4/src/steps/os/linux.rs:325

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.DEBUG Desktop notification: System update failed

Retry? (y)es/(N)o/(s)hell/(q)uituser@Computer:~/Downloads/Repos/medusa$ 

</pre>
</details>

**Comment by DottoDev** [comment]
What happens if you just run `sudo apt-get update`

**Comment by yoshimo** [comment]
> sudo apt-get update
> Ign:1 http://ppa.launchpad.net/cybermax-dexter/vkd3d/ubuntu kinetic InRelease
> OK:2 http://de.archive.ubuntu.com/ubuntu kinetic InRelease                                                                                                                                       
> OK:3 https://dl.winehq.org/wine-builds/ubuntu kinetic InRelease                                                                                                                                  
> Ign:4 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu kinetic InRelease                                                                                          
> Holen:5 http://de.archive.ubuntu.com/ubuntu kinetic-updates InRelease [118 kB]                                                          
> Holen:6 http://security.ubuntu.com/ubuntu kinetic-security InRelease [109 kB]                                                                                                   
> OK:7 http://ppa.launchpad.net/mozillateam/firefox-next/ubuntu kinetic InRelease                                                                                                 
> Holen:8 https://ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu kinetic InRelease [23,9 kB]                 
> OK:9 http://ppa.launchpad.net/mozillateam/ppa/ubuntu kinetic InRelease                                                                                   
> Holen:10 http://de.archive.ubuntu.com/ubuntu kinetic-backports InRelease [99,9 kB]                                                                                               
> Holen:11 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu kinetic InRelease [23,9 kB]                                                                                                
> OK:12 https://ppa.launchpadcontent.net/openrazer/stable/ubuntu kinetic InRelease                                                                         
> OK:13 http://ppa.launchpad.net/openrazer/stable/ubuntu kinetic InRelease                                           
> Holen:14 http://de.archive.ubuntu.com/ubuntu kinetic-updates/main Sources [125 kB]                                                                       
> OK:15 https://ppa.launchpadcontent.net/polychromatic/stable/ubuntu kinetic InRelease                                                                     
> OK:16 http://ppa.launchpad.net/polychromatic/stable/ubuntu kinetic InRelease       
> Holen:17 http://de.archive.ubuntu.com/ubuntu kinetic-updates/main amd64 Packages [329 kB]                                                        
> Ign:18 http://ppa.launchpad.net/wireshark-dev/nightly/ubuntu jammy InRelease                                                                     
> Holen:19 http://de.archive.ubuntu.com/ubuntu kinetic-updates/main i386 Packages [180 kB]                                                                
> Holen:20 http://de.archive.ubuntu.com/ubuntu kinetic-updates/main Translation-en [90,1 kB]                                                                                       
> Holen:21 http://de.archive.ubuntu.com/ubuntu kinetic-updates/main amd64 DEP-11 Metadata [84,2 kB]                                                                                
> Fehl:22 http://ppa.launchpad.net/cybermax-dexter/vkd3d/ubuntu kinetic Release                                                   
>   404  Not Found [IP: 2620:2d:4000:1::3e 80]
> Holen:23 http://de.archive.ubuntu.com/ubuntu kinetic-updates/universe amd64 Packages [202 kB]                                                                                                   
> Fehl:13 http://ppa.launchpad.net/openrazer/stable/ubuntu kinetic InRelease                                                                                                              
>   Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 073E051D7B2AEE37
> Holen:24 http://de.archive.ubuntu.com/ubuntu kinetic-updates/universe i386 Packages [117 kB]                                                            
> Holen:25 https://ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu kinetic/main Sources [3.972 B]     
> Holen:26 http://de.archive.ubuntu.com/ubuntu kinetic-updates/universe amd64 DEP-11 Metadata [38,1 kB]                    
> Fehl:27 http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu kinetic Release                                                                             
>   404  Not Found [IP: 2620:2d:4000:1::3e 80]
> Holen:28 http://de.archive.ubuntu.com/ubuntu kinetic-updates/multiverse amd64 DEP-11 Metadata [212 B]                                                                    
> Holen:29 http://de.archive.ubuntu.com/ubuntu kinetic-backports/universe amd64 DEP-11 Metadata [10,9 kB]                                                                  
> Fehl:30 http://ppa.launchpad.net/wireshark-dev/nightly/ubuntu jammy Release                                                                                                                 
>   404  Not Found [IP: 2620:2d:4000:1::3e 80]
> Holen:31 http://security.ubuntu.com/ubuntu kinetic-security/main Sources [83,9 kB]                              
> Holen:32 https://ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu kinetic/main amd64 Packages [7.380 B]
> Holen:33 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu kinetic/main Sources [3.972 B]                                                    
> Fehl:16 http://ppa.launchpad.net/polychromatic/stable/ubuntu kinetic InRelease                                                                                                   
>   Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 96B9CD7C22E2C8C5
> Holen:34 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu kinetic/main amd64 Packages [7.380 B]                                                     
> Holen:35 http://ppa.launchpad.net/oibaf/graphics-drivers/ubuntu kinetic/main i386 Packages [6.860 B]                                                                    
> Holen:36 https://ppa.launchpadcontent.net/oibaf/graphics-drivers/ubuntu kinetic/main i386 Packages [6.860 B]                                    
> Holen:37 http://security.ubuntu.com/ubuntu kinetic-security/main i386 Packages [114 kB]
> Holen:38 http://security.ubuntu.com/ubuntu kinetic-security/main amd64 Packages [242 kB]
> Holen:39 http://security.ubuntu.com/ubuntu kinetic-security/main Translation-en [66,0 kB]
> Holen:40 http://security.ubuntu.com/ubuntu kinetic-security/main amd64 DEP-11 Metadata [28,6 kB]
> Holen:41 http://security.ubuntu.com/ubuntu kinetic-security/main amd64 c-n-f Metadata [5.844 B]
> Holen:42 http://security.ubuntu.com/ubuntu kinetic-security/universe i386 Packages [84,0 kB]
> Holen:43 http://security.ubuntu.com/ubuntu kinetic-security/universe amd64 Packages [137 kB]
> Holen:44 http://security.ubuntu.com/ubuntu kinetic-security/universe Translation-en [58,2 kB]
> Holen:45 http://security.ubuntu.com/ubuntu kinetic-security/universe amd64 DEP-11 Metadata [4.452 B]
> Holen:46 http://security.ubuntu.com/ubuntu kinetic-security/universe amd64 c-n-f Metadata [6.308 B]
> Paketlisten werden gelesen… Fertig                         
> W: Ziel Packages (main/binary-amd64/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Packages (main/binary-i386/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Packages (main/binary-all/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Translations (main/i18n/Translation-de_DE) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Translations (main/i18n/Translation-de) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Translations (main/i18n/Translation-en) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11 (main/dep11/Components-amd64.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11 (main/dep11/Components-all.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons-small (main/dep11/icons-48x48.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons (main/dep11/icons-64x64.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons-large (main/dep11/icons-128x128.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel CNF (main/cnf/Commands-amd64) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel CNF (main/cnf/Commands-all) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> E: Das Depot »http://ppa.launchpad.net/cybermax-dexter/vkd3d/ubuntu kinetic Release« enthält keine Release-Datei.
> N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
> N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
> W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://ppa.launchpad.net/openrazer/stable/ubuntu kinetic InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 073E051D7B2AEE37
> E: Das Depot »http://ppa.launchpad.net/flexiondotorg/mangohud/ubuntu kinetic Release« enthält keine Release-Datei.
> N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
> N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
> E: Das Depot »http://ppa.launchpad.net/wireshark-dev/nightly/ubuntu jammy Release« enthält keine Release-Datei.
> N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
> N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
> W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Depot wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://ppa.launchpad.net/polychromatic/stable/ubuntu kinetic InRelease: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 96B9CD7C22E2C8C5
> W: Ziel Packages (main/binary-amd64/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Packages (main/binary-i386/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Packages (main/binary-all/Packages) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Translations (main/i18n/Translation-de_DE) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Translations (main/i18n/Translation-de) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel Translations (main/i18n/Translation-en) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11 (main/dep11/Components-amd64.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11 (main/dep11/Components-all.yml) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons-small (main/dep11/icons-48x48.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons (main/dep11/icons-64x64.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons-hidpi (main/dep11/icons-64x64@2.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel DEP-11-icons-large (main/dep11/icons-128x128.tar) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel CNF (main/cnf/Commands-amd64) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> W: Ziel CNF (main/cnf/Commands-all) ist mehrfach konfiguriert in /etc/apt/sources.list:49 und /etc/apt/sources.list.d/winehq.list:1
> 

it finishes and then you can run apt-get upgrade just fine

**Comment by yoshimo** [comment]
I think topgrade needs to handle special cases better like repository duplicates that are in sources.lst and have their own copy as repository.lst in the sources.list.d subfolder or pgp keys that are missing.
Some repositories are upgraded to the latest ubuntu release in the dist-upgrade process but if the repo owner does not build packages for the recent release just yet. This shouldn't block topgrade.

Assist the user in cleaning this up would be my suggestion.

**Comment by DottoDev** [comment]
This would lead to the same problem as #320, that Topgrade has to fix the issues other package managers have.

**Comment by DottoDev** [comment]
The problem, if I understand it right, is not, that `apt-get update` doesnt't run because the error just appears after the command has run, the problem is that because `apt-get update` errors out `apt-get upgrade` doesn't run. Will have a look at that.
