### ISSUE TITLE
error: This system was not booted via libostree

### ISSUE THREAD

**Issue by AWHubGit** [topgrade-rs/topgrade#387]
## What did you expect to happen?

topgrade is running without errors as it did before

## What actually happened?

topgrade is exiting with an error

## Additional Details
- Which operating system or Linux distribution are you using?
Fedora Linux 37 (Workstation Edition) x86_64
Kernel: 6.1.18-200.fc37.x86_64

- How did you install Topgrade?
Manually
- Which version are you running? 

Topgrade 10.3.3

topgrade --dry-run

── 04:19:14 - System update ────────────────────────────────────────────────────
Dry running: /usr/bin/rpm-ostree upgrade

── 04:19:14 - Brew ─────────────────────────────────────────────────────────────
Dry running: brew update
Dry running: brew upgrade --ignore-pinned --formula

── 04:19:14 - Gnome Shell extensions ───────────────────────────────────────────
Dry running: /usr/bin/gdbus call --session --dest org.gnome.Shell.Extensions --object-path /org/gnome/Shell/Extensions --method org.gnome.Shell.Extensions.CheckForUpdates

── 04:19:15 - pip3 ─────────────────────────────────────────────────────────────
Dry running: /home/linuxbrew/.linuxbrew/bin/python3 -m pip install --upgrade --user pip

── 04:19:15 - Node Package Manager ─────────────────────────────────────────────

── 04:19:15 - Containers ───────────────────────────────────────────────────────

── 04:19:15 - Flatpak User Packages ────────────────────────────────────────────
Dry running: /usr/bin/flatpak update --user

── 04:19:15 - Flatpak System Packages ──────────────────────────────────────────
Dry running: /usr/bin/flatpak update --system

── 04:19:15 - Firmware upgrades ────────────────────────────────────────────────
Dry running: /usr/bin/fwupdmgr refresh
Dry running: /usr/bin/fwupdmgr get-updates

<details>

<pre>

── 04:20:18 - System update ────────────────────────────────────────────────────
DEBUG Detected "/usr/bin/rpm-ostree" as "rpm-ostree"
DEBUG Executing command `/usr/bin/rpm-ostree upgrade`
error: This system was not booted via libostree.
Currently, most rpm-ostree commands only work on ostree-based host systems.

DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:176

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "System update" failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:176

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:176

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

</pre>
</details>

**Comment by DottoDev** [comment]
Normally there should be a check that that won't happen. Will look into that

**Comment by DottoDev** [comment]
Just for debugging, could you send in your os-release file

**Comment by AWHubGit** [comment]
`cat /etc/os-release 


NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
`
If you are testing for a binary "Detected "/usr/bin/rpm-ostree" as "rpm-ostree"" and there is one found you can't assume that this system is based on libostree as for example Fedora Silverblue or EndlessOS.

Flatpak also uses rpm-ostree. Try command "flatpak update --ostree-verbose".

**Comment by DottoDev** [comment]
Currently getting fixed, and yes indeed, topgrade is checking for the `rpm-ostree` command xD
