### ISSUE TITLE
Fedora 38 - Incorrect use of rpm-ostree vs dnf 

### ISSUE THREAD

**Issue by mdhankins1** [topgrade-rs/topgrade#402]
My computer is running Fedora 38 Workstation beta (not Silverblue).  

── 20:28:29 - System update ────────────────────────────────────────────────────
error: This system was not booted via libostree.
Currently, most rpm-ostree commands only work on ostree-based host systems.

System update failed: 
   0: Command failed: `/usr/bin/rpm-ostree upgrade`
   1: `/usr/bin/rpm-ostree` failed: exit status: 1

Location:
   src/steps/os/linux.rs:176

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by mdhankins1** [comment]
Forgot to mention that the rest of the log looks normal.

**Comment by DottoDev** [comment]
Could you try out #395 and see if this patch works?

**Comment by mdhankins1** [comment]
I just ran topgrade and saw it upgrade to version 10.3.3, which still has the issue.  How do I apply the patch?  I am not a developer.

**Comment by SteveLauC** [comment]
> I just ran topgrade and saw it upgrade to version 10.3.3, which still has the issue. How do I apply the patch? I am not a developer.

The latest version 11.0.0 (released in crates.io) has that patch included, you can try it now.

**Comment by mdhankins1** [comment]
It is working correctly for me now.  Thanks.

**Comment by SteveLauC** [comment]
Then we can close this issue:)
