### ISSUE TITLE
[Feature Request]Change the config path to `CONFIG_DIR/topgrade/topgrade.toml`

### ISSUE THREAD

**Issue by SteveLauC** [topgrade-rs/topgrade#411]
## I want to suggest some general feature
Maybe the configuration path should be `CONFIG_DIR/topgrade/topgrade.toml` instead of just `CONFIG_DIR/topgrade.toml` so that `CONFIG_DIR` could be tidy.

And for those who would like to manage their dotfiles, they can simply symlink the `topgrade` directory without caring about the actual contents.

-----
Feel free to close the issue if you guys don't like this idea, maybe it is just me who is so fastidious about this stuff. But if you guys do want this feature, I am happy to submit a patch:)

**Comment by DottoDev** [comment]
Feel free to submit a patch but I would like it more if topgrade would just accept both locations and if both exist to prefer the `CONFIG_DIR/topgrade.toml` file.

**Comment by SteveLauC** [comment]
So `topgrade` is going to support multiple configuration paths(in order of priority):
1. `CONFIG_DIR/topgrade.toml`
2. `CONFIG_DIR/topgrade/topgrade.toml`

## Some questions about the future behavior

1. In the current implementation, `topgrade` will create a configuration file at `CONFIG_DIR/topgrade.toml` if it does exist. After switching to multiple config file mode, what is the desired behavior for this, creating a configuration file at `CONFIG_DIR/topgrade.toml` if **both** config files don't exist?
   > An alternative is that we don't create config file by default, like [alacritty](https://github.com/alacritty/alacritty#configuration) did, but I would consider this as a breaking change since it differs from the current impl.

2. And what if both config files exist, and the config at `CONFIG_DIR/topgrade.toml` is invalid, should we use the config at `CONFIG_DIR/topgrade/topgrade.toml` or simply give user an error then do the upgrade(i.e., we find `CONFIG_DIR/topgrade.toml`, we use it, and ignore `CONFIG_DIR/topgrade/topgrade.toml`)?

**Comment by tmcarr** [comment]
Why not just default to /etc/default/topgrade.toml ?

**Comment by SteveLauC** [comment]
> Why not just default to /etc/default/topgrade.toml ?

I guess that's for the system software?

**Comment by DottoDev** [comment]
> Why not just default to /etc/default/topgrade.toml ? 

We can not assume that the user has the rights to write a file to the /etc/ location or that this file exists. XDG spec says that .config/ is the place where those files should be placed.

**Comment by DottoDev** [comment]
> So `topgrade` is going to support multiple configuration paths(in order of priority):
> 
> 1. `CONFIG_DIR/topgrade.toml`
> 
> 2. `CONFIG_DIR/topgrade/topgrade.toml`
> 

Yes, correct

> 
> ## Some questions about the future behavior
> 
> 
> 
> 1. In the current implementation, `topgrade` will create a configuration file at `CONFIG_DIR/topgrade.toml` if it does exist. After switching to multiple config file mode, what is the desired behavior for this, creating a configuration file at `CONFIG_DIR/topgrade.toml` if **both** config files don't exist?
> 
>    > An alternative is that we don't create config file by default, like [alacritty](https://github.com/alacritty/alacritty#configuration) did, but I would consider this as a breaking change since it differs from the current impl.
> 

`CONFIG_DIR/topgrade.toml` should be the default file and should be created if no config file exists.

> 
> 2. And what if both config files exist, and the config at `CONFIG_DIR/topgrade.toml` is invalid, should we use the config at `CONFIG_DIR/topgrade/topgrade.toml` or simply give user an error then do the upgrade(i.e., we find `CONFIG_DIR/topgrade.toml`, we use it, and ignore `CONFIG_DIR/topgrade/topgrade.toml`)?


If both exist, `CONFIG_DIR/topgrade.toml` should always be preferred, even if it is invalid.
