### ISSUE TITLE
Topgrade-invoked mas should not be trying to update a (seemingly - false positive) outdated app

### ISSUE THREAD

**Issue by gmerlino** [topgrade-rs/topgrade#412]
## What did you expect to happen?

Topgrade *not* upgrading a MAS-installed App which is already at the latest version (Paste - pasteapp.io, at 3.1.9 already)

## What actually happened?

At each invocation of topgrade, Paste (version 3.1.9) will be (re)installed. By checking with `mas outdated`, I get the following output:

`967805235 Paste (3.1.9 -> 3.2)`

so I expect this "glitch" to be the root cause. In particular, there is no 3.2 release (yet), as MAS is (mistakenly) checking as well (and conflating) the versions of the iOS flavour of the same App, and the iOS one indeed is at 3.2.

## Additional Details
- Which operating system or Linux distribution are you using?

MacOS Ventura (13.3.1)

- How did you install Topgrade?

Brew

- Which version are you running? 

11.0.0

<details>

<pre>

N.B.: it looks definitely as an issue with MAS, but I'm referring to this behavior as a bug for Topgrade as I feel that Topgrade is meant exactly for that - automate away upgrade chores, and work around issues/limitations of the invoked package managers, when feasible (e.g., pinning stuff, double-checking assumptions made by the p.m., etc.), obviously short of just disabling that package manager from the Topgrade TOML (as a last resort)

</pre>
</details>

**Comment by DottoDev** [comment]
Thanks for brining this up. Does `mas upgrade` also run into this error?

**Comment by DottoDev** [comment]
This is a bug in the `mas` tool and not in `topgrade`. Please open an issue at the `mas` github.
