### ISSUE TITLE
v11.0.1 reports it's version as v.11.0.0

### ISSUE THREAD

**Issue by p-linnane** [topgrade-rs/topgrade#415]
## What did you expect to happen?
`topgrade --version` returns `Topgrade 11.0.1`

## What actually happened?
`topgrade --version` returns `Topgrade 11.0.0`

## Additional Details
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v11.0.1 of topgrade we ran into a test failure where the version was not reported correctly.

Relates to https://github.com/Homebrew/homebrew-core/pull/129879

**Comment by DottoDev** [comment]
Oh sorry, forgot that

**Comment by DottoDev** [comment]
Resolved now

**Comment by p-linnane** [comment]
Thank you for the quick response!
