### ISSUE TITLE
Latest Topgrade release is not in Homebrew

### ISSUE THREAD

**Issue by klausi** [topgrade-rs/topgrade#42]
## What did you expect to happen?
`brew install topgrade` should install version 9.1.0 from this repository.

## What actually happened?
`brew install topgrade` installs the old 9.0.1 version

Can you take over maintainership over the Homebrew formulae?

**Comment by DottoDev** [comment]
Working on it.

**Comment by DottoDev** [comment]
I don't have the hardware required to do the MacOS builds so there has to be someone else who makes them before I can update it.

**Comment by klausi** [comment]
Great, thanks a lot!

**Comment by DottoDev** [comment]
Currently Pending
https://github.com/Homebrew/homebrew-core/pull/113721

**Comment by DottoDev** [comment]
V10.0.0 is now available at Homebrew
