### ISSUE TITLE
Possibility to add Oh My Bash? 

### ISSUE THREAD

**Issue by BackSpace54** [topgrade-rs/topgrade#424]
## I want to suggest a new step
Hi could you add the support of Oh My Bash (https://github.com/ohmybash/oh-my-bash)?

## More information
Oh My Bash provides a script for self updating located here: `$OSH/tools/upgrade.sh`
$OSH is `~/.oh-my-bash`
Command update could be something like this
`export OSH=~/.oh-my-bash && source $OSH/tools/upgrade.sh`

Thanks.

**Comment by SteveLauC** [comment]
Hi, does `oh-my-bash` support external plugin like `oh-my-zsh` [did](https://github.com/ohmyzsh/ohmyzsh/wiki/External-plugins), such an external plugin is installed (cloned) through git, take [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#oh-my-zsh) as an example:

```shell
$ git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
```
Thus, to update `oh-my-zsh`, `topgrade` should also update these external plugins:
https://github.com/topgrade-rs/topgrade/blob/227e8dcc8dc1383745b8e883b13aaff384f07d8c/src/steps/zsh.rs#L190-L193

Do we need this in `oh-my-bash`?
> Sorry for asking this question, I am not a bash user

**Comment by BackSpace54** [comment]
Hi,
i'm a not a power user of oh-my-bash but it seems you're right about the plugins.
I'm not aware of a such possibility in `oh-my-bash` about external plugins so we don't need plugins updates.
Thanks.
