### ISSUE TITLE
builds without self-upgrade in releases

### ISSUE THREAD

**Issue by OldWorldOrdr** [topgrade-rs/topgrade#428]
[scoop](https://scoop.sh/) a package manager for windows ships packages directly from the release pages of the projects, instead of building themselves, there's probably other similar projects that do the same, plus it would just be a nice option to have for some people.

**Comment by signed-log** [comment]
I would be interested too as a maintainer of the openSUSE (RPM) package

I might go ahead and try to achieve that (likely using a cargo feature flag) before `12.0` (due to a breaking change in #417) is ready to roll

**Comment by DottoDev** [comment]
@signed-log There is already a feature flag for self updating

**Comment by SteveLauC** [comment]
> I would be interested too as a maintainer of the openSUSE (RPM) package
> 
> I might go ahead and try to implement the backend code to achieve that (likely using a cargo feature flag) before `12.0` (due to a breaking change in #417) is ready to roll

Have you take a look at https://github.com/topgrade-rs/topgrade/issues/157, It seems there is already some work done on that
