### ISSUE TITLE
Self update points to the wrong repository

### ISSUE THREAD

**Issue by klausi** [topgrade-rs/topgrade#43]
## What did you expect to happen?
Topgrade can update itself on this repository.

## What actually happened?
In the source code I see that r-darwish is still used: https://github.com/topgrade-rs/topgrade/blob/master/src/self_update.rs#L18 . So this probably needs to be changed?

**Comment by DottoDev** [comment]
This is known and got already submitted by @ssmendon in PR #41 . But thank you for bringing it up. Also I don't really know how the self update function works right now so PRs are welcome.

**Comment by ssmendon** [comment]
I haven't tested the self-update functionality myself (yet), so I'm not sure if the changes work as described. Any pointers on automation?

It's using the [self_update crate](https://docs.rs/self_update/latest/self_update/) which seems to have a pretty simple builder API.

**Comment by klausi** [comment]
I think one prerequisite for this is to have binary releases on Github for all supported platforms. Compare https://github.com/r-darwish/topgrade/releases/tag/v9.0.1 vs. https://github.com/topgrade-rs/topgrade/releases/tag/v9.1.0

**Comment by DottoDev** [comment]
I have a script in development to build all required releases, but I still have the problem of Macos and windows-msvc(windows-gnu is possible) releases, because I can't build them myself.

**Comment by ssmendon** [comment]
I could build for macOS M1 and Windows-MSVC, though I'm not sure if I can on a continuing basis.

At the very least, we could investigate failing gracefully (not sure how the present code propagates errors for this) where the target triple isn't available under releases.

**Comment by DottoDev** [comment]
Packaging for windows and M1 would be great :)

It's definitely a good idea, just throwing an error and crashing is definitely not the right direction to go with that.

**Comment by klausi** [comment]
It looks like the old project used a Github action to make the releases https://github.com/r-darwish/topgrade/blob/master/.github/workflows/release.yml , would that be an option?

**Comment by DottoDev** [comment]
I will set it up for Windows and MacOS at least, Unix will be done via the build-all.sh script.

**Comment by DottoDev** [comment]
Done with #61

**Comment by Zahrun** [comment]
[v10.0.1](https://github.com/topgrade-rs/topgrade/releases/tag/v10.0.1)
Has no linux asset. Or are you manually going to add them there?

**Comment by DottoDev** [comment]
They will be added, this was mainly to test out the CI Pipeline.
