### ISSUE TITLE
Firmware update returning error

### ISSUE THREAD

**Issue by lisandrocarmona** [topgrade-rs/topgrade#432]
## What did you expect to happen?
Topgrade updates firmware.

## What actually happened?
Failed with error described below.

## Additional Details
- Which operating system or Linux distribution are you using? Arch Linux
- How did you install Topgrade? Script
- Which version are you running?  Topgrade 11.0.0

<details>
── 15:06:08 - Firmware upgrades ────────────────────────────────────────────────
Updating lvfs
Downloading…                [  -                                    ]
failed to download file: OpenSSL/3.0.8: error:0A000458:SSL routines::tlsv1 unrecognized name
Firmware upgrades failed:
0: Command failed: `/usr/bin/fwupdmgr refresh`
1: `/usr/bin/fwupdmgr` failed: exit status: 1

Location:
/home/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-11.0.0/src/executor.rs:182

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⋮ 1 frame hidden ⋮
2: <E as eyre::context::ext::StdError>::ext_report::ha405aef5e001e0f3
at <unknown source file>:<unknown line>
3: topgrade::executor::Executor::status_checked_with_codes::h521eda5180c6159a
at <unknown source file>:<unknown line>
4: topgrade::runner::Runner::execute::h0729b834dd0c537f
at <unknown source file>:<unknown line>
5: topgrade::run::h2cd8ed30da28696e
at <unknown source file>:<unknown line>
6: topgrade::main::h702fb4109d79e569
at <unknown source file>:<unknown line>
7: std::sys_common::backtrace::__rust_begin_short_backtrace::hb9bd62f02966ed57
at <unknown source file>:<unknown line>
8: main<unknown>
at <unknown source file>:<unknown line>
9: __libc_start_main<unknown>
at <unknown source file>:<unknown line>
10: _start<unknown>
at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
</details>

**Comment by DottoDev** [comment]
This looks like a fwupd error and not something topgrade has any influence on.
