### ISSUE TITLE
Distribute `topgrade` through `pip`

### ISSUE THREAD

**Issue by SteveLauC** [topgrade-rs/topgrade#462]
`pip` nowadays really becomes a general-purpose package manager, and is the most likely installed package manager on a user's computer, it would be much better if we can distribute `topgrade` through `pip`:

```shell
$ pip install topgrade
```

And this isn't something hard, [PyO3: maturin](https://github.com/PyO3/maturin) can be used to get it done with ONLY few steps.

The main benefit of doing this is that we can fill the gap where Linux packages are missing, maintaining Linux packages is hard, so many distros, and so many formats.

**Comment by keilmillerjr** [comment]
"pip is the [package installer](https://packaging.python.org/guides/tool-recommendations/) for Python." Meanwhile, topgrade is  [Rust 98.6%](https://github.com/topgrade-rs/topgrade/search?l=rust). I am not sure how the two belong together. That would be like me using ruby gems to install topgrade. I can, however, it doesn't make sense.

**Comment by SteveLauC** [comment]
Kinda make sense, but like I said:

> pip nowadays really becomes a general-purpose package manager, and is the most likely installed package manager on a user's computer

If `topgrade` does it, it is not the first non-python project that is distributed through pip, [`cmake`](https://pypi.org/project/cmake/) already did this (it is written in C++):

```shell
$ pip install cmake
```

**Comment by signed-log** [comment]
Python is built in C/C++, and indeed many C libs can be shipped through pip.

The only tool supporting packaging rust extensions is [setuptools-rust](https://setuptools-rust.readthedocs.io/en/latest/README.html), and it only supports Python **extensions**, not fully standalone

**Comment by SteveLauC** [comment]
> Python is built in C/C++, and indeed many C libs can be shipped through pip because it's the same language (you can run C code through Pyhton).

Yep, that's true.

> The only tool supporting packaging rust extensions is [setuptools-rust](https://setuptools-rust.readthedocs.io/en/latest/README.html), and it only supports Rust extensions for Python (based on specific librairies), and not fully standalone libs/extensions

In the [README of manturin](https://github.com/PyO3/maturin), it states that `manturin` aims to be a **zero configuration replacement** for `setuptools-rust`.

-----

I am not quite familiar with Python and its echo system, so correct me if I am wrong. To my knowledge, I understand what you said, but I think that is for **library**, `topgrade` currently is a **binary**, we are not creating source level Python bindings for `topgrade`.

And using `manturin`, packaging `topgrade` binary into a Python wheel seems to be easy, then you can distribute that wheel file or upload it to `pypi` for easier installation:

```shell
$ pwd
/home/steve/Documents/workspace/topgrade

$ cat pyproject.toml
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: pyproject.toml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [build-system]
   2   │ requires = ["maturin>=1.0,<2.0"]
   3   │ build-backend = "maturin"
   4   │
   5   │ [project]
   6   │ name = "topgrade"
   7   │ requires-python = ">=3.7"
   8   │ classifiers = [
   9   │     "Programming Language :: Rust",
  10   │     "Programming Language :: Python :: Implementation :: CPython",
  11   │     "Programming Language :: Python :: Implementation :: PyPy",
  12   │ ]
  13   │
  14   │
  15   │ [tool.maturin]
  16   │ bindings = "bin"
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────

$ maturin build -r
📦 Including license file "/home/steve/Documents/workspace/topgrade/LICENSE"
🔗 Found bin bindings
📡 Using build options bindings from pyproject.toml
   Compiling topgrade v11.0.2 (/home/steve/Documents/workspace/topgrade)
    Finished release [optimized] target(s) in 58.84s
📦 Built wheel to /home/steve/Documents/workspace/topgrade/target/wheels/topgrade-11.0.2-py3-none-manylinux_2_34_x86_64.whl

$ ls target/wheels/topgrade-11.0.2-py3-none-manylinux_2_34_x86_64.whl
Permissions Links Size User  Group Date Modified Name
.rw-r--r--@     1 3.6M steve steve  7 Jun 08:44  target/wheels/topgrade-11.0.2-py3-none-manylinux_2_34_x86_64.whl

$ pip install target/wheels/topgrade-11.0.2-py3-none-manylinux_2_34_x86_64.whl
Defaulting to user installation because normal site-packages is not writeable
Processing ./target/wheels/topgrade-11.0.2-py3-none-manylinux_2_34_x86_64.whl
Installing collected packages: topgrade
Successfully installed topgrade-11.0.2

$ which topgrade
~/.local/bin/topgrade
```

**Comment by SteveLauC** [comment]
Friendly ping @DottoDev, thoughts on this?

**Comment by DottoDev** [comment]
Seems good to me if you can get it to work on multiple platforms. Don't know how this would work but it should at least work on linux and macos.

**Comment by SteveLauC** [comment]
I have tested it via [SteveLauC/test_topgrade_pip](https://github.com/SteveLauC/test_topgrade_pip)

### CI
The release process can be automated in CI, see this [config file](https://github.com/SteveLauC/test_topgrade_pip/blob/main/.github/workflows/release_pypi.yaml)

### Supported OS and Architectures
* Linux
  * x64
  * x86
  * aarch64
 * macOS
   * x64
   * aarch64
* Windows
   * x64
   * x86
 
----

I have uploaded the latest git version to [pypi](https://pypi.org/project/topgrade/), you can try it now:

```shell
$ pip install topgrade
```

It is under my personal account currently, I have submitted a request to create the `topgrade-rs` organization, when approved, I will transfer it to the organization.

**Comment by Auravendill** [comment]
I tested it on my Debian 12 server and it failed.

```
pip install topgrade
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Idk how that changes the whole argument about being multiplatform, if Debian-based distros are excluded?

**Comment by SteveLauC** [comment]
> I tested it on my Debian 12 server and it failed.
> 
> 
> 
> ```
> 
> pip install topgrade
> 
> error: externally-managed-environment
> 
> 
> 
> × This environment is externally managed
> 
> ╰─> To install Python packages system-wide, try apt install
> 
>     python3-xyz, where xyz is the package you are trying to
> 
>     install.
> 
> 
> 
>     If you wish to install a non-Debian-packaged Python package,
> 
>     create a virtual environment using python3 -m venv path/to/venv.
> 
>     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
> 
>     sure you have python3-full installed.
> 
> 
> 
>     If you wish to install a non-Debian packaged Python application,
> 
>     it may be easiest to use pipx install xyz, which will manage a
> 
>     virtual environment for you. Make sure you have pipx installed.
> 
> 
> 
>     See /usr/share/doc/python3.11/README.venv for more information.
> 
> 
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
> 
> hint: See PEP 668 for the detailed specification.
> 
> ```
> 
> 
> 
> Idk how that changes the whole argument about being multiplatform, if Debian-based distros are excluded?

Debian-based distros definitely won't be excluded, I will investigate the issue

**Comment by SteveLauC** [comment]
@Auravendill 

From [this answer](https://stackoverflow.com/a/75696359/14092446), this is for the reason that Debian adopted [PEP 668 – Marking Python base environments as “externally managed”](https://peps.python.org/pep-0668/).

To fix this (or avoid this), you can:

1. Use a virtual env
2. Install through `pipx`: `pipx install topgrade`
3. Install another `python` that does not adopt `PEP 668`

**Comment by SteveLauC** [comment]
Pin this issue to get more exposure and possibly more tests:)

**Comment by bibz** [comment]
`pipx run topgrade` worked just fine on my Debian 11 box :+1:

**Comment by SteveLauC** [comment]
It is kinda weird that PyPi hasn't approved my request, it is almost a month...

![Screenshot from 2023-07-05 14-16-02](https://github.com/topgrade-rs/topgrade/assets/96880612/6e507834-f7fa-405a-9d99-5a8940d2d347)
