### ISSUE TITLE
Topgrade uses `python3` shim instead of real `python` binary on windows

### ISSUE THREAD

**Issue by soredake** [topgrade-rs/topgrade#470]
## What did you expect to happen?
Topgrade should use real `python` binary on windows, not `python3` shim that will only open microsoft store.

## What actually happened?
Topgrade uses `python3` shim instead of real `python` binary on windows.

## Additional Details
- Which operating system or Linux distribution are you using? Windows 11 Pro
- How did you install Topgrade? Downloaded binary from github.
- Which version are you running? Topgrade 11.0.2

<details>
<pre>
❯ .\topgrade -v --only pip3
DEBUG Configuration at C:\Users\user\AppData\Roaming\topgrade.toml
DEBUG Loaded configuration: ConfigFile { sudo_command: None, pre_sudo: None, pre_commands: Some({}), post_commands: None, commands: Some({}), git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, display_preamble: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, python: Some(Python { enable_pip_review: None, enable_pipupgrade: None }), no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None, wsl_update_pre_release: None, wsl_update_use_web_download: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), no_self_update: None }
DEBUG Version: 11.0.2
DEBUG OS: x86_64-pc-windows-msvc
DEBUG Args { inner: ["C:\\Users\\user\\Downloads\\topgrade.exe", "-v", "--only", "pip3"] }
DEBUG Binary path: Ok("C:\\Users\\user\\Downloads\\topgrade.exe")
DEBUG Self Update: true
DEBUG Detected "C:\\Program Files\\Git\\cmd\\git.EXE" as "git"
DEBUG Cannot find "doas"
DEBUG Cannot find "please"
DEBUG Detected "C:\\Program Files\\gsudo\\Current\\sudo.EXE" as "sudo"

── 17:27:00 - Self update ──────────────────────────────────────────────────────
DEBUG starting new connection: https://api.github.com/
DEBUG resolving host="api.github.com"
DEBUG connecting to 140.82.121.6:443
DEBUG connected to 140.82.121.6:443
DEBUG No cached session for DnsName(DnsName(DnsName("api.github.com")))
DEBUG Not resuming any session
DEBUG Using ciphersuite TLS13_AES_128_GCM_SHA256
DEBUG Not resuming
DEBUG TLS1.3 encrypted extensions: [ServerNameAck, Protocols([6832])]
DEBUG ALPN protocol is Some(b"h2")
DEBUG binding client connection
DEBUG client connection bound
DEBUG send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
DEBUG Connection{peer=Client}: new
DEBUG Connection{peer=Client}: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
DEBUG pooling idle connection for ("https", api.github.com)
DEBUG Connection{peer=Client}: send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
DEBUG Connection{peer=Client}: Ticket saved
DEBUG Connection{peer=Client}: Ticket saved
DEBUG Connection{peer=Client}: received frame=Settings { flags: (0x0), max_concurrent_streams: 100, initial_window_size: 67108864, max_frame_size: 65536, enable_connect_protocol: 1 }
DEBUG Connection{peer=Client}: send frame=Settings { flags: (0x1: ACK) }
DEBUG Connection{peer=Client}: received frame=Settings { flags: (0x1: ACK) }
DEBUG Connection{peer=Client}: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
DEBUG Connection{peer=Client}: received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
DEBUG Connection{peer=Client}: received frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
DEBUG Connection{peer=Client}: close
Topgrade is up-to-date
DEBUG Detected "C:\\Program Files\\PowerShell\\7\\pwsh.EXE" as "pwsh"
DEBUG Executing command `C:\Program Files\PowerShell\7\pwsh.EXE -NoProfile -Command 'Split-Path $profile'`
DEBUG Path "C:\\Users\\user\\Documents\\PowerShell" exists
DEBUG Path "C:\\Users\\user\\AppData\\Roaming\\.emacs.d" doesn't exist
DEBUG C:\Users\user\.ideavimrc does not exists
DEBUG C:\Users\user\.intellimacs does not exists
DEBUG Checking if \\?\C:\Users\user\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState is a git repository
DEBUG Transformed path to C:\Users\user\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState
DEBUG Executing command `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any of the parent directories): .git
   1: `C:\Program Files\Git\cmd\git.EXE` failed: exit code: 128

Location:
   src\steps\git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Startup link: Lnk { path: Some("C:\\Users\\user\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\64Gram.lnk"), header: ShellLinkHeader { header_size: 76, link_clsid: 93045959704944114645041356371858166785, link_flags: HAS_LINK_TARGET_ID_LIST | HAS_LINK_INFO | HAS_NAME | HAS_RELATIVE_PATH | HAS_WORKING_DIR | HAS_ARGUMENTS | IS_UNICODE, file_attributes: (empty), creation_time: 133308061026854264, access_time: 133309393587768394, write_time: 133308061243582882, file_size: 133812224, icon_index: 0, show_command: SW_SHOWNORMAL, hot_key: HotKeyFlags { low_byte: 0, high_byte: 0 }, reserved1: 0, reserved2: 0, reserved3: 0, created_on: Some(2023-06-09T17:41:42.685Z), modified_on: Some(2023-06-09T17:42:04.358Z), accessed_on: Some(2023-06-11T06:42:38.776Z) }, string_data: StringData { name_string: Some("Telegram autorun link.\nYou can disable autorun in Telegram settings."), relative_path: Some("..\\..\\..\\..\\..\\64Gram Desktop\\Telegram.exe"), working_dir: Some("C:\\Users\\user\\AppData\\Roaming\\64Gram Desktop"), command_line_arguments: Some("-autostart"), icon_location: None }, link_target_id_list: LinkTargetIdList, link_info: LinkInfo { link_info_size: 114, link_info_header_size: 28, link_info_flags: Some(VOLUME_ID_AND_LOCAL_BASE_PATH), volume_id_offset: 28, local_base_path_offset: 55, common_network_relative_link_offset: 0, common_path_suffix_offset: 113, local_base_path_offset_unicode: 27, common_path_suffix_offset_unicode: 3, volume_id: None, local_base_path: Some("C:\\Users\\user\\AppData\\Roaming\\64Gram Desktop\\Telegram.exe"), common_network_relative_link: None, common_path_suffix: None, local_base_path_unicode: None, common_path_suffix_unicode: None }, extra_data: ExtraData { darwin_props: None, special_folder_props: None, console_props: None, console_fe_props: None, environment_props: None, icon_environment_props: None, known_folder_props: None, property_store_props: Some(PropertyStoreDataBlock { block_size: 166, block_signature: 2684354569, property_store: [97, 0, 0, 0, 49, 83, 80, 83, 85, 40, 76, 159, 121, 159, 57, 75, 168, 208, 225, 212, 45, 225, 213, 243, 69, 0, 0, 0, 5, 0, 0, 0, 0, 31, 0, 0, 0, 25, 0, 0, 0, 84, 0, 101, 0, 108, 0, 101, 0, 103, 0, 114, 0, 97, 0, 109, 0, 46, 0, 84, 0, 101, 0, 108, 0, 101, 0, 103, 0, 114, 0, 97, 0, 109, 0, 68, 0, 101, 0, 115, 0, 107, 0, 116, 0, 111, 0, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0, 49, 83, 80, 83, 177, 22, 109, 68, 173, 141, 112, 72, 167, 72, 64, 46, 164, 61, 120, 140, 29, 0, 0, 0, 104, 0, 0, 0, 0, 72, 0, 0, 0, 86, 38, 228, 225, 215, 95, 117, 65, 188, 160, 253, 171, 218, 9, 131, 241, 0, 0, 0, 0, 0, 0, 0, 0] }), shim_props: None, tracker_props: Some(TrackerDataBlock { block_size: 96, block_signature: 2684354563, length: 88, version: 0, machine_id: 547369977551526558338383880546838903, droid: [246641088347836073403379160464379613196, 25846492941788644465674475228989225756], droid_birth: [246641088347836073403379160464379613196, 25846492941788644465674475228989225756] }), vista_and_above_idlist_props: None } }
DEBUG \\?\C:\Users\user\AppData\Roaming\64Gram Desktop\Telegram.exe is a file. Checking \\?\C:\Users\user\AppData\Roaming\64Gram Desktop
DEBUG Checking if \\?\C:\Users\user\AppData\Roaming\64Gram Desktop is a git repository
DEBUG Transformed path to C:\Users\user\AppData\Roaming\64Gram Desktop
DEBUG Executing command `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any of the parent directories): .git
   1: `C:\Program Files\Git\cmd\git.EXE` failed: exit code: 128

Location:
   src\steps\git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Startup link: Lnk { path: Some("C:\\Users\\user\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\DS4Windows.lnk"), header: ShellLinkHeader { header_size: 76, link_clsid: 93045959704944114645041356371858166785, link_flags: HAS_LINK_TARGET_ID_LIST | HAS_LINK_INFO | HAS_RELATIVE_PATH | HAS_WORKING_DIR | HAS_ARGUMENTS | HAS_ICON_LOCATION | IS_UNICODE | HAS_EXP_ICON, file_attributes: (empty), creation_time: 133273592879706248, access_time: 133282955451197684, write_time: 133273590979517659, file_size: 566272, icon_index: 0, show_command: SW_SHOWNORMAL, hot_key: HotKeyFlags { low_byte: 0, high_byte: 0 }, reserved1: 0, reserved2: 0, reserved3: 0, created_on: Some(2023-04-30T20:14:47.970Z), modified_on: Some(2023-04-30T20:11:37.951Z), accessed_on: Some(2023-05-11T16:19:05.119Z) }, string_data: StringData { name_string: None, relative_path: Some("..\\..\\..\\..\\..\\..\\..\\..\\..\\ProgramData\\chocolatey\\lib\\ds4windows\\tools\\DS4Windows\\DS4Windows.exe"), working_dir: Some("C:\\ProgramData\\chocolatey\\lib\\ds4windows\\tools\\DS4Windows"), command_line_arguments: Some("-m"), icon_location: Some("C:/ProgramData/chocolatey/lib/ds4windows/tools/DS4Windows/DS4Windows.exe") }, link_target_id_list: LinkTargetIdList, link_info: LinkInfo { link_info_size: 129, link_info_header_size: 28, link_info_flags: Some(VOLUME_ID_AND_LOCAL_BASE_PATH), volume_id_offset: 28, local_base_path_offset: 55, common_network_relative_link_offset: 0, common_path_suffix_offset: 128, local_base_path_offset_unicode: 27, common_path_suffix_offset_unicode: 3, volume_id: None, local_base_path: Some("C:\\ProgramData\\chocolatey\\lib\\ds4windows\\tools\\DS4Windows\\DS4Windows.exe"), common_network_relative_link: None, common_path_suffix: None, local_base_path_unicode: None, common_path_suffix_unicode: None }, extra_data: ExtraData { darwin_props: None, special_folder_props: None, console_props: None, console_fe_props: None, environment_props: None, icon_environment_props: Some(IconEnvironmentDataBlock { block_size: 788, block_signature: 2684354567, target_ansi: Some([37, 83, 121, 115, 116, 101, 109, 68, 114, 105, 118, 101, 37, 47, 80, 114, 111, 103, 114, 97, 109, 68, 97, 116, 97, 47, 99, 104, 111, 99, 111, 108, 97, 116, 101, 121, 47, 108, 105, 98, 47, 100, 115, 52, 119, 105, 110, 100, 111, 119, 115, 47, 116, 111, 111, 108, 115, 47, 68, 83, 52, 87, 105, 110, 100, 111, 119, 115, 47, 68, 83, 52, 87, 105, 110, 100, 111, 119, 115, 46, 101, 120, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), target_unicode: Some([37, 0, 83, 0, 121, 0, 115, 0, 116, 0, 101, 0, 109, 0, 68, 0, 114, 0, 105, 0, 118, 0, 101, 0, 37, 0, 47, 0, 80, 0, 114, 0, 111, 0, 103, 0, 114, 0, 97, 0, 109, 0, 68, 0, 97, 0, 116, 0, 97, 0, 47, 0, 99, 0, 104, 0, 111, 0, 99, 0, 111, 0, 108, 0, 97, 0, 116, 0, 101, 0, 121, 0, 47, 0, 108, 0, 105, 0, 98, 0, 47, 0, 100, 0, 115, 0, 52, 0, 119, 0, 105, 0, 110, 0, 100, 0, 111, 0, 119, 0, 115, 0, 47, 0, 116, 0, 111, 0, 111, 0, 108, 0, 115, 0, 47, 0, 68, 0, 83, 0, 52, 0, 87, 0, 105, 0, 110, 0, 100, 0, 111, 0, 119, 0, 115, 0, 47, 0, 68, 0, 83, 0, 52, 0, 87, 0, 105, 0, 110, 0, 100, 0, 111, 0, 119, 0, 115, 0, 46, 0, 101, 0, 120, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]) }), known_folder_props: None, property_store_props: Some(PropertyStoreDataBlock { block_size: 69, block_signature: 2684354569, property_store: [57, 0, 0, 0, 49, 83, 80, 83, 177, 22, 109, 68, 173, 141, 112, 72, 167, 72, 64, 46, 164, 61, 120, 140, 29, 0, 0, 0, 104, 0, 0, 0, 0, 72, 0, 0, 0, 86, 38, 228, 225, 215, 95, 117, 65, 188, 160, 253, 171, 218, 9, 131, 241, 0, 0, 0, 0, 0, 0, 0, 0] }), shim_props: None, tracker_props: Some(TrackerDataBlock { block_size: 96, block_signature: 2684354563, length: 88, version: 0, machine_id: 547369977551526558338383880546838903, droid: [246641088347836073403379160464379613196, 25846492941788502794679964029974598042], droid_birth: [246641088347836073403379160464379613196, 25846492941788502794679964029974598042] }), vista_and_above_idlist_props: None } }
DEBUG \\?\C:\ProgramData\chocolatey\lib\ds4windows\tools\DS4Windows\DS4Windows.exe is a file. Checking \\?\C:\ProgramData\chocolatey\lib\ds4windows\tools\DS4Windows
DEBUG Checking if \\?\C:\ProgramData\chocolatey\lib\ds4windows\tools\DS4Windows is a git repository
DEBUG Transformed path to C:\ProgramData\chocolatey\lib\ds4windows\tools\DS4Windows
DEBUG Executing command `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any of the parent directories): .git
   1: `C:\Program Files\Git\cmd\git.EXE` failed: exit code: 128

Location:
   src\steps\git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Checking if \\?\C:\Users\user\Documents\PowerShell is a git repository
DEBUG Transformed path to C:\Users\user\Documents\PowerShell
DEBUG Executing command `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `C:\Program Files\Git\cmd\git.EXE rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any of the parent directories): .git
   1: `C:\Program Files\Git\cmd\git.EXE` failed: exit code: 128

Location:
   src\steps\git.rs:167

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "pip3"
DEBUG Detected "C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\python3.EXE" as "python3"
DEBUG Executing command `C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.EXE -m pip`
DEBUG Command failed: Err(
   0: Command failed: `C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.EXE -m pip`

      Stderr:
      Python
   1: `C:\Users\user\AppData\Local\Microsoft\WindowsApps\python3.EXE` failed: exit code: 9009

Location:
   src\steps\generic.rs:369

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)

── 17:27:01 - Summary ──────────────────────────────────────────────────────────
pip3: SKIPPED: pip does not exists
DEBUG Desktop notification: Topgrade finished successfully
</pre>
</details>

**Comment by SteveLauC** [comment]
So when you run `topgrade --only pip3`, Microsoft App Store was launched cause `topgrade` invoked `python3` under the hood, right?

I just give it a test in my Windows 10 VM (does the version matter?)

1. Install `Python3.11` from the Microsoft App Store
2. Check that `python`, `python3`, `pip` are invokable
3. Run `topgrade --only pip3`

```shell
C:\Users\steve\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts>.\topgrade --only pip3

── 23:01:35 - pip3 ─────────────────────────────────────────────────────────────
Requirement already satisfied: pip in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\lib\site-packages (23.1.2)

── 23:01:37 - Summary ──────────────────────────────────────────────────────────
pip3: OK
```

It seems to be fine? 

How did you get `python` installed, perhaps different ways cause different behaviors

**Comment by soredake** [comment]
>Install Python3.11 from the Microsoft App Store

I install python from winget, which only installs python binary and not python3, that's why it works for you.

**Comment by SteveLauC** [comment]
I am not familiar with the Windows environment, will `python` always be available if an actual python is installed?

On Fedora Linux, `python` is a symlink to `python3`, and `python3` is a symlink to the actual python:

```shell
$ l $(which python)
Permissions Links Size User Group Date Modified Name
lrwxrwxrwx@     1    9 root root  25 May 04:25  /usr/bin/python -> ./python3

$ l $(which python3)
Permissions Links Size User Group Date Modified Name
lrwxrwxrwx@     1   10 root root  25 May 04:21  /usr/bin/python3 -> python3.11

$ l /usr/bin/python3.11
Permissions Links Size User Group Date Modified Name
.rwxr-xr-x@     1  16k root root  25 May 04:21  /usr/bin/python3.11
```

If `python` is always available, we should probably prefer `python` and fall back to `python3` when the former is not found. 

Is there any system that still makes `python` refer to a `python2`? I recalled that macOS used to do this since `python2` is a dependency used by the macOS kernel, and it was removed in a recent release.

**Comment by SteveLauC** [comment]
Probably we should do something like:

```
if `python` is installed && is python 3:
    use binary `python`
else 
   Check `python3`
```

**Comment by soredake** [comment]
> I am not familiar with the Windows environment, will `python` always be available if an actual python is installed?

I think yes, official python installer always installs "python" binary.

> Probably we should do something like:

Or check version number (store shim don't have it)
![image](https://github.com/topgrade-rs/topgrade/assets/5204968/b2d4ad99-5fbe-4bdf-a8c9-8f08bdfff73f)

**Comment by SteveLauC** [comment]
PR filed, before the new release, you can disable `pip3` and run a customized command to update `pip3`:

```toml
# topgrade.toml
[misc]
disable = ["pip3"]

[commands]
"cust_pip3" = "python -m pip install --upgrade --user pip"
```

And run `topgrade` like this:

```shell
$ topgrade --custom-commands cust_pip3
```
