### ISSUE TITLE
Distrobox step fails

### ISSUE THREAD

**Issue by Zahrun** [topgrade-rs/topgrade#472]
## What did you expect to happen?
Distrobox step success

## What actually happened?
Distrobox step fails

## Additional Details
- Which operating system or Linux distribution are you using? Tuxedo OS 2
- How did you install Topgrade? pacstall -I topgrade-bin
- Which version are you running? 11.0.2

<details>
── 21:18:15 - Distrobox ────────────────────────────────────────────────────────
DEBUG Executing command `/usr/bin/distrobox upgrade --all`
 Upgrading apx_managed...
distrobox: Installing basic packages...
/usr/bin/apt-get
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 Upgrading debian-stable-new...
distrobox: Installing basic packages...
/usr/bin/apt-get
Hit:1 http://deb.debian.org/debian stable InRelease
Hit:2 http://deb.debian.org/debian-security stable-security InRelease
Hit:3 http://deb.debian.org/debian stable-updates InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
39 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libffi7 libpcre3 libsepol1 libssl1.1
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libcap2
The following packages will be upgraded:
  adduser debian-archive-keyring e2fsprogs init-system-helpers libacl1 libattr1 libcom-err2 libext2fs2
  libgssapi-krb5-2 libhogweed6 libidn2-0 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblz4-1
  libnettle8 libp11-kit0 libpam-modules libpam-modules-bin libpam-runtime libpcre2-8-0 libpcre3 libseccomp2
  libss2 libsystemd0 libtasn1-6 libtirpc-common libtirpc3 libudev1 libunistring2 libuuid1 libxxhash0 logsave
  lsb-base mawk mount sysvinit-utils tzdata
39 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 5892 kB of archives.
After this operation, 1034 kB disk space will be freed.
Get:1 http://deb.debian.org/debian stable/main amd64 init-system-helpers all 1.65.2 [49.8 kB]
Get:2 http://deb.debian.org/debian stable/main amd64 sysvinit-utils amd64 3.06-4 [31.0 kB]
Get:3 http://deb.debian.org/debian stable/main amd64 lsb-base all 11.6 [4584 B]
Get:4 http://deb.debian.org/debian stable/main amd64 libpam-modules-bin amd64 1.5.2-6 [75.5 kB]
Get:5 http://deb.debian.org/debian stable/main amd64 libpam-modules amd64 1.5.2-6 [291 kB]
Get:6 http://deb.debian.org/debian stable/main amd64 logsave amd64 1.47.0-2 [19.6 kB]
Get:7 http://deb.debian.org/debian stable/main amd64 libext2fs2 amd64 1.47.0-2 [205 kB]
Get:8 http://deb.debian.org/debian stable/main amd64 e2fsprogs amd64 1.47.0-2 [571 kB]
Get:9 http://deb.debian.org/debian stable/main amd64 mount amd64 2.38.1-5+b1 [134 kB]
Get:10 http://deb.debian.org/debian stable/main amd64 libpam-runtime all 1.5.2-6 [161 kB]
Get:11 http://deb.debian.org/debian stable/main amd64 adduser all 3.134 [183 kB]
Get:12 http://deb.debian.org/debian stable/main amd64 debian-archive-keyring all 2023.3 [161 kB]
Get:13 http://deb.debian.org/debian stable/main amd64 libacl1 amd64 2.3.1-3 [31.5 kB]
Get:14 http://deb.debian.org/debian stable/main amd64 libattr1 amd64 1:2.5.1-4 [22.2 kB]
Get:15 http://deb.debian.org/debian stable/main amd64 libcap2 amd64 1:2.66-4 [27.0 kB]
Get:16 http://deb.debian.org/debian stable/main amd64 libnettle8 amd64 3.8.1-2 [288 kB]
Get:17 http://deb.debian.org/debian stable/main amd64 libhogweed6 amd64 3.8.1-2 [328 kB]
Get:18 http://deb.debian.org/debian stable/main amd64 libunistring2 amd64 1.0-2 [437 kB]
Get:19 http://deb.debian.org/debian stable/main amd64 libidn2-0 amd64 2.3.3-1+b1 [124 kB]
Get:20 http://deb.debian.org/debian stable/main amd64 liblz4-1 amd64 1.9.4-1 [62.9 kB]
Get:21 http://deb.debian.org/debian stable/main amd64 libp11-kit0 amd64 0.24.1-2 [345 kB]
Get:22 http://deb.debian.org/debian stable/main amd64 libpcre2-8-0 amd64 10.42-1 [261 kB]
Get:23 http://deb.debian.org/debian stable/main amd64 libseccomp2 amd64 2.5.4-1+b3 [46.6 kB]
Get:24 http://deb.debian.org/debian stable/main amd64 libsystemd0 amd64 252.6-1 [330 kB]
Get:25 http://deb.debian.org/debian stable/main amd64 libtasn1-6 amd64 4.19.0-2 [56.6 kB]
Get:26 http://deb.debian.org/debian stable/main amd64 libudev1 amd64 252.6-1 [107 kB]
Get:27 http://deb.debian.org/debian stable/main amd64 libuuid1 amd64 2.38.1-5+b1 [28.8 kB]
Get:28 http://deb.debian.org/debian stable/main amd64 libxxhash0 amd64 0.8.1-1 [27.6 kB]
Get:29 http://deb.debian.org/debian stable/main amd64 mawk amd64 1.3.4.20200120-3.1 [119 kB]
Get:30 http://deb.debian.org/debian stable/main amd64 tzdata all 2023c-5 [296 kB]
Get:31 http://deb.debian.org/debian stable/main amd64 libcom-err2 amd64 1.47.0-2 [19.8 kB]
Get:32 http://deb.debian.org/debian stable/main amd64 libgssapi-krb5-2 amd64 1.20.1-2 [134 kB]
Get:33 http://deb.debian.org/debian stable/main amd64 libkrb5-3 amd64 1.20.1-2 [331 kB]
Get:34 http://deb.debian.org/debian stable/main amd64 libk5crypto3 amd64 1.20.1-2 [79.0 kB]
Get:35 http://deb.debian.org/debian stable/main amd64 libkrb5support0 amd64 1.20.1-2 [32.3 kB]
Get:36 http://deb.debian.org/debian stable/main amd64 libkeyutils1 amd64 1.6.3-2 [8808 B]
Get:37 http://deb.debian.org/debian stable/main amd64 libpcre3 amd64 2:8.39-15 [341 kB]
Get:38 http://deb.debian.org/debian stable/main amd64 libss2 amd64 1.47.0-2 [24.5 kB]
Get:39 http://deb.debian.org/debian stable/main amd64 libtirpc-common all 1.3.3+ds-1 [14.0 kB]
Get:40 http://deb.debian.org/debian stable/main amd64 libtirpc3 amd64 1.3.3+ds-1 [85.2 kB]
Fetched 5892 kB in 5s (1098 kB/s)     
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_TIME = "C",
        LC_MONETARY = "C",
        LC_ADDRESS = "en_AG",
        LC_TELEPHONE = "en_AG",
        LC_NAME = "en_AG",
        LC_MEASUREMENT = "C",
        LC_IDENTIFICATION = "en_AG",
        LC_NUMERIC = "C",
        LC_PAPER = "en_AG",
        LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Extracting templates from packages: 100%
Preconfiguring packages ...
Setting up usrmerge (35) ...
Warning: overlayfs detected, /usr/lib/usrmerge/convert-usrmerge will not
be run automatically. See #1008202 for details.

If this is a container then it can be converted by unpacking the image,
entering it with chroot(8), installing usrmerge and then repacking the
image again. at /usr/lib/usrmerge/convert-usrmerge line 402.
E: usrmerge failed.
dpkg: error processing package usrmerge (--configure):
 installed usrmerge package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 usrmerge
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: An error occurred
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/distrobox upgrade --all`
   1: `/usr/bin/distrobox` failed: exit status: 100

Location:
   src/steps/os/linux.rs:779

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "distrobox" failed: 
   0: Command failed: `/usr/bin/distrobox upgrade --all`
   1: `/usr/bin/distrobox` failed: exit status: 100

Location:
   src/steps/os/linux.rs:779

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
distrobox failed: 
   0: Command failed: `/usr/bin/distrobox upgrade --all`
   1: `/usr/bin/distrobox` failed: exit status: 100

Location:
   src/steps/os/linux.rs:779

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
<pre>

</pre>
</details>

**Comment by SteveLauC** [comment]
Does the error still exists if you just run `distrobox upgrade --all`

**Comment by Zahrun** [comment]
Yes

**Comment by SteveLauC** [comment]
Then I guess this is not a issue of topgrade since topgrade is simply a wrapper for these commands
