### ISSUE TITLE
Unclear what the breaking changes in 12.0.0 are

### ISSUE THREAD

**Issue by SuperSandro2000** [topgrade-rs/topgrade#475]
I just wanted to update topgrade in nixpkgs and took a look at the release page and immediately saw the headline ``Warning: Config Files may have to be edited for this release to work`` but I couldn't find what exactly needs to be edited. The changelog seems to be auto generated and I couldn't find an entry on first sight that stood out which settings need to be changed.

**Comment by SteveLauC** [comment]
It seems that we do have a config section [misc] that was not required in the previous version, so the config may need to be updated I guess

**Comment by sajeshcherian** [comment]
Do we have an example config for what goes into [misc] section?

**Comment by hannah98** [comment]
@sajeshcherian I got around the "failed to deserialize" problem by commenting out the line:
`display_preamble = true`
Maybe that config option is no longer supported.

**Comment by sajeshcherian** [comment]
@hannah98 Thank you! That did it.

**Comment by SuperSandro2000** [comment]
That's the diff between my old config and the new one. I removed sections I modified myself. I think the main change is the new [misc] at the top.

```diff
--- topgrade/topgrade.toml  2023-06-29 13:20:14.645557770 +0200
+++ topgrade.toml   2023-06-29 13:20:36.555601170 +0200
@@ -1,19 +1,8 @@
-[misc]
 # Don't ask for confirmations
 #assume_yes = true

 # Disable specific steps - same options as the command line flag
 #disable = ["system", "emacs"]

 # Ignore failures for these steps
 #ignore_failures = ["powershell"]
@@ -29,21 +18,19 @@

 # Run `sudo -v` to cache credentials at the start of the run; this avoids a
 # blocking password prompt in the middle of a possibly-unattended run.
-#pre_sudo = true
+#pre_sudo = false

 # Run inside tmux
 #run_in_tmux = true

@@ -63,26 +50,19 @@
 # Skip the preamble displayed when topgrade is run
 #display_preamble = false

+# Whether to self update (this is ignored if the binary has been built without self update support, available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
+#no_self_update = true
+
 [git]
 #max_concurrency = 5
 # Additional git repositories to pull
 #repos = [
 #    "~/src/*/",
 #    "~/.config/something"
 #]

 # Don't pull the predefined git repos
-#predefined_repos = false
+#pull_predefined = false

 # Arguments to pass Git when pulling Repositories
 #arguments = "--rebase --autostash"
```

**Comment by leoheck** [comment]
For me, things were kind of working. Removing the `[misc]` did not fix the error reported here https://github.com/topgrade-rs/topgrade/issues/481

**Comment by leoheck** [comment]
Commenting out `display_preamble = false` did not fix this too.

**Comment by adamhsparks** [comment]
I too am baffled. Suddenly it just stopped working and I can't figure out by reading any docs what to change. Removing `[misc]` doesn't fix it and I don't have a `display_preamble` that I can find.

**Comment by hannah98** [comment]
As far as I understand, having the `[misc]` block is a **requirement** now in version 12.  Commenting out `[misc]` will break, so it makes sense to me that it is not working for the people who are commenting it out.

The only thing I had to do was comment out the `display_preamble` line.  Topgrade automatically added the `[misc]` header for me, and I left it in.

**Comment by adamhsparks** [comment]
OK, the `[misc]` is/was there. Commenting out doesn't fix the issue. it still exists, so it's clearly not that causing the issue. I remain perplexed about just what I need to change.

**Comment by SteveLauC** [comment]
For guys in the thread that haven't figured out what is the root cause of the config parsing issue, would u like to paste your configuration file here and I will give it a look


We should record these breaking changes and document them well in the release page, I am sorry for this

**Comment by leoheck** [comment]
My config file is here, https://github.com/topgrade-rs/topgrade/issues/481

**Comment by SteveLauC** [comment]
> My config file is here, https://github.com/topgrade-rs/topgrade/issues/481
> 
> 
> 
> > I am sorry for this
> 
> 
> 
> It happens, we just have to understand what is going on to be able to fix it.
> 
> 

Yeah, I have given it a check:)

**Comment by leoheck** [comment]
Alright, at least I could check, the problem is in the config file.

Doing this, 
```
➜ mv .config/topgrade.toml .config/topgrade.toml.old
```

I did not have any problems.

**Comment by SteveLauC** [comment]
> Alright, at least I could check, the problem is in the config file.
> 
> 
> 
> Doing this, 
> 
> ```
> 
> ➜ mv .config/topgrade.toml .config/topgrade.toml.old
> 
> ```
> 
> 
> 
> I did not have any problems so far.
> 
> 

Have you checked my suggestions here: https://github.com/topgrade-rs/topgrade/issues/481#issuecomment-1613952050

👀

**Comment by leoheck** [comment]
Yeap, that worked. Thanks, it is fixed for me.

**Comment by DottoDev** [comment]
Release file is updated
