### ISSUE TITLE
don't upgrade pip with "--user" option on windows if "C:\Users\<user>\AppData\Roaming\Python\Python<version>\Scripts\" is not in PATH

### ISSUE THREAD

**Issue by soredake** [topgrade-rs/topgrade#480]
## I want to suggest some general feature
Topgrade should not upgrade pip with ["--user" option](https://github.com/topgrade-rs/topgrade/blob/57546a07fc73e31d18517b4be8db5ff12d71b6af/src/steps/generic.rs#L411) on windows if "C:\Users\<user>\AppData\Roaming\Python\Python<version>\Scripts\" is not in path, this will lead to another pip copy installed on Roaming path (`C:\Users\user\AppData\Roaming\Python\Python310\site-packages\pip` for example), while official installer only adds `C:\Users\user\AppData\Local\Programs\Python\Python310` and `C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts` to PATH.

Installing with user will lead to this message:
![Снимок экрана 2023-06-29 071037](https://github.com/topgrade-rs/topgrade/assets/5204968/52d38c75-2f96-4e26-8797-731a0f924dcb)

## More information
Can be tested by installing python from winget `sudo winget install -h Python.Python.3.10` and then invoking `topgrade --only 'pip3'`

**Comment by SteveLauC** [comment]
Sorry for the late reply, could you take a look at [Support for PIP3 (self update)](https://github.com/r-darwish/topgrade/pull/663), they do have a discussion on whether we should go with `--user` on Windows

**Comment by soredake** [comment]
I'll close it for now.
