### ISSUE TITLE
Brew Cask with greedy

### ISSUE THREAD

**Issue by igordrnobrega** [topgrade-rs/topgrade#489]
## I want to suggest some general feature
If possible, run Homebrew Cask with the greedy option so it installs formulas that are tagged as latest and not have a version.

```bash
── 12:33:25 - Brew - Cask ──────────────────────────────────────────────────────
==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
```

**Comment by SteveLauC** [comment]
Seems that this is already implemented: 
https://github.com/topgrade-rs/topgrade/blob/dbac121a901063cb7e5eb546ecf51fb0f30a7b3a/config.example.toml#L87C20-L87C20
