### ISSUE TITLE
Better error message when os-release file parsing goes wrong

### ISSUE THREAD

**Issue by 6543** [topgrade-rs/topgrade#499]
![image](https://github.com/topgrade-rs/topgrade/assets/24977596/2c090c7e-babd-4f32-b8ac-f9ffa3c1730a)

## Additional Details
OS: Artix Linux x86_64
Kernel: 6.4.1-zen1-1-zen
Installation: `cargo install topgrade`
Version: 12.0.0, also newest f3b1d2dfb3b38d73b14d7254a76c33359d062370 tested

**Comment by SteveLauC** [comment]
Would u like to provide the /etc/os-release file of your system?

**Comment by 6543** [comment]
well it's empty ...

**Comment by SteveLauC** [comment]
> well it's empty ...

Then this is the issue, topgrade relies on the os-release file to determine the distro

**Comment by 6543** [comment]
ah ok then I change it to an "enhancement request" that just print the hint on the crash

**Comment by 6543** [comment]
@SteveLauC ->  #511
