### ISSUE TITLE
Topgrade 12.0.1 fails on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by LordChaos73** [topgrade-rs/topgrade#512]
## Erroneous Behavior
Topgrade 12.0.1 fails on openSUSE Tumbleweed

## Expected Behavior
Topgrade should finish successfully

## Steps to reproduce
Run `topgrade`

## Additional Details
Operating System: openSUSE Tumbleweed 20230718
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.3-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 PRO 6860Z with Radeon Graphics
Memory: 30,6 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 21D2CTO1WW
System Version: ThinkPad Z13 Gen 1

- Installation
Topgrade is installed through crates.io

- Topgrade version (`topgrade -V`)
`Topgrade 12.0.1`

## Verbose Output (`topgrade -v`)
<details>
<pre>
 ✘ ericd@thinkz13  ~  topgrade -v
DEBUG Configuration at /home/ericd/.config/topgrade.toml
DEBUG No include paths found in /home/ericd/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { pre_sudo: None, sudo_command: None, git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: Some(true), notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None }), pre_commands: Some({}), post_commands: None, commands: Some({}), python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None, wsl_update_pre_release: None, wsl_update_use_web_download: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }) }
DEBUG Version: 12.0.1
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/home/ericd/.cargo/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/ericd/.config/emacs" doesn't exist
DEBUG Path "/home/ericd/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Cannot find "please"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Step "packer.nu"
DEBUG Step "System update"

── 15:29:43 - System update ────────────────────────────────────────────────────
DEBUG Executing command `/usr/bin/sudo zypper refresh`
Repository 'AnyDesk OpenSUSE - stable' is up to date.
Repository 'Visual Studio Code' is up to date.
Repository 'Main Repository (NON-OSS)' is up to date.
Repository 'Main Repository (OSS)' is up to date.
Repository 'Main Update Repository' is up to date.
Repository 'google-chrome' is up to date.
Repository 'packman' is up to date.
Repository 'Open H.264 Codec (openSUSE Tumbleweed)' is up to date.
All repositories have been refreshed.
DEBUG Executing command `/usr/bin/sudo zypper dist-upgrade ''`
Loading repository data...
Reading installed packages...
Too many arguments.
Usage:
dist-upgrade (dup) [OPTIONS]

Perform a distribution upgrade.

  Command options:

    --from <ALIAS|#|URI>    Restrict upgrade to specified repository.
    --details               Show the detailed installation summary. Default: false
    --replacefiles          Install the packages even if they replace files from other, already
                            installed, packages. Default is to treat file conflicts as an error.
                            --download-as-needed disables the fileconflict check. Default: false
-r, --repo <ALIAS|#|URI>    Work only with the specified repository.
-l, --auto-agree-with-licenses
                            Automatically say 'yes' to third party license confirmation prompt. See
                            'man zypper' for more details. Default: false
-D, --dry-run               Don't change anything, just report what would be done. A meaningful file
                            conflict check can only be performed if used together with
                            '--download-only'. Default: false
-y, --no-confirm            Don't require user interaction. Alias for the --non-interactive global
                            option. Default: false
    --download <MODE>       Set the download-install mode. Available modes: only, in-advance,
                            in-heaps, as-needed Default: DownloadDefault
-d, --download-only         Only download the packages, do not install.

  Solver options

    --debug-solver          Create a solver test case for debugging.
    --force-resolution      Force the solver to find a solution (even an aggressive one) rather than
                            asking.
-R, --no-force-resolution   Do not force the solver to find a solution, let it ask.
    --solver-focus <MODE>   Set the solvers general attitude when resolving a job.
    --recommends            Install also recommended packages in addition to the required ones.
    --no-recommends         Do not install recommended packages, only required ones.

  Expert options

    --allow-downgrade
    --no-allow-downgrade    Whether to allow downgrading installed resolvables.
    --allow-name-change
    --no-allow-name-change  Whether to allow changing the names of installed resolvables.
    --allow-arch-change
    --no-allow-arch-change  Whether to allow changing the architecture of installed resolvables.
    --allow-vendor-change
    --no-allow-vendor-change
                            Whether to allow changing the vendor of installed resolvables.

DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/sudo zypper dist-upgrade ''`
   1: `/usr/bin/sudo` failed: exit status: 3

Location:
   /home/ericd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-12.0.1/src/steps/os/linux.rs:277

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "System update" failed:
   0: Command failed: `/usr/bin/sudo zypper dist-upgrade ''`
   1: `/usr/bin/sudo` failed: exit status: 3

Location:
   /home/ericd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-12.0.1/src/steps/os/linux.rs:277

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
System update failed:
   0: Command failed: `/usr/bin/sudo zypper dist-upgrade ''`
   1: `/usr/bin/sudo` failed: exit status: 3

Location:
   /home/ericd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-12.0.1/src/steps/os/linux.rs:277

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit ✘
</pre>
</details>

**Comment by SteveLauC** [comment]
Seems related to #501🤦‍♂️, I will try to fix this tomorrow

**Comment by SteveLauC** [comment]
v12.0.2 released, please update to it.

**Comment by LordChaos73** [comment]
Thank you sir!
