### ISSUE TITLE
Error using topgrade with pacdef after the last update (12.0.1)

### ISSUE THREAD

**Issue by lennert05** [topgrade-rs/topgrade#517]
## Erroneous Behavior
After updating topgrade it thows an error when trying to sync with pacdef.

## Steps to reproduce

use version 12.0.1 in combination with pacdef for your packagemanagement and run with default config
## Possible Cause (Optional)

I think the problem happes with the addition of the last argument to add --noconfirm to the command with the yes setting:
```rust
// linux.rs line 552
 if new_version {
        ctx.run_type()
            .execute(&pacdef)
            .args(["package", "sync"])
            .arg(if ctx.config().yes(Step::System) {
                "--noconfirm"
            } else {
                ""
            })
            .status_checked()?;
```
Topgrade works with Pacdef if assume_yes is set to true so this is most likely the issue
## Additional Details
- Operation System/Version
  
Arch linux
- Installation
  
Aur package
- Topgrade version (`topgrade -V`)
12.0.1
## Verbose Output (`topgrade -v`)

<details>
<pre>
Nothing to do.
15:20:28 - pacdef
error: unexpected argument found
Usage: pacdef package sync [OPTIONS]
For more information, try '--help'.
pacdef failed:
0: Command failed: `/usr/bin/pacdef package sync ''
1: /usr/bin/pacdef` failed: exit status: 2
Location:
src/steps/os/linux.rs:557
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
</pre>
</details>

**Comment by SteveLauC** [comment]
Hi, sorry for this bug.

#513 will have it resolved, then I will push a new release

**Comment by SteveLauC** [comment]
Close as completed in #513

**Comment by SteveLauC** [comment]
v12.0.2 released, please update to it.

**Comment by lennert05** [comment]
Thank you for fixing it so quickly!
