### ISSUE TITLE
Upgrade fails on the oh-my-zsh step with the `fatal: not in a git directory` error

### ISSUE THREAD

**Issue by undrivendev** [topgrade-rs/topgrade#519]
## Erroneous Behavior

When performing a normal execution, it fails on the oh-my-zsh step with a `fatal: not in a git directory` error.

## Expected Behavior

It performs the oh-my-zsh upgrade step and continues. 

## Steps to reproduce

1. Install oh-my-zsh using the normal installation method (using curl).
2. Launch the `topgrade` command without arguments.

## Possible Cause (Optional)

To perform the oh-my-zsh upgrade the script `$HOME/.oh-my-zsh/tools/upgrade.sh` is called by topgrade.
If I `cd` into that directory and call the script with `./upgrade.sh` it works, but if I call it directly from the home directory with `./.oh-my-zsh/tools/upgrade.sh`, it fails even outside of topgrade.

## Problem persists without calling from topgrade

- [x] Yes

## Additional Details
- Operation System/Version
  
Arch Linux

- Installation
  
I installed topgrade using AUR: `yay -S topgrade-bin` .

- Topgrade version (`topgrade -V`)
12.0.2

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Executing command `zsh /home/ldv/.oh-my-zsh/tools/upgrade.sh`
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: --local can only be used inside a git repository
fatal: --local can only be used inside a git repository
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
DEBUG Command failed: Err(
   0: Command failed: `zsh /home/ldv/.oh-my-zsh/tools/upgrade.sh`
   1: `zsh` failed: exit status: 1

Location:
   src/executor.rs:181

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "oh-my-zsh" failed:
   0: Command failed: `zsh /home/ldv/.oh-my-zsh/tools/upgrade.sh`
   1: `zsh` failed: exit status: 1

Location:
   src/executor.rs:181

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
oh-my-zsh failed:
   0: Command failed: `zsh /home/ldv/.oh-my-zsh/tools/upgrade.sh`
   1: `zsh` failed: exit status: 1

Location:
   src/executor.rs:181
</pre>
</details>

**Comment by SteveLauC** [comment]
> but if I call it directly from the home directory with ./.oh-my-zsh/tools/upgrade.sh, it fails even outside of topgrade.

Then I am not sure this is an issue of topgrade

**Comment by undrivendev** [comment]
> > but if I call it directly from the home directory with ./.oh-my-zsh/tools/upgrade.sh, it fails even outside of topgrade.
> 
> Then I am not sure this is an issue of topgrade

The upgrade works when it's triggered by oh-my-zsh itself during autopdate, so I think it is.

Would it be possible to `cd` into the script directory and launch the upgrade with `./upgrade.sh`?

**Comment by SteveLauC** [comment]
> Would it be possible to cd into the script directory and launch the upgrade with ./upgrade.sh?

You can write your own custom `oh-my-zsh update` and disable the built-in one in your configuration file:

```
[misc]
disable = ["shell"]

[commands]
"Custom oh-my-zsh" = "zsh -c 'cd ~/.oh-my-zsh/tools; ./upgrade.sh'"
```

> The upgrade works when it's triggered by oh-my-zsh itself during autopdate, so I think it is.
> 
> If I cd into that directory and call the script with ./upgrade.sh it works, **but if I call it directly from the home directory with ./.oh-my-zsh/tools/upgrade.sh, it fails even outside of topgrade.**

This behavior, IMHO, is not an issue of Topgrade. I would like to encourage you to file an issue in [`oh-my-zsh`](https://github.com/ohmyzsh/ohmyzsh/issues), and paste the link here, I am willing to help debug the issue:)

**Comment by mayersj1** [comment]
This is a topgrade issue as you should be invoking 'omz update' rather than calling ~/.oh-my-zsh/tools/upgrade.sh directly.  That would resolve this issue.

**Comment by SteveLauC** [comment]
> This is a topgrade issue as you should be invoking 'omz update' rather than calling ~/.oh-my-zsh/tools/upgrade.sh directly. That would resolve this issue.

Would you like to elaborate on this? 

And, from the [FAQ](https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-manually-update-oh-my-zsh-from-a-script) of oh-my-zsh, it is recommended to call the upgrade.sh script directly.

**Comment by mayersj1** [comment]
The FAQ you point to was last edited on July 9th, 2022.  The README.md 
file in the root of the repository was last edited in May of 2023 and 
all information pertaining to updating uses ‘omz update’. Nothing 
mentioned about calling the upgrade.sh directly.

All I’m saying is that by directly calling upgrade.sh, it fails unless 
I’m sitting in the .oh-my-zsh directory.  Calling ‘omz update’ 
from anywhere is successful.

Thanks,

Steve Mayer
***@***.***

**Comment by SteveLauC** [comment]
![Screenshot from 2023-08-15 08-32-28](https://github.com/topgrade-rs/topgrade/assets/96880612/220c3333-ec48-4e45-80c7-7b39efed5bb4)


Let's reach out to the OMZ community for some help:)

**Comment by SteveLauC** [comment]
Here is what we got:
![Screenshot from 2023-08-17 09-36-57](https://github.com/topgrade-rs/topgrade/assets/96880612/237eb24a-a5f3-4048-ac2d-ebf8b1d0b5ea)

**Comment by mayersj1** [comment]
Figured this one out.  Stepping through the .oh-my-zsh/tools/upgrade.sh, I was seeing that the value for $ZSH was empty which would cause the 'cd' command  on line 15 to fail to change to the $HOME/.oh-my-zsh directory.  

Comparing this machine to one where I was not experiencing the issue, the difference was that the working machine had a .zshrc with the following line:

export ZSH="$HOME/.oh-my-zsh"

On the failing machine, the .zshrc, while setting $ZSH was not exporting it.  Added export to that line and all now works properly.

Thanks!

**Comment by undrivendev** [comment]
@mayersj1 seems to have found a workaround, thanks!
Closing.
