### ISSUE TITLE
Flatpak System Packages fails

### ISSUE THREAD

**Issue by RuiNtD** [topgrade-rs/topgrade#520]
## Erroneous Behavior
Topgrade fails on Flatpak System Packages

## Expected Behavior
Topgrade successfully updates Flatpak System Packages

## Steps to reproduce
1. `topgrade`

## Possible Cause (Optional)
I'm pretty sure `flatpak update --system` should be run with sudo.

## Problem persists without calling from topgrade
- [X] Yes

## Additional Details
- Ubuntu 22.04.2 running under WSL

- cargo install topgrade

- Topgrade 12.0.2

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Configuration at /home/ethan/.config/topgrade.toml
DEBUG No include paths found in /home/ethan/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { include: Some(Include { paths: None }), misc: Some(Misc { pre_sudo: None, sudo_command: None, git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None }), pre_commands: Some({}), post_commands: None, commands: Some({}), python: Some(Python { enable_pip_review: None, enable_pip_review_local: None, enable_pipupgrade: None, pipupgrade_arguments: None }), composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, autoremove: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, enable_winget: None, wsl_update_pre_release: None, wsl_update_use_web_download: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }) }
DEBUG Version: 12.0.2
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/home/ethan/.cargo/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/ethan/.config/emacs" doesn't exist
DEBUG Path "/home/ethan/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Cannot find "please"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Step "packer.nu"
DEBUG Step "System update"

── 16:16:00 - System update ────────────────────────────────────────────────────
DEBUG Cannot find "apt-fast"
DEBUG Cannot find "mist"
DEBUG Executing command `/usr/bin/sudo apt-get update`
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
DEBUG Executing command `/usr/bin/sudo apt-get dist-upgrade`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libldap-2.5-0 libldap-common
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
DEBUG Step "config-update"
DEBUG Step "Brew"
DEBUG Detected "/home/linuxbrew/.linuxbrew/bin/brew" as "brew"

── 16:16:04 - Brew ─────────────────────────────────────────────────────────────
DEBUG Executing command `brew update`
Already up-to-date.
DEBUG Executing command `brew upgrade --ignore-pinned --formula`
DEBUG Step "am"
DEBUG Step "appman"
DEBUG Step "deb-get"
DEBUG Step "toolbx"
DEBUG Step "Flatpak"
DEBUG Detected "/usr/bin/flatpak" as "flatpak"

── 16:16:12 - Flatpak User Packages ────────────────────────────────────────────
DEBUG Executing command `/usr/bin/flatpak update --user`
Looking for updates…
Nothing to do.

── 16:16:12 - Flatpak System Packages ──────────────────────────────────────────
DEBUG Executing command `/usr/bin/flatpak update --system`
Looking for updates…

New org.kde.dolphin permissions:
    fallback-x11

        ID                              Branch          Op          Remote          Download
 1. [✗] org.kde.dolphin.Locale          stable          u           flathub         1.0 kB / 6.1 MB
 2. [✗] org.kde.dolphin                 stable          u           flathub         1.0 kB / 30.8 MB

Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user
Warning: Flatpak system operation Deploy not allowed for user
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user
Error: Flatpak system operation Deploy not allowed for user
Updates complete.
error: There were one or more errors
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/flatpak update --system`
   1: `/usr/bin/flatpak` failed: exit status: 1

Location:
   /home/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-12.0.2/src/steps/os/linux.rs:803

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "Flatpak" failed:
   0: Command failed: `/usr/bin/flatpak update --system`
   1: `/usr/bin/flatpak` failed: exit status: 1

Location:
   /home/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-12.0.2/src/steps/os/linux.rs:803

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Flatpak failed:
   0: Command failed: `/usr/bin/flatpak update --system`
   1: `/usr/bin/flatpak` failed: exit status: 1

Location:
   /home/ethan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-12.0.2/src/steps/os/linux.rs:803

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
</pre>
</details>

**Comment by SteveLauC** [comment]
I tested on my host, `flatpak update --system` without sudo runs without issue, would you like to elaborate on why sudo is needed here?

**Comment by RuiNtD** [comment]
> would you like to elaborate on why sudo is needed here?

```
$ flatpak update --system
Looking for updates…

New org.kde.dolphin permissions:
    fallback-x11



        ID                              Branch          Op          Remote          Download
 1. [✗] org.kde.dolphin.Locale          stable          u           flathub          1.5 kB / 6.1 MB
 2. [✗] org.kde.dolphin                 stable          u           flathub         20.2 MB / 30.8 MB

Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user
Warning: Flatpak system operation Deploy not allowed for user
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user
Error: Flatpak system operation Deploy not allowed for user
Updates complete.
error: There were one or more errors

$ sudo flatpak update --system
[sudo] password for ethan:
Looking for updates…

New org.kde.dolphin permissions:
    fallback-x11



        ID                              Branch          Op          Remote          Download
 1. [✓] org.kde.dolphin.Locale          stable          u           flathub          1.5 kB / 6.1 MB
 2. [✓] org.kde.dolphin                 stable          u           flathub         20.2 MB / 30.8 MB

Updates complete.

```
