### ISSUE TITLE
Could be nice to recommend `Install-Module -Name PSWindowsUpdate` if it is not installed

### ISSUE THREAD

**Issue by HenkPoley** [topgrade-rs/topgrade#525]
Currently you see this:

```
── 08:49:31 - Windows Update ───────────────────────────────────────────────────
Running Windows Update. Check the control panel for progress.
Windows update failed:
   0: Command failed: `C:\Windows\system32\UsoClient.EXE ScanInstallWait`
   1: `C:\Windows\system32\UsoClient.EXE` failed: exit code: 0x80070057

Location:
   C:\Users\henk\.cargo\registry\src\index.crates.io-6f17d22bba15001f\topgrade-12.0.2\src\steps\os\windows.rs:189

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit

── 08:55:32 - Summary ──────────────────────────────────────────────────────────
..
Windows update: FAILED
..
```

Since UsoClient doesn't quite work on any recent version of Windows (I'm reading about failures back to 2018) it could be nice to just recommend to install the PSWindowsUpdate module, somewhere around this check: 

https://github.com/topgrade-rs/topgrade/blob/8e580457a5d0f39612e4f73edb8c281c0625ab76/src/steps/powershell.rs#L87-L93

https://github.com/topgrade-rs/topgrade/blob/8e580457a5d0f39612e4f73edb8c281c0625ab76/src/steps/powershell.rs#L95-L107

https://github.com/topgrade-rs/topgrade/blob/8e580457a5d0f39612e4f73edb8c281c0625ab76/src/steps/os/windows.rs#L174-L191

**Comment by SteveLauC** [comment]
Not a Windows user, so PR welcome, I am willing to provide help if got any questions during the implementation:)

**Comment by SteveLauC** [comment]
And, related issue: #482

**Comment by HenkPoley** [comment]
Basically if this if fails, it should print "Since UsoClient doesn't work on most up to date Windows, install the PSWindowsUpdate with `Install-Module -Name PSWindowsUpdate`.".

https://github.com/topgrade-rs/topgrade/blob/8e580457a5d0f39612e4f73edb8c281c0625ab76/src/steps/os/windows.rs#L177

**Comment by HenkPoley** [comment]
I guess you might even go ahead and run the install yourself. 

But maybe that depends on UsoClient actually working. I suppose it might work on the Enterprise targeted Windows 10 LTSC branch that is basically the 2015 version with security patches and no new features. But I think Microsoft dropped that around the release of Windows 11 (only 5 years of support).

**Comment by niStee** [comment]
> Basically if this if fails,
> 
> https://github.com/topgrade-rs/topgrade/blob/8e580457a5d0f39612e4f73edb8c281c0625ab76/src/steps/os/windows.rs#L177
> 
> it should print
> 
> ```
> Since UsoClient doesn't work on most up to date Windows, install the PSWindowsUpdate with `Install-Module -Name PSWindowsUpdate`.
> ```

@HenkPoley implemented in #671 and can be tested.

**Comment by SteveLauC** [comment]
Well, a skip reason won't be printed [unless the `--verbose` or the `--show-skipped` option is passed](https://github.com/topgrade-rs/topgrade/blob/64db67939088371e5f547b8287db030049620785/src/runner.rs#L45-L47)

**Comment by niStee** [comment]
@SteveLauC This feature request can be closed as it seems to have been implemented, right? See https://github.com/topgrade-rs/topgrade/issues/482#issuecomment-2376668884.

**Comment by SteveLauC** [comment]
Right, the feature requested in this issue has been implemented, closing.
