### ISSUE TITLE
Cannot update system when please-cli is installed

### ISSUE THREAD

**Issue by sbstn87** [topgrade-rs/topgrade#539]
topgrade does not update system when please-cli is installed:
https://github.com/TNG/please-cli

This is the output I get:

Usage: please [OPTIONS] COMMAND [ARGS]...
Try 'please --help' for help.

Error: No such command '/usr/bin/nala'.
System update failed:
0: Command failed: /home/USER/.local/bin/please /usr/bin/nala upgrade
1: /home/USER/.local/bin/please failed: exit status: 2

Location:
src/steps/os/linux.rs:481
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

---

Removing please-cli causes topgrade to work again.

**Comment by SteveLauC** [comment]
This is because there is a sudo alternative, which is also named `please`, so Topgrade thinks that [please-cli](https://github.com/TNG/please-cli) is that please sudo.

I think you need to manually specify the sudo you are gonna use in the configuration file:

```
[misc]
# Sudo command to be used
sudo_command = "sudo"
```

**Comment by sbstn87** [comment]
Thank you, this has solved the issue.

Is there a possibility to add a kind of automatic detection, which please is installed and to amend the config file appropriately?

**Comment by SteveLauC** [comment]
> Is there a possibility to add a kind of automatic detection, which please is installed 

I think we can add some checks on if the `please` binary is the sudo please or not, this is feasible

> and to amend the config file appropriately?

Probably not:(

**Comment by sbstn87** [comment]
Ok, just checking and letting user know what he can do to solve the issue would be great.

**Comment by SteveLauC** [comment]
> letting user know what he can do to solve the issue would be great.

I agree with this 

Topgrade is like a big shell script that tries to be universal and suitable for everyone, but you know, it is kinda hard to meet everyone's needs (this is why we have so many configuration entries, see `config.example.toml` in the source code), but we will try out best:)

**Comment by sbstn87** [comment]
Thank you, I appreciate your work!

**Comment by SteveLauC** [comment]
Filed a PR to depripritize the `please` sudo command, here is a build with that patch included, you won't need to manually specify the sudo command with this build:

https://github.com/SteveLauC/topgrade/releases/tag/deprioritize-please-sudo
