### ISSUE TITLE
macOS system update still runs with --dry-run

### ISSUE THREAD

**Issue by drrlvn** [topgrade-rs/topgrade#543]
## Erroneous Behavior
Running `topgrade` with `--dry-run` still runs the macOS system update instead of showing which commands would be run.

```
$ topgrade --only system --dry-run

── 11:00:21 - macOS system update ──────────────────────────────────────────────
Finding available software
No new software available.

── 11:00:31 - Summary ──────────────────────────────────────────────────────────
System upgrade: OK
```

## Expected Behavior
System update should not run, instead `topgrade` should print what it would do.

## Steps to reproduce
Use `--dry-run` flag.

## Problem persists without calling from topgrade
N/A
- [ ] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`
- [ ] Yes
- [x] No

## Additional Details
- Operation System/Version
macOS 13.5.1

- Installation
Homebrew

- Topgrade version (`topgrade -V`)
Topgrade 12.0.2

## Verbose Output (`topgrade -v`)
<details>
<pre>
$ topgrade -v --only system --dry-run
DEBUG Configuration at /Users/drrlvn/.config/topgrade.toml
DEBUG Path ~/config-files expanded to /Users/drrlvn/config-files
DEBUG Loaded configuration: ConfigFile { include: None, misc: Some(Misc { pre_sudo: None, sudo_command: None, git_repos: None, predefined_git_repos: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None }), pre_commands: None, post_commands: None, commands: None, python: None, composer: None, brew: Some(Brew { greedy_cask: None, autoremove: Some(true) }), linux: None, git: Some(Git { max_concurrency: None, arguments: None, repos: Some(["/Users/drrlvn/config-files"]), pull_predefined: None }), windows: None, npm: None, yarn: None, vim: None, firmware: None, vagrant: None, flatpak: None, distrobox: None }
DEBUG Version: 12.0.2
DEBUG OS: aarch64-apple-darwin
DEBUG Args { inner: ["topgrade", "-v", "--only", "system", "--dry-run"] }
DEBUG Binary path: Ok("/opt/homebrew/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/opt/homebrew/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/Users/drrlvn/.config/emacs" doesn't exist
DEBUG Path "/Users/drrlvn/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Cannot find "please"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Step "System upgrade"

── 11:05:32 - macOS system update ──────────────────────────────────────────────
Finding available software
DEBUG Executing command `softwareupdate --list`
DEBUG Utf8Output { status: ExitStatus(unix_wait_status(0)), stdout: "Software Update Tool\n\nFinding available software\n", stderr: "No new software available.\n" }
No new software available.
DEBUG /Users/drrlvn/.ideavimrc does not exists
DEBUG /Users/drrlvn/.intellimacs does not exists
DEBUG /Users/drrlvn/.zshrc does not exists
DEBUG Checking if /Users/drrlvn/.config/fish is a git repository
DEBUG Executing command `/opt/homebrew/bin/git rev-parse --show-toplevel`
DEBUG /Users/drrlvn/.config/openbox does not exists
DEBUG /Users/drrlvn/.config/bspwm does not exists
DEBUG /Users/drrlvn/.config/i3 does not exists
DEBUG /Users/drrlvn/.config/sway does not exists

── 11:05:35 - Summary ──────────────────────────────────────────────────────────
System upgrade: OK
DEBUG Desktop notification: Topgrade finished successfully
</pre>
</details>

**Comment by SteveLauC** [comment]
It runs `softwareupdate --list`  to check if there are any updates,  but it won't update the system even though a system update is available:

https://github.com/topgrade-rs/topgrade/blob/ce234bdb59525cc99dbdaadb1bf73cc009cb7a27/src/steps/os/macos.rs#L41-L75

See the `system_update_available()` function, `Command` is used to always execute the command

-----

Should we use `ctx.run_type().execute("softwareupdate").arg("--list").output_checked_utf8()` to really dry-run this command? In the current implementation, calling `outout_checked_with()`(`output_checked_utf8()` is implemented based on this) on a dry command would return an Error

https://github.com/topgrade-rs/topgrade/blob/ce234bdb59525cc99dbdaadb1bf73cc009cb7a27/src/executor.rs#L234-L263

If we are gonna do this, then `output_checked_with()` has to be changed as well, what should be the output of a dry-run command,  maybe something like this?

```
pub struct Output {
    // success exit status 0
    pub status: 0,
    // empty stdout
    pub stdout: Vec::new(),
    // empty stderr
    pub stderr: Vec::new(),
}
```

**Comment by SteveLauC** [comment]
I just realized that this `should_ask` variable should be defined as:

```diff
-let should_ask = !(ctx.config().yes(Step::System)) || (ctx.config().dry_run());
+let should_ask = !(ctx.config().yes(Step::System) || ctx.config().dry_run());
```

**Comment by SteveLauC** [comment]
Close as completed in #668
