### ISSUE TITLE
Dotnet may fail when trying to update tools just after it was updated from package manager

### ISSUE THREAD

**Issue by thecatcore** [topgrade-rs/topgrade#572]
## Erroneous Behavior

Dotnet step tried to update a tool "-------------------------------------" which is the separator, just after updating it from package manager.
I don't have any tools installed so it simply should not have tried running.

## Expected Behavior

Dotnet step doesn't run because I don't have any tools installed.

## Steps to reproduce

Run topgrade when a dotnet update is available through the package manager.

## Possible Cause (Optional)

When installing or updating dotnet through the package manager, it warns the user about a command running in the background to finish setuping it after the package manager is done running.
My guess is that in this case, the background command wasn't done when topgrade arrived to the dotnet step, and because of this there might have been more lines logged before the list of tools than usual (2, which are skipped in topgrade).

## Problem persists without calling from topgrade

- [ ] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Operation System/Version
  
Pop!_OS 22.04

- Installation
  
cargo/crates.io

- Topgrade version (`topgrade -V`)
12.0.2

## Verbose Output (`topgrade -v`)

<details>
<pre>

</pre>
</details>

**Comment by SteveLauC** [comment]
> Dotnet step tried to update a tool "-------------------------------------" which is the separator

Can you still reproduce it, if so, could you please give me the output of:

```sh
$ dotnet tool list --global
```

**Comment by SteveLauC** [comment]
Ah, I just installed dotnet-SDK on my host, and reproduce it:

```sh
$ topgrade --only dotnet

── 09:03:23 - Sudo ─────────────────────────────────────────────────────────────

── 09:03:23 - .NET ─────────────────────────────────────────────────────────────
/tmp/4ffdd387-40aa-4171-a469-56e9e636ccb0/restore.csproj : error NU1101: Unable to find package ---------------------. No packages exist with this id in source(s): nuget.org
Tool '---------------------' failed to update due to the following:
The tool package could not be restored.
Tool '---------------------' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
.NET failed:
   0: Failed to update .NET package ---------------------
   1: Command failed: `/usr/bin/dotnet tool update --------------------- --global`
   2: `/usr/bin/dotnet` failed: exit status: 1

Location:
   src/steps/generic.rs:716

```

**Comment by SteveLauC** [comment]
Well, this is so weird that it makes me doubt that it is a bug of dotnet or the Rust std.

In our impl, we explicitly skipped the first 2 lines of the output of  `dotnet tool list --global`:
https://github.com/topgrade-rs/topgrade/blob/18e2d3e59ca97c5f69805a9a06ea136ed23a3ee3/src/steps/generic.rs#L690-L707

And the output of `dotnet tool list --global` is still: `"Package Id      Version      Commands\n-------------------------------------\n"`, so this issue should not happen

And then I can not reproduce this bug on my host:

![Screenshot from 2023-10-12 09-31-50](https://github.com/topgrade-rs/topgrade/assets/96880612/cd7aa879-fb01-4aba-8998-2ec0a8bbc246)

**Comment by SteveLauC** [comment]
Verbose output, with no dotnet tools installed:

```sh
$ topgrade --only dotnet -v
DEBUG Version: 12.0.2
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "--only", "dotnet", "-v"] }
DEBUG Binary path: Ok("/home/steve/.cargo/bin/topgrade")
DEBUG Self Update: false
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/steve/.config/emacs" doesn't exist
DEBUG Path "/home/steve/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"

── 09:36:43 - Sudo ─────────────────────────────────────────────────────────────
DEBUG Executing command `/usr/bin/sudo -v`
DEBUG Step ".NET"
DEBUG Detected "/usr/bin/dotnet" as "dotnet"
DEBUG Executing command `/usr/bin/dotnet tool list --global`

── 09:36:44 - Summary ──────────────────────────────────────────────────────────
.NET: SKIPPED: No dotnet global tools installed
DEBUG Desktop notification: Topgrade finished successfully
 INFO perform: new
 INFO perform:write_command{command=Auth(Some(External), Some([49, 48, 48, 48]))}: new
 INFO perform:write_command{command=Auth(Some(External), Some([49, 48, 48, 48]))}: close
 INFO perform:read_command: new
 INFO perform:read_command: close
 INFO perform:write_command{command=NegotiateUnixFD}: new
 INFO perform:write_command{command=NegotiateUnixFD}: close
 INFO perform:read_command: new
 INFO perform:read_command: close
 INFO perform:write_command{command=Begin}: new
 INFO perform:write_command{command=Begin}: close
 INFO perform: close
 INFO socket reader: new
 INFO socket reader: close
```

**Comment by SteveLauC** [comment]
Well, I reproduced this because `dotnet` will print a greeting message on the first run: (kudos to @loichyan)

```sh
[root@fedora /]# dotnet tool list --global
Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.122
----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Package Id      Version      Commands
-------------------------------------
```

And from this [question](https://stackoverflow.com/q/70493706/14092446), setting `DOTNET_NOLOGO=true` should disable it:

```sh
[root@5c376aa6f0da /]# DOTNET_NOLOGO=true dotnet tool list --global
Package Id      Version      Commands
-------------------------------------
```
