### ISSUE TITLE
VSCode extensions update fail

### ISSUE THREAD

**Issue by psydvl** [topgrade-rs/topgrade#593]
## Erroneous Behavior
Update fails on extensions not available on VSCode marketplace https://marketplace.visualstudio.com/
Like self-written or distributed from different sources 

## Expected Behavior
Topgrade check that extensions available on marketplace

## Steps to reproduce
1. Install VSCode
2. Build and install sample extension from guide https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample

## Problem persists without calling from topgrade
- [x] No

## Did you run topgrade through `Remote Execution`

- [x] No

## Additional Details
- Operation System/Version
  openSUSE Tumbleweed

- Installation
  Built from repo

- Topgrade version (`topgrade -V`)
  `Topgrade 13.0.0`

Related: https://github.com/topgrade-rs/topgrade/issues/589

**Comment by SteveLauC** [comment]
Would you like to provide the output of:

```sh
$ code --list-extensions 
$ code --list-extensions --show-versions 
```

**Comment by psydvl** [comment]
I can't list extensions: some or all of them that not from marketplace are under NDA

**Comment by SteveLauC** [comment]
Ok, understand, I will try reproducing myself

**Comment by DenisLanz** [comment]
I stumbled over this issue with the shell integration from installed by [fig](https://github.com/withfig/fig) and not listed in the marketplace.

**Comment by SteveLauC** [comment]
The contributor of this step was working with upstream to get all the VS Code issues solved, but unfortunately, the maintainers of VS Code don't want the feature that will get this issue fixed: https://github.com/microsoft/vscode/issues/196155#issuecomment-1824904374
