### ISSUE TITLE
Make zinit use 'zinit update --parallel'

### ISSUE THREAD

**Issue by domglusk** [topgrade-rs/topgrade#610]
### Which tool is this about? Where is its repository?
https://github.com/zdharma-continuum/zinit
It's also at
https://github.com/psprint/Zinit-4 what's interesting is this one points to zdharma-continuum if you don't use the appimage
And a version that the dev doesn't support
https://github.com/z-shell/zi
### Which operating systems are supported by this tool?
I believe everything with zsh but I know linux is it's main support focus
### Which exact commands should Topgrade run?
zinit update --parallel
you can also do
zinit update --parallel 40 to make it faster
## I want to suggest some general feature
Topgrade should...
Make zinit use 'zinit update --parallel'

**Comment by SteveLauC** [comment]
This seems to be easy to change, PR welcome:

```sh
$ rg "zinit"
src/main.rs
289:        runner.execute(Step::Shell, "zinit", || zsh::run_zinit(&ctx))?;

src/steps/zsh.rs
114:pub fn run_zinit(ctx: &ExecutionContext) -> Result<()> {
120:        .unwrap_or_else(|_| HOME_DIR.join(".zinit"))
123:    print_separator("zinit");
125:    let cmd = format!("source {} && zinit self-update && zinit update --all", zshrc.display(),);
```
