### ISSUE TITLE
Support for `pyenv`

### ISSUE THREAD

**Issue by lucaspar** [topgrade-rs/topgrade#626]
### Which tool is this about? Where is its repository?

`pyenv` is a Python version manager. [Repo](https://github.com/pyenv/pyenv).

### Which operating systems are supported by this tool?

UNIX, MacOS ~, and Windows~

Edit: [Windows is not officially supported](https://github.com/pyenv/pyenv?tab=readme-ov-file#windows).

### What should Topgrade do to figure out if the tool needs to be invoked?

`pyenv` command exists and `$PYENV_ROOT` points to a git repository.

### Which exact commands should Topgrade run?

`pyenv update`, which updates the tool itself, its plugins, and the list of available python versions (when running `pyenv versions`).

**Comment by SteveLauC** [comment]
From their [doc](https://github.com/pyenv/pyenv?tab=readme-ov-file#upgrading-with-installer-or-git-checkout), it seems taht this `pyenv update` is only desirable when you installed it with the Pyenv-installer


And would `pyenv update` update python versions even for those virtual environments?

**Comment by lucaspar** [comment]
Looking at their [update script](https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer), it seems to basically checkout the git repos associated to pyenv. We could check whether `$PYENV_ROOT` points to a git repo, and if so, the update command should probably work.

**Comment by SteveLauC** [comment]
> Looking at their [update script](https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer), it seems to basically checkout the git repos associated to pyenv. We could check whether `$PYENV_ROOT` points to a git repo, and if so, the update command should probably work.

Sounds good to me


> And would pyenv update update python versions even for those virtual environments?

What about this? will it do such updates?

**Comment by lucaspar** [comment]
> would pyenv update update python versions even for those virtual environments?

I can't say. It seems the only other way to install it other than their script and a git repo is with brew, and I don't have access to an environment with brew today.
