### ISSUE TITLE
Homebrew no longer supports --ignore-pinned option but it is used by topgrade

### ISSUE THREAD

**Issue by ffloimair** [topgrade-rs/topgrade#628]
## Erroneous Behavior
topgrade uses "--ignore-pinned" option for homebrew but this has been deprecated.
When topgrade is executing the "Brew" step a warning is now shown:

> Warning: Calling `brew upgrade --ignore-pinned` is deprecated! There is no replacement.

## Expected Behavior
topgrade should no longer use `--ignore-pinned` option

## Steps to reproduce
just run a brew step with topgrade

## Possible Cause (Optional)
topgrade uses --ignore-pinned homebrew option which is now deprecated and should no longer be used.

## Problem persists without calling from topgrade

- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Operation System/Version
  macOS Sonoma 14.2 on intel Mac

- Installation
  
  via homebrew

- Topgrade version (`topgrade -V`)
Topgrade 13.0.0
## Verbose Output (`topgrade -v`)

<details>
<pre>
── 15:52:43 - Brew ─────────────────────────────────────────────────────────────
DEBUG Executing command `/usr/local/bin/brew update`
Already up-to-date.
DEBUG Executing command `/usr/local/bin/brew upgrade --ignore-pinned --formula`
Warning: Calling `brew upgrade --ignore-pinned` is deprecated! There is no replacement.
DEBUG Executing command `/usr/local/bin/brew cleanup`
</pre>
</details>

**Comment by lbonvarl** [comment]
also observed on Macbook Pro M1 Macos 14.2.

**Comment by SteveLauC** [comment]
Thanks for reporting

> There is no replacement.

So we should simply remove it?

**Comment by lbonvarl** [comment]
I would say yes: It is anyway the user choice to specifically not upgrade certain formulas. I use either:
Fast: "brew update; brew upgrade"
Full: "brew update; brew upgrade; brew cleanup; brew doctor"

**Comment by ffloimair** [comment]
Yes, according to the Homebrew team the option was removed as it is now the default anyway, which can be derived by looking into the commits here:
https://github.com/Homebrew/brew/commits/d0da6bdf7c77d49cf7a8f64e15c95e791900261f

**Comment by ffloimair** [comment]
So in other words removing the option will behave the same as before with the option.

**Comment by SteveLauC** [comment]
> So in other words removing the option will behave the same as before with the option.

Thanks for the explanation, I will remove it then.

**Comment by SteveLauC** [comment]
Close as completed in #629
