### ISSUE TITLE
update pip3 when pip config has set `global.break-system-packages`

### ISSUE THREAD

**Issue by ErnestDong** [topgrade-rs/topgrade#631]
## Erroneous Behavior

I tend to install base environment for general scripts, and venv for specific projects. Therefore I set pip to `global.break-system-packages` default. Therefore I can install some common packages like numpy and pandas globally conveniently. But topgrade skips pip3 since it only checks if `EXTERNALLY-MANAGED` exists (#367). But it's not the only way to allow pip to install packages globally.

my ~/.pip/pip.conf looks like

```toml
[global]
break-system-packages = true
```

you can use `pip config get global.break-system-packages` to get boolean `true` to check.

## Expected Behavior

updates pip3 when `pip config get global.break-system-packages` is true

## Steps to reproduce

add `break-system-packages = true` in pip.conf

**Comment by SteveLauC** [comment]
Hi, if I understand correctly, if you allow pip to break the system package, even though your pip is externally managed, Topgrade should still update it, right?

I am on Debian, so my pip is externally managed, then I tried the command you provided:

```sh
$ pip config get global.break-system-packages
ERROR: No such key - global.break-system-packages
```

It failed with exit code 1, does this mean that this key is false?

**Comment by ErnestDong** [comment]
Thank you for your reply. It seems `break-system-packages` is `None` when it's not set in `pip.conf` explicitly. 

> Hi, if I understand correctly, if you allow pip to break the system package, even though your pip is externally managed, Topgrade should still update it, right?
> 
> I am on Debian, so my pip is externally managed, then I tried the command you provided:
> 
> ```shell
> $ pip config get global.break-system-packages
> ERROR: No such key - global.break-system-packages
> ```
> 
> It failed with exit code 1, does this mean that this key is false?
