### ISSUE TITLE
no retry flag does not work properly

### ISSUE THREAD

**Issue by xeruf** [topgrade-rs/topgrade#641]
## Erroneous Behavior
- I run with no retry enabled (either config or `--no-retry`)
- Cancel a step with Ctrl-C
- get asked the retry prompt

## Expected Behavior
Ctrl-C cancels the whole operation because retry prompt should be off.

## Steps to reproduce
see above

**Comment by SteveLauC** [comment]
I can reproduce this, will investigate it

**Comment by SteveLauC** [comment]
Actually, this is done on purpose, when you interrupt a step, if will always ask you if you want to retry:

https://github.com/topgrade-rs/topgrade/blob/d1d8904376f12c03339c817c97fb0c4e3b62512e/src/runner.rs#L66

I think the design behind this behavior is that interruption is not an error.
