### ISSUE TITLE
topgrade attempts to upgrade custom tool called `toolbox` as `toolbx`

### ISSUE THREAD

**Issue by chimeworld** [topgrade-rs/topgrade#642]
## Erroneous Behavior

`topgrade` seems to mistake a custom utility `toolbox` with `toolbx`. I don't actually have `toolbx` installed.
```
── 22:11:46 - Toolbx ───────────────────────────────────────────────────────────
toolbx failed:
   0: Command failed: `/usr/local/bin/toolbox list --containers`

      Stderr:
      Usage:
        toolbox list [flags]

      Flags:
            --commands         Output a list of commands from tools installed on your host
            --installed        Output a list of tools installed on your host
            --all              Output a list of tools for all OS platforms
            --include-custom   Outputs all tools you have access to, including ones not reviewed by the Builder Toolbox team.
        -h, --help             help for list

      Global Flags:
        -v, --verbose   Enables info level logging
      Failed while parsing flags: unknown flag: --containers
      If you believe this is an issue with toolbox, feel free to reach out to us using this link:
      https://t.corp.amazon.com/create/templates/77a4662f-a4df-4d1a-b31b-f38e37662592
   1: `/usr/local/bin/toolbox` failed: exit status: 1
```

## Steps to reproduce

Not completely sure, but I'm assuming a `toolbox` bin in your path will cause this. Stops being an issue when `toolbox` binaries are removed from path.

## Problem persists without calling from topgrade

- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Operation System/Version
  

- Installation
  
cargo
- Topgrade version (`topgrade -V`)
Topgrade 13.0.0
## Verbose Output (`topgrade -v`)

<details>
<pre>
── 22:35:08 - Toolbx ───────────────────────────────────────────────────────────
DEBUG Executing command `/home/alsabbal/.toolbox/bin/toolbox list --containers`
DEBUG Command failed: Err(
   0: Command failed: `/home/alsabbal/.toolbox/bin/toolbox list --containers`

      Stderr:
      Usage:
        toolbox list [flags]

      Flags:
            --commands         Output a list of commands from tools installed on your host
            --installed        Output a list of tools installed on your host
            --all              Output a list of tools for all OS platforms
            --include-custom   Outputs all tools you have access to, including ones not reviewed by the Builder Toolbox team.
        -h, --help             help for list

      Global Flags:
        -v, --verbose   Enables info level logging
      Failed while parsing flags: unknown flag: --containers
      If you believe this is an issue with toolbox, feel free to reach out to us using this link:
      https://t.corp.amazon.com/create/templates/77a4662f-a4df-4d1a-b31b-f38e37662592
   1: `/home/alsabbal/.toolbox/bin/toolbox` failed: exit status: 1

Location:
   /home/alsabbal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/toolbx.rs:14)
DEBUG Step "toolbx" failed:
   0: Command failed: `/home/alsabbal/.toolbox/bin/toolbox list --containers`

      Stderr:
      Usage:
        toolbox list [flags]

      Flags:
            --commands         Output a list of commands from tools installed on your host
            --installed        Output a list of tools installed on your host
            --all              Output a list of tools for all OS platforms
            --include-custom   Outputs all tools you have access to, including ones not reviewed by the Builder Toolbox team.
        -h, --help             help for list

      Global Flags:
        -v, --verbose   Enables info level logging
      Failed while parsing flags: unknown flag: --containers
      If you believe this is an issue with toolbox, feel free to reach out to us using this link:
      https://t.corp.amazon.com/create/templates/77a4662f-a4df-4d1a-b31b-f38e37662592
   1: `/home/alsabbal/.toolbox/bin/toolbox` failed: exit status: 1

Location:
   /home/alsabbal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/toolbx.rs:14
toolbx failed:
   0: Command failed: `/home/alsabbal/.toolbox/bin/toolbox list --containers`

      Stderr:
      Usage:
        toolbox list [flags]

      Flags:
            --commands         Output a list of commands from tools installed on your host
            --installed        Output a list of tools installed on your host
            --all              Output a list of tools for all OS platforms
            --include-custom   Outputs all tools you have access to, including ones not reviewed by the Builder Toolbox team.
        -h, --help             help for list

      Global Flags:
        -v, --verbose   Enables info level logging
      Failed while parsing flags: unknown flag: --containers
      If you believe this is an issue with toolbox, feel free to reach out to us using this link:
      https://t.corp.amazon.com/create/templates/77a4662f-a4df-4d1a-b31b-f38e37662592
   1: `/home/alsabbal/.toolbox/bin/toolbox` failed: exit status: 1

Location:
   /home/alsabbal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/toolbx.rs:14
Retry? (y)es/(N)o/(s)hell/(q)uit

</pre>
</details>

**Comment by SteveLauC** [comment]
From the log, Topgrade actually involved the toolbox command rather than toolbx, it is just the step name that is called toolbx.

The toolbox command that Topgrade tries to involve is containers/toolbox, what is the command installed on your host?

Currently Topgrade cannot handle such a collision, so I would recommend you to disable the toolbx step for now.

**Comment by SteveLauC** [comment]
But I am indeed that sure why this step is called toobx (it was added before I actually maintained this tool), maybe it is a typo.

**Comment by DottoDev** [comment]
Just a Quick Note while having a short pause from studying, thr runnet is cooler toolbx because the name of the tool, not the binary, is called toolbx.

https://containertoolbx.org/

**Comment by chimeworld** [comment]
Yeah that seems to be current. So can I close this issue?

Side note: instead of ignoring the command for Toolbx, can I change the command? Wouldn't mind updating my custom `toolbox`. I'm sure this is in the docs somewhere...

**Comment by SteveLauC** [comment]
> thr runnet is cooler toolbx because the name of the tool, not the binary, is called toolbx.

Then it makes sense.

>  instead of ignoring the command for Toolbx, can I change the command? Wouldn't mind updating my custom toolbox. I'm sure this is in the docs somewhere...

You cannot modify the built-in steps unless you tweak the code, but you can [write your custom step](https://github.com/topgrade-rs/topgrade/blob/78dc567226be38491dad23c4de42ed841bc46bef/config.example.toml#L89) and disable the built-in one.

```toml
[misc]
disable = ["toolbx"]

[commands]
toolbox = "echo updating my toolbox"
```
