### ISSUE TITLE
Support `pkg_*` on OpenBSD

### ISSUE THREAD

**Issue by Izder456** [topgrade-rs/topgrade#649]
Could `pkg_*` support be implemented on OpenBSD targets?

rust, from OpenBSD ports, is version froze at stable, so if this project targets any rust-nightly features, we would need some build-time checking for that.

Right now, I should try looking into getting it to compile first.

[faq15](https://www.openbsd.org/faq/faq15.html) has information on how to use `pkg_*` on OpenBSD.

I would be open to implementing support for this when I get the chance to. I use this program a lot on Debian machines, it would be nice to have this on my personal daily driver.

**Comment by SteveLauC** [comment]
Hi, I am very willing to have these BSDs supported!

But, I am not quite sure I understand this issue:

> rust, from OpenBSD ports, is version froze at stable, so if this project targets any rust-nightly features, we would need some build-time checking for that.

Topgrade currently needs a stable toolchain higher than 1.65, if I remeber correctly, we don't have any features that need a nightly toolchain.

> [faq15](https://www.openbsd.org/faq/faq15.html) has information on how to use pkg_* on OpenBSD.

Do you mean packaging Topgrade through the package manager of OpenBSD?

**Comment by Izder456** [comment]
> Topgrade currently needs a stable toolchain higher than 1.65, if I remeber correctly, we don't have any features that need a nightly toolchain.

the rust included in OpenBSD's ports tree is version froze at release every 6 months iirc. it targets stable rust. since openbsd isn't a supported platform by rust technically, we are stuck with the rust included in the ports.

> Do you mean packaging Topgrade through the package manager of OpenBSD?

no- i was just linking documentation that may be relevant when adding support for the `pkg_*` tools from OpemBSD.

**Comment by SteveLauC** [comment]
> the rust included in OpenBSD's ports tree is version froze at release every 6 months iirc. it targets stable rust. since openbsd isn't a supported platform by rust technically

Yes, OpenBSD is a tier 3, and thus Topgrade users on OpenBSD have to build it from source

> Right now, I should try looking into getting it to compile first.

It seems that [Rust 1.75 is shipped in OpenBSD](https://openports.pl/path/lang/rust), so you should be able to build Topgrade without any issues.

**Comment by Izder456** [comment]
Turns out there already was a `Step` for openbsd in `src/os/openbsd.rs` but it fails to build with `E0599`

my PR #707 should fix the issue.

Thanks for your patience.

:)

OK?

**Comment by Izder456** [comment]
Yes- it should be. 

Again- thanks for you patience with me.

OK to close?
