### ISSUE TITLE
Binary release archive topgrade-10.0.0-x86_64-linux-gnu.tar.gz contains uneccessary directories target/x86_64-unknown-linux-gnu/release

### ISSUE THREAD

**Issue by klausi** [topgrade-rs/topgrade#65]
## What did you expect to happen?
When I download and extract https://github.com/topgrade-rs/topgrade/releases/download/v10.0.0/topgrade-10.0.0-x86_64-linux-gnu.tar.gz I should directly have the topgrade binary without any subfolders.

## What actually happened?
When I extract topgrade-10.0.0-x86_64-linux-gnu.tar.gz then I have the directory structure `target/x86_64-unknown-linux-gnu/release/topgrade`.

Can you remove all the subdirectories so that the topgrade binary is in the root of the archive?

**Comment by DottoDev** [comment]
Upps, jup, will fix that
