### ISSUE TITLE
Support wildcards in ignored_containers

### ISSUE THREAD

**Issue by mortenlj** [topgrade-rs/topgrade#653]
When ignoring containers to pull, it would be useful to be able to use wildcards.

When you use docker for development, you often end up with loads of locally built images with various tags.
These will never be possible to pull, and you wouldn't want to either, because they represent your local state.

While the new feature in v14 allows ignoring specific image tags, often it would be more effective to ignore large sets using wildcards. That way the image would be ignored even if I decide to tag it with a slug describing the current branch or time of day.

## More information
I'm not sure how I would test a side branch of topgrade, but I might be able to work on a PR.

If I were to tackle it, I think I would base the approach on [Globset](https://docs.rs/globset/latest/globset/), where the values in the config are interpreted as globs instead of doing equality matching. It would be backwards compatible with any currently configured values.

**Comment by SteveLauC** [comment]
Implemented in #666, cc folks who are also interested in this @CharlesChiuGit @dannysteenman
