### ISSUE TITLE
topgrade 14.0.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [topgrade-rs/topgrade#655]
👋 trying to build the latest release, but run into some regression test failure. The error log is as below:

<details>
<summary>regression test failure</summary>

```
==> /opt/homebrew/Cellar/topgrade/14.0.0/bin/topgrade -n --only brew_formula
―― 11:00:27 - Topgrade 14.0.0 Breaking Changes ――
1. In 13.0.0, we introduced a new feature, pushing git repos, now this feature
   has been removed as some users are not satisfied with it.

   For configuration entries, the following ones are gone:

   
   [git]
   pull_only_repos = []
   push_only_repos = []
   pull_arguments = ""
   push_arguments = ""



Confirmed? (y)es/(N)oError:
   0: Not a terminal

Location:
   src/main.rs:143
/opt/homebrew/Library/Homebrew/ignorable.rb:29:in `block in raise'
Minitest::Assertion: Expected: 0
  Actual: 1
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/7606266278/job/20711857326?pr=160588
relates to Homebrew/homebrew-core#160588

**Comment by SteveLauC** [comment]
Thanks for helping package Topgrade to homebrew!

That prompt indeed needs an terminal, maybe I should skip it when it is executed without the terminal, e.g., in the CI test environment

**Comment by chenrui333** [comment]
> That prompt indeed needs an terminal, maybe I should skip it when it is executed without the terminal, e.g., in the CI test environment

can we add some environment option for it?

**Comment by SteveLauC** [comment]
Are the tests used by brew human-written, i.e., can be changed by us? From the log, the answer seems to be yes, brew tries to get the version number and execute the homebrew_formula step, and do some assertions on the output.

From the stacktrace, I see a method called with_env, does this mean that we can set a environment variable before running the test? If so, maybe I can add a environment variable to make the breaking changes notification optional

**Comment by chenrui333** [comment]
> From the stacktrace, I see a method called with_env, does this mean that we can set a environment variable before running the test? If so, maybe I can add a environment variable to make the breaking changes notification optional

yeah, that is totally doable, you can do it with `ENV["XXX"]  = "XXX"` in the `test` block.

**Comment by chenrui333** [comment]
@SteveLauC what environment variable should I try on?

**Comment by SteveLauC** [comment]
> @SteveLauC what environment variable should I try on?

I will implement this soon:)

**Comment by SteveLauC** [comment]
Hi, I just implemented this feature in #659, we can skip that notification now with:

```sh
$ TOPGRADE_SKIP_BRKC_SKIP=true topgrade
```

Should I release a new version of Toprade (say v14.0.1), or you can just release v14.0.0 with a newer commit

**Comment by chenrui333** [comment]
yeah, new release is better, but I can push some build patch to test that PR. Thanks for the quick turnaround. :)

**Comment by chenrui333** [comment]
Works fine for me, I can ship either in 14.0.0 or 14.0.1 :)

**Comment by SteveLauC** [comment]
> new release is better

Let me give it a new release!

**Comment by chenrui333** [comment]
no worries at all, since we have fixed and shipped the change, I am gonna close this issue for now. Appreciate the quick turnaround! ❤️

**Comment by SteveLauC** [comment]
v14.0.1 released:)
