### ISSUE TITLE
Transfer the ownership of the original crates.io package

### ISSUE THREAD

**Issue by r-darwish** [topgrade-rs/topgrade#66]
I would like to transfer the ownership of the original create.io package. @DottoDev what is your username in creates.io?

**Comment by DottoDev** [comment]
It's Thomas Schönauer

**Comment by r-darwish** [comment]
I just sent you an invite. Can you please confirm that you accepted?

**Comment by DottoDev** [comment]
I have accepted it.
I'm currently thinking about if topgrade-rs on crates.io should be abandoned and just topgrade should be updated, both should get updatet or only topgrade-rs.
Opinions are welcome

**Comment by vedkothavade** [comment]
> I have accepted it. I'm currently thinking about if topgrade-rs on crates.io should be abandoned and just topgrade should be updated, both should get updatet or only topgrade-rs. Opinions are welcome

I'd push a version to the "topgrade-rs" crate which notifies users to switch to the normal "topgrade," and then continue updating the more popular topgrade crate.

**Comment by vedkothavade** [comment]
Also, @r-darwish, you might want to change the README of your repo to reflect that the crates.io package is no longer under your control either.

**Comment by DottoDev** [comment]
> > I have accepted it. I'm currently thinking about if topgrade-rs on crates.io should be abandoned and just topgrade should be updated, both should get updatet or only topgrade-rs. Opinions are welcome
> 
> 
> 
> I'd push a version to the "topgrade-rs" crate which notifies users to switch to the normal "topgrade," maybe just by printing "INFO: topgrade-rs has been superseded by topgrade. Please install topgrade to continue recieving updates," and then continue updating the more popular topgrade crate.

Will do that
