### ISSUE TITLE
[CI] Build and Test arm64 natively

### ISSUE THREAD

**Issue by thecatcore** [topgrade-rs/topgrade#678]
[Github just announced the public release of a new workflow runner for arm64 macos a few days ago.](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)

It can be used to build and test arm64/aarch64 binaries natively, for macos and probably other systems using images on top of it.

**Comment by SteveLauC** [comment]
#680 enables us to run checks on macOS aarch64, for release, I will do it later.
