### ISSUE TITLE
Support for `waydroid`'s image upgrade

### ISSUE THREAD

**Issue by w568w** [topgrade-rs/topgrade#684]
### Which tool is this about? Where is its repository?
[Waydroid](https://waydro.id/) is a container-based tool to boot a full Android system on a regular GNU/Linux system (i.e. an Android simulator). It uses Linux namespaces (user, pid, uts, net, mount, ipc) and provides Android applications on any GNU/Linux-based platform.

The Android runtime environment ships with a minimal customized Android system image based on [LineageOS](https://lineageos.org/), which receives frequent (weekly) upgrades. 

[Repository](https://github.com/waydroid/waydroid/).

### Which operating systems are supported by this tool?

Any x86_64 GNU/Linux with Wayland session and kernel module `binder_linux`.

### What should Topgrade do to figure out if the tool needs to be invoked?
`waydroid` executable exists and `$ waydroid status` exits successfully.

### Which exact commands should Topgrade run?
`# waydroid upgrade`, which stops running containers, downloads new images (if any) and extracts them.

Since it will kill any running containers without confirmation, one can use `$ waydroid status` to determine whether the container is running first, and allow user to save their work.

Running:

```
$ waydroid status
Session:        RUNNING
Container:      RUNNING
Vendor type:    MAINLINE
IP address:     192.168.240.112
Session user:   w568w(1000)
Wayland display:        wayland-0
```

Stopped:

```
$ waydroid status 
Session:        STOPPED
Vendor type:    MAINLINE
```

**Comment by SteveLauC** [comment]
> What should Topgrade do to figure out if the tool needs to be invoked?
>
>waydroid executable exists and $ waydroid status exits successfully.

> Which operating systems are supported by this tool?
>
> Any x86_64 GNU/Linux with Wayland session and kernel module binder_linux.

Looks like we should also check:

1. This Linux system runs Wayland
2. The kernel module `binder_linux` exists

besides checking `waydroid` and `waydroid status`?

-----

And, just to confirm, for that kernel module, should we check if it exists or is **loaded** or not?

-----

How many containers will this tool run? Seems that there will only be 1 container from your output.

----

I am thinking about implementing this step with the following procedure:

1. Check whether the conditions are satisfied:
    1. Linux running Wayland with kernel module `binder_linux` installed (or loaded)
    2. The command `waydroid` is installed

2. Check if the container is running through `waydroid status` (the `Session` field)
3. If the container is running, ask the user if it is allowed to continue the update (which would stop the running container)
     > If `assume_yes` is true, then we will directly proceed to the next update step.
4. Update it with `waydroid update`

**Comment by w568w** [comment]
> Looks like we should also check:
> 
> 1. This Linux system runs Wayland
> 
> 2. The kernel module `binder_linux` exists
> 
> 
> besides checking `waydroid` and `waydroid status`?
>
> And, just to confirm, for that kernel module, should we check if it exists or is **loaded** or not?

Unfortunately, there is no portable way to do (1). You can list all sessions by running `$ loginctl` and check their types with `$ loginctl show-session <SESSION_ID> --property=Type` on a system with `systemd-logind`, but this does not necessarily mean that Waydroid is installed and running on a Wayland session; and there is no portable way to do (2) for similar reasons.

However, these two points are prerequisites for installing Waydroid (not for running `$ waydroid upgrade`, in case I did not convey this clearly). If they are not met, a Waydroid session cannot appear on the system at all. So **I do not think topgrade needs to check them**.

> How many containers will this tool run? Seems that there will only be 1 container from your output.

Currently they support only one running container. [Here](https://github.com/waydroid/waydroid/blob/f8d4bd2dc78fab8b6f9e837b65869f8fa112f7c4/tools/actions/status.py#L9-L25) is how the output of `$ waydroid status` is built.
