### ISSUE TITLE
tlmgr failing?

### ISSUE THREAD

**Issue by mouse07410** [topgrade-rs/topgrade#7]
## What did you expect to happen?

`tlmgr` to succeed updating all the TeXLive stuff upon invocation.

## What actually happened?

```
―― 07:28:34 - TeX Live package manager ―――――――――――――――――――――――――――――――――――――――――
Enter PIN for 'Certificate For PIV Authentication xxxxxxxx': 

/Library/TeX/texbin/tlmgr: signature verification error of /usr/local/texlive/2022/tlpkg/texlive.tlpdb.main.2fdb20874d4fe1a3267a99dbbf353926 from https://mirror.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb: cryptographic signature verification of
  /tmp/BQmzF5UvJT/6ox4ZGeQ7I
against
  https://mirror.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb.sha512.asc
failed. Output was:
gpg: Signature made Thu Sep 29 19:53:42 2022 EDT
gpg:                using RSA key 4CE1877E19438C70
gpg: BAD signature from "TeX Live Distribution <tex-live@tug.org>" [ultimate]

Please try from a different mirror and/or wait a few minutes
and try again; usually this is because of transient updates.
If problems persist, feel free to report to texlive@tug.org.
```

Occasionally (only within `tlmgr` - other stuff gets updated OK), a couple of packages would fail to update. And all the packages seem to take a long time to download, as if network had a problem - except that other apps don't seem to notice.

## Additional Details
- **OS?** MacOS Monterey 12.6
- **How did you install Topgrade?** `cargo install topgrade` (don't want to use Macports version)
- **Which version are you running?** 9.0.1

<details>

<pre>

</pre>
</details>

**Comment by mouse07410** [comment]
In the process of checking.

In the meanwhile, are there any plans to replace the now-unmaintained "topgrade" with this one?

**Comment by DottoDev** [comment]
The Crates.io crate is difficult to get access to because r-darwish is still the owner of it and I don't now if he want to give us crates.io access in the near future.

Till that's done I'll probably publish it as topgrade-rs or something like that on crates.io.

And for packages we will have to reach out to the maintainers.

**Comment by mouse07410** [comment]
Offhand, could it be that "topgrade" is not passing (or blocking, somehow) the env vars to the invoked apps, `tlmgr` in this case? Like `http_proxy`? Because the symptoms I'm observing suggest a problem with the network access, explainable if the app does not know the location the pricy.

**Comment by DottoDev** [comment]
As long as the error is a Bad Signature error it's a problem with the tlmgr servers certificates. This is normally because tlmgr can not verify the servers identity. You could check if the problem persists when changing the repo server of tlmgr.

**Comment by mouse07410** [comment]
Looks like `tlmgr` invokes `curl`. I'll play with `.curlrc` and report any changes.

**Comment by mouse07410** [comment]
Looks like straightening out the `~/.curlrc` improved the situation. Closing this issue, for now at least. Thanks!
