### ISSUE TITLE
Support OpenBSD's `pkg_*` for cleaning orphaned packages.

### ISSUE THREAD

**Issue by Izder456** [topgrade-rs/topgrade#708]
## What
I want to suggest a new clean step for OpenBSD.
### Which tool is this about?
OpenBSD's `pkg_*`
### Where is its repository?
*not applicable*
### Which operating systems are supported by this tool?
OpenBSD
### What should Topgrade do to figure out if the tool needs to be invoked?
- check if System Type is OpenBSD
- check if `-c` switch is flipped or `topgrade.toml` has autoclean enabled.
### Which exact commands should Topgrade run?
`pkg_delete -a`

I can self-assign here if possible- I would be willing to implement this functionality myself when I get the chance.

**Comment by SteveLauC** [comment]
> I can self-assign here if possible- I would be willing to implement this functionality myself when I get the chance.

Please go ahead ❤️

**Comment by Izder456** [comment]
*necrobump* ||sorry||

working on now.

adding `-c` as well, which cleans config files as well, like `apt purge`:

from the (manpage)[https://man.openbsd.org/pkg_delete]:
```man
-c Delete extra configuration file, mentioned as
   @extra file
   in the packing-list.
```
