### ISSUE TITLE
Distrobox

### ISSUE THREAD

**Issue by LeSnake04** [topgrade-rs/topgrade#72]
### Which tool is this about? Where is its repository?
Distrobox is a tool to integrate other linux distros into your system. 

https://github.com/89luca89/distrobox
### Which operating systems are supported by this tool?
Most linux distros
![image](https://user-images.githubusercontent.com/47243761/197888729-2273cb5c-6c26-461b-9938-fd9c009ab983.png)
### What should Topgrade do to figure out if the tool needs to be invoked?
If its installed.
### Which exact commands should Topgrade run?
distrobox upgrade -a

## More information

I can add it (Assuming there are no extra steps)

**Comment by LeSnake04** [comment]
I will start working on it as soon as I get your OK.

**Comment by LeSnake04** [comment]
I would implement it similar to https://github.com/topgrade-rs/topgrade/commit/3f7614b8855c849843965bec92ae9b8719e8b0c1

**Comment by DottoDev** [comment]
> I will start working on it as soon as I get your OK.

Go on. Have fun coding

**Comment by LeSnake04** [comment]
I decided to use os/linux.rs instead since there is no mac support (yet).

#76
