### ISSUE TITLE
VSCode installed, but winget can't execute `code --version`

### ISSUE THREAD

**Issue by derkrasseleo** [topgrade-rs/topgrade#720]
## Erroneous Behavior
```
Visual Studio Code extensions failed:
   0: Failed to execute `code --version`
   1: program not found
```

## Expected Behavior
program found

## Steps to reproduce
run `topgrade` in powershell on windows 11

## Possible Cause (Optional)
I can only say that there's no differnce if I'm running topgrade in administrative shell or not.

## Problem persists without calling from topgrade
- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Operation System/Version
  Windows 11 Home Version 10.0.22631 Build 22631

- Installation
   winget

- Topgrade version (`topgrade -V`)
   14.0.1
## Verbose Output (`topgrade -v`)
<details>
<pre>
DEBUG Step "Visual Studio Code extensions"
DEBUG Detected "C:\\Users\\leoch\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code.CMD" as "code"
DEBUG Executing command `code --version`
DEBUG Step "Visual Studio Code extensions" failed:
   0: Failed to execute `code --version`
   1: program not found

Location:
   src\steps\generic.rs:352
Visual Studio Code extensions failed:
   0: Failed to execute `code --version`
   1: program not found

Location:
   src\steps\generic.rs:352
Retry? (y)es/(N)o/(s)hell/(q)uit
</pre>
</details>

**Comment by SteveLauC** [comment]
What is the output of `code --version` if you directly do it in your shell?

**Comment by derkrasseleo** [comment]
`PS C:\Users\leoch> code --version
1.86.2
903b1e9d8990623e3d7da1df3d33db3e42d80eda
x64`

**Comment by derkrasseleo** [comment]
Does topgrade expect a special PATH variable for `code` ?

**Comment by SteveLauC** [comment]
> Does topgrade expect a special PATH variable for code ?

No

> DEBUG Detected "C:\\Users\\leoch\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code.CMD" as "code"

From the log, Topgrade has successfully found the code binary, I have no idea why it didn't work in the Topgrade code...

**Comment by SteveLauC** [comment]
> Mine is a user variable that points to C:\Users\leoch\AppData\Local\Programs\Microsoft VS Code\bin

Interesting, perhaps the `std::process::Command` won't automatically dereference links on Windows?

**Comment by derkrasseleo** [comment]
No clue, sorry, I don't have any experience with rust

**Comment by loehden** [comment]
I got exactly the same issue, no matter whether I run it from powershell or from cmd.

### Verbose Output (topgrade -v)

---

<details>

```
DEBUG Step "Visual Studio Code extensions"
DEBUG Detected "C:\\Program Files\\Microsoft VS Code\\bin\\code.CMD" as "code"
DEBUG Executing command `code --version`
DEBUG Step "Visual Studio Code extensions" failed:
   0: Failed to execute `code --version`
   1: program not found

Location:
   C:\Users\Xx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\topgrade-14.0.1\src\steps\generic.rs:352
Visual Studio Code extensions failed:
   0: Failed to execute `code --version`
   1: program not found

Location:
   C:\Users\Xx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\topgrade-14.0.1\src\steps\generic.rs:352
```

**Comment by Lim-Dul** [comment]
I have the exact same issue on:
Edition	Windows 11 Pro
Version	23H2
OS build	22631.3235

VSCode Version 1.87.1

Topgrade Version 14.0.1

The additional information I can perhaps provide is that the issues started with topgrade 14.0.1 without any changes to my setup. The issue also occurs on a second machine of mine which is configured quite differently to the one I'm posting this from.

I have redownloaded Topgrade 13.0.0 and `topgrade --only vscode` finished just fine.
In either case just typing in `code --version` in the console runs just fine. Something broke between topgrade v13 and v14...

**Comment by SteveLauC** [comment]
> The additional information I can perhaps provide is that the issues started with topgrade 14.0.1 without any changes to my setup. The issue also occurs on a second machine of mine which is configured quite differently to the one I'm posting this from.

Thanks for this info!

----

My thought on this issue is that it should be something specific to Windows, I have no idea why we can not execute `code --version` in Rust code...

How did you guys get your VSCode installed, maybe I will set up a Windows machine to give it a test.

**Comment by Lim-Dul** [comment]
On both machines VSCode has been installed through chocolatey but the installation path is the default one. Unlike scoop or something no shims seem to be created, just the official installer downloaded and executed resulting in:
```
❯ Get-Command code

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     code.cmd                                           0.0.0.0    C:\Program Files\Microsoft VS Code\bin\code.cmd
```
One observation is that this is a batch script, not an executable with the contents of:
```
@echo off
setlocal
set VSCODE_DEV=
set ELECTRON_RUN_AS_NODE=1
"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" %*
endlocal
```
But this doesn't explain why `code --version` runs OK and why it works in topgrade v13. Maybe the paths somehow changed between VSCode versions as you'll note that code.exe is actually located one directory above what the `code` command (and correspondingly code.cmd) actually executes.

**Comment by yuma140902** [comment]
Hello. I think it may be related to https://github.com/rust-lang/rust/issues/37519

**Comment by SteveLauC** [comment]
Ok, I was able to reproduce this issue on my Windows VM:

* Windows 10 home edition
* VS Code 1.87.2 (downloaded from browser)
* Rust 1.77

```sh
PS C:\Users\steve\Desktop\rust> get-command code

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     code.cmd                                           0.0.0.0    C:\Users\steve\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd


PS C:\Users\steve\Desktop\rust> get-content 'C:\Users\steve\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd'
@echo off
setlocal
set VSCODE_DEV=
set ELECTRON_RUN_AS_NODE=1
"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" %*
endlocal
PS C:\Users\steve\Desktop\rust>
```
