### ISSUE TITLE
expanded glob git repo directory cache needs to be invalidated I think

### ISSUE THREAD

**Issue by float3** [topgrade-rs/topgrade#728]
## Erroneous Behavior
after getting dropped to shell from git repos pull step failing and deleting the failing repo topgrade has cached the repos from the glob in config

## Expected Behavior
topgrade should invalidate the github repo directories cache if dropping to shell or retrying on repo pull step

## Steps to reproduce
1. have glob repos in your config example `~/Projects/*` 
2. have an invalid (e.g deleted) remote in a git repo in side of said folder
3. run topgrade
4. drop to shell
5. delete repo with invalid remote
6. exit shell -> topgrade fails again but this time with `OS error directory not found`

## Possible Cause (Optional)
need to invalidate repo cache in if dropped to shell or retrying (directories might have change since last run)

## Problem persists without calling from topgrade
not applicable

## Did you run topgrade through `Remote Execution`
not applicable

## Configuration file (Optional)

```toml
[git]
max_concurrency = 10
repos = ["~/Projects/*/"]
```

## Additional Details
- Operation System/Version
NixOS 24.05pre590113.1536926ef562 (Uakari)

- Installation
NixPkgs

- Topgrade version (`topgrade -V`)
Topgrade 14.0.1
## Verbose Output (`topgrade -v`)

<details>
<pre>

</pre>
</details>

**Comment by SteveLauC** [comment]
Can reproduce this on my host
