### ISSUE TITLE
Getting deprecation warning when running vscode extension updates

### ISSUE THREAD

**Issue by dannysteenman** [topgrade-rs/topgrade#730]
## Erroneous Behavior
Running Visual Studio Code extensions updates causes the following warning:

```
── 08:46:18 - Visual Studio Code extensions ────────────────────────────────────
Updating extensions: ms-python.vscode-pylance
(node:26728) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'ms-python.vscode-pylance' v2024.2.3 was successfully updated.
```

## Expected Behavior

No warning messages during updates

## Steps to reproduce

Have an outdated vscode extension and then run the topgrade command

## Possible Cause (Optional)

It's using an old method of buffer which is deprecated: https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues

## Additional Details
 - OS: macOS 14.3.1 23D60 arm64
 - Shell: zsh 5.9
 - Topgrade 14.0.1
 - Nodejs v20.11.1

- Installation
  Homebrew

- Topgrade version (`topgrade -V`)
- Topgrade 14.0.1

## Verbose Output (`topgrade -v`)

<details>
<pre>

</pre>
</details>

**Comment by SteveLauC** [comment]
Can you reproduce this with:

```sh
$ code --update-extensions
```

**Comment by SteveLauC** [comment]
Yeah, I think this is an issue of VSCode rather than Topgrade, Topgrade is simply a wrapper that tries to execute `code --update-extensions`

**Comment by dannysteenman** [comment]
yeah I thought so, let's close this issue. thanks for the quick response!
