### ISSUE TITLE
Mamba update fails with `Command failed: mamba config --show auto_activate_base`

### ISSUE THREAD

**Issue by Quba1** [topgrade-rs/topgrade#731]
## Erroneous Behavior

mamba update fails with:

```sh
mamba failed: 
   0: Command failed: `mamba config --show auto_activate_base`

      Stdout:
      Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
   1: `mamba` failed: exit status: 1
```

Interestingly, everything worked just fine yesterday and today it stopped working on two similarly configured machines (one with Pop_OS!22.04 and one with Ubuntu LTS 22.04)

## Expected Behavior

mamba updates successfully

## Steps to reproduce

run `topgrade --yes`

## Problem persists without calling from topgrade

- [x] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Operation System/Version
  Pop_OS!22.04

  mamba installed with miniforge

  mamba 1.5.7

  conda 24.1.2

- Installation
   
  `cargo install topgrade`

- Topgrade version (`topgrade -V`) 14.0.1

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Step "mamba"
DEBUG Detected "/home/xxx/miniforge3/condabin/mamba" as "mamba"
DEBUG Executing command `mamba config --show auto_activate_base`
DEBUG Command failed: Err(
   0: Command failed: `mamba config --show auto_activate_base`

      Stdout:
      Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
   1: `mamba` failed: exit status: 1

Location:
   /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-14.0.1/src/steps/generic.rs:419)
DEBUG Step "mamba" failed: 
   0: Command failed: `mamba config --show auto_activate_base`

      Stdout:
      Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
   1: `mamba` failed: exit status: 1

Location:
   /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-14.0.1/src/steps/generic.rs:419
mamba failed: 
   0: Command failed: `mamba config --show auto_activate_base`

      Stdout:
      Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
   1: `mamba` failed: exit status: 1

Location:
   /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-14.0.1/src/steps/generic.rs:419
</pre>
</details>

**Comment by SteveLauC** [comment]
Seems that the `config` sub-command is no longer supported in mamba 1.5.7?

**Comment by Quba1** [comment]
There's nothing in the [changelog](https://github.com/mamba-org/mamba/compare/micromamba-1.5.6...micromamba-1.5.7) that would suggest so, but it's apparently it's the case

**Comment by SteveLauC** [comment]
A similar issue I found while searching:

https://github.com/mamba-org/mamba/issues/3033

It is related to the underlying `conda` command, so I guess this one is similar. 

I encourage you to open an issue there since I am not familiar with these tools, but still, I am willing to help, ping me when needed:)

**Comment by Pipboyguy** [comment]
@SteveLauC Please see #905 

Using `-n base` directly targets the base environment, making the `auto_activate_base` check redundant.
