### ISSUE TITLE
ClamAV database update support (freshclam)

### ISSUE THREAD

**Issue by fluentmoheshwar** [topgrade-rs/topgrade#743]
## I want to suggest a new step

I want topgrade to upgrade the database of ClamAV

### Which tool is this about? Where is its repository?

It's a Cross-platform antivirus software. Repo: https://github.com/Cisco-Talos/clamav

### Which operating systems are supported by this tool?

Windows, Linux, Mac

### What should Topgrade do to figure out if the tool needs to be invoked?

check if `freshclam` exists in PATH.

### Which exact commands should Topgrade run?

```command
freshclam
```

**Comment by SteveLauC** [comment]
Implemented in #747
