### ISSUE TITLE
[Feature Request] Add support for PlatformIO Core update

### ISSUE THREAD

**Issue by Auravendill** [topgrade-rs/topgrade#754]
### Which tool is this about? Where is its repository?
PlatformIO is a tool to configure and compile embedded software – especially custom firmware for 3D printer.
The command "`pio upgrade`" is used to check if a new version (of the "Core") is available and will upgrade it, if needed.
(The other parts not in the core are the VS Code extension, which is therefore already supported, and the libraries used in each project)

This is their website, which has links to their git repository and documentation: https://platformio.org/

### Which operating systems are supported by this tool?

Linux, Windows (and most likely on Apple as well)

### What should Topgrade do to figure out if the tool needs to be invoked?

On Linux the default installation path for the updater is: "`~/.platformio/penv/bin/pio`"
If it exists, invoke it.

On Windows it is according to documentation in "`C:\Users\UserName\.platformio\penv\Scripts\`", which should result in the path being "`~/.platformio/penv/Scripts/pio.exe`". (tested in Powershell on Windows 10)

### Which exact commands should Topgrade run?

On Linux: `~/.platformio/penv/bin/pio upgrade`
On Windows: `~/.platformio/penv/Scripts/pio.exe upgrade`

**Comment by SteveLauC** [comment]
Hi, sounds like a nice step to add!

My question is that is this `pio` binary put in `$PATH`, or we have to involve it through the full binary path?

**Comment by Auravendill** [comment]
By default it isn't put into the path. The [documentation](https://docs.platformio.org/en/latest/core/installation/shell-commands.html) recommends, that symbolic links are used to effectively put the binaries in `~/.local/bin/` and put that into the path, but that's far from what the average user does, since you can also call pio upgrade via the VS Code plugin's GUI (which requires VS Code to be restarted if an update was done) and the CLI seems to be rarely used.

So yeah, I'm afraid using it via the full path of the binary is the only option for 99% of users.

**Comment by SteveLauC** [comment]
Will implement this tomorrow
