### ISSUE TITLE
Possibility to disable / config TLDR in config TOML

### ISSUE THREAD

**Issue by j-lakeman** [topgrade-rs/topgrade#758]
Almost every step of topgrade can be disabled and configured in the TOML file except TLDR. Please add a section in the config file for TLDR as well.

**Comment by SteveLauC** [comment]
> Almost every step of topgrade can be disabled and configured in the TOML file except TLDR

You can disable it in your config file, like this:

```toml
[misc]
disable = ["tldr"]
```

**Comment by j-lakeman** [comment]
Sorry, overlooked that one.
