### ISSUE TITLE
Could TopGrade Please Support ZVM?

### ISSUE THREAD

**Issue by tristan-nsg** [topgrade-rs/topgrade#769]
### Which tool is this about? Where is its repository?
The tool is [ZVM](https://github.com/tristanisham/zvm). It's the Zig Version Manager. 
### Which operating systems are supported by this tool?
 - Windows
 - Linux
 - MacOS
 - FreeBSD
 - NetBSD
 - Plan9
 - Solaris
### What should Topgrade do to figure out if the tool needs to be invoked?
It depends on what you're most comfortable with. ZVM comes with its own self-upgrade functionality. Just running that will automatically upgrade ZVM to the latest version, or print a nice message to stdout if the latest version is already installed.

If you'd rather grab ZVM manually, the releases are all hosted on GitHub and organized by `zvm-${os}-${arch}`. The bundle just needs to be unpacked in `$ZVM_INSTALL` or `~/.zvm/self` if the former is not set. Add that directory and `~/$(ZVM_INSTALL)/../bin` to path as well. 

This is the equivalent bash. 
```sh
echo "# ZVM" >> $HOME/.profile
echo export ZVM_INSTALL="$HOME/.zvm/self" >> $HOME/.profile
echo export PATH="$PATH:$HOME/.zvm/bin" >> $HOME/.profile
echo export PATH="$PATH:$ZVM_INSTALL/" >> $HOME/.profile
```

![image](https://github.com/topgrade-rs/topgrade/assets/73843070/de22ddbb-fe34-4a37-ba2e-61dd4e0c444a)

### Which exact commands should Topgrade run?
`zvm upgrade`

## More information
ZVM comes with one-line install scripts for Bash and Windows. The Bash Script does not edit environment variables, but that's just because I'm not comfortable with Bash enough to edit user's configs. Following the install script will show you step-by-step how to install and configure ZVM.

**Comment by SteveLauC** [comment]
So IIUC, `zvm upgrade` only updates `zvm` itself, it won't update the installed Zig toolchains

**Comment by tristan-nsg** [comment]
Yes. I thought that was what the question was asking. If the goal is to upgrade Zig, then just run `zvm i master`.

**Comment by SteveLauC** [comment]
> then just run zvm i master.

Ok, I am not familiar with zig, so I will implement this step and let it update `zvm` itself
