### ISSUE TITLE
ZI Upgrades fail

### ISSUE THREAD

**Issue by StephanSchmidt** [topgrade-rs/topgrade#775]
## Erroneous Behavior

Updating ZI failes with 

   zi failed: 
   0: Command failed: `/usr/bin/zsh -i -c 'source /home/stephan/.zshrc && zi self-update && zi update --all -p'`
   1: `/usr/bin/zsh` failed: exit status: 1

## Expected Behavior

Updating ZI works

## Possible Cause (Optional)

The `-p` starts parallel updates,  but the process ends early. When executing the command I get

   zsh:1: warning: 2 jobs SIGHUPed

## Problem persists without calling from topgrade
- [ x] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [ x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Windows 11/ WSL / Ubuntu 22.04.

- Topgrade version: 14.0.1

**Comment by StephanSchmidt** [comment]
Thanks, did a search, but wasn't good enough. Looking forward to the release + thank you for the tool and the very very fast response.

**Comment by SteveLauC** [comment]
Ok, so I will close this issue
