### ISSUE TITLE
Add auto-cpufreq 

### ISSUE THREAD

**Issue by sbstn87** [topgrade-rs/topgrade#793]
Hi, would it be possible to add a single app to topgrade? Below you will find a link to the repo, it has an option to update itself.

### Which tool is this about? Where is its repository?
https://github.com/AdnanHodzic/auto-cpufreq

### Which operating systems are supported by this tool?
Linux

### What should Topgrade do to figure out if the tool needs to be invoked?
Check if the app is installed and just run the update command, it checks if the update is available.

### Which exact commands should Topgrade run?
sudo auto-cpufreq --update

**Comment by SteveLauC** [comment]
Nice tool, will add it.
