### ISSUE TITLE
Corrupt topgrade-10.0.0-x86_64-linux-gnu.tar.gz in 10.0.1 release assets

### ISSUE THREAD

**Issue by humboldtux** [topgrade-rs/topgrade#80]
Just for you to know, there is a corrupt topgrade-10.0.0-x86_64-linux-gnu.tar.gz download listed in the release assets of the last 10.0.1 version.

**Comment by DottoDev** [comment]
Thanks, is deleted

**Comment by humboldtux** [comment]
I just downloaded the x86_64-linux-musl.tar.gz and the x86_64-linux-musl.tar.gz archives and both are the 10.0.0 version:

```
tar zxf topgrade-10.0.1-x86_64-linux-gnu.tar.gz
./topgrade --version
Topgrade 10.0.0

rm -f topgrade

tar zxf topgrade-10.0.1-x86_64-linux-musl.tar.gz
./topgrade --version
Topgrade 10.0.0
```

Can't tell if that was the case before you deleted the topgrade-10.0.0-x86_64-linux-gnu.tar.gz archive.

**Comment by DottoDev** [comment]
Interesting, this shouldn't be normally

**Comment by DottoDev** [comment]
I'll look into that

**Comment by DottoDev** [comment]
Found out the reason, everything was fine, only the Cargo.toml version wasn't changed
