### ISSUE TITLE
Consistent casing: `Topgrade` vs. `topgrade`

### ISSUE THREAD

**Issue by paescuj** [topgrade-rs/topgrade#85]
Based on discussion started in #82.

---

Consistent casing for the name of this project would be great, primarily concerning the README, documentation and outputs of the tool.
The question is whether to use `Topgrade` or `topgrade`.

This is how the discussion has gone so far:

> @DottoDev
>
> Consistency would be great, but I don't really know if topgrade or Topgrade should be used. But probably would be topgrade the better option.

> @paescuj 
>
> Thanks for your feedback! I'm not sure either... I would probably have said "topgrade" too.
> However, "Topgrade" is currently used a little more in the source code:
> ```console
> ❯ grep " Topgrade " * -r | wc -l
>       16
> ❯ grep " topgrade " * -r | wc -l
>        6
> ```
> 
> Should we just go with ~"topgrade"~ "Topgrade"? I mean we can always change it back at a later time.
> I'd happy to provide a PR for this.
> 
> **Edit:** Okay, I briefly tested how the [documentation](https://topgrade-rs.github.io) looks when "topgrade" is used everywhere and I must say IMO it looks better with "Topgrade". I think same goes for the README.

**Comment by DottoDev** [comment]
Now that I saß it I would say Topgrade is the way to go. With the exception when it's refering to something like the crate, but then IMO it should be pre/postfix notated with something like crate or binary...

**Comment by paescuj** [comment]
> Now that I saw it I would say Topgrade is the way to go. With the exception when it's refering to something like the crate, but then IMO it should be pre/postfix notated with something like crate or binary...

Perfect! Yes, I very much agree with this!
