### ISSUE TITLE
togprade: do `scoop cache rm -a` also when doing `topgrade --no-retry --cleanup --yes --only 'scoop'`

### ISSUE THREAD

**Issue by soredake** [topgrade-rs/topgrade#891]
## I want to suggest a new step

* Which tool is this about? Where is its repository?
* Which operating systems are supported by this tool?
* What should Topgrade do to figure out if the tool needs to be invoked?
* Which exact commands should Topgrade run?
* Does it have a `--dry-run` option? i.e., print what should be done and exit
* Does it need the user to confirm the execution? And does it provide a `--yes`
  option to skip this step?

## I want to suggest some general feature
Do `scoop cache rm -a` also when doing `topgrade --no-retry --cleanup --yes --only 'scoop'` so scoop cache would not be piling up forever on disk.

**Comment by SteveLauC** [comment]
Hi, sorry for the late reply!

IIUC, we should add:

```diff
pub fn run_scoop(ctx: &ExecutionContext) -> Result<()> {
    let scoop = require("scoop")?;

    print_separator("Scoop");

    ctx.run_type().execute(&scoop).args(["update"]).status_checked()?;
    ctx.run_type().execute(&scoop).args(["update", "*"]).status_checked()?;

    if ctx.config().cleanup() {
        ctx.run_type().execute(&scoop).args(["cleanup", "*"]).status_checked()?;
+       ctx.run_type().execute(&scoop).args(["cache", "rm", "-a"]).status_checked()?

    Ok(())
}
```

Is this right?

**Comment by soredake** [comment]
@SteveLauC yes

**Comment by SteveLauC** [comment]
> @SteveLauC yes

Get it, let me impl this feature.
