### ISSUE TITLE
Run Fisher without .config/fish/functions/fisher.fish existing

### ISSUE THREAD

**Issue by Chrobin111** [topgrade-rs/topgrade#9]
## I want to suggest some general feature
Topgrade should run Fisher even if _.config/fish/functions/fisher.fish_ doesn't exist. This is e.g. the case for Homebrew installations of Fisher.

**Comment by DottoDev** [comment]
Where does homebrew install fisher?

**Comment by Chrobin111** [comment]
It's under `$HOMEBREW_CELLAR/fisher/4.4.3/share/fish/vendor_functions.d/`, where 4.4.3 is the version of fisher.

**Comment by phnx47** [comment]
ArchLinux install here:
```
/usr/share/fish/vendor_functions.d/fisher.fish
/usr/share/fish/vendor_completions.d/fisher.fish
```
https://github.com/archlinux/svntogit-community/blob/packages/fisher/trunk/PKGBUILD

**Comment by DottoDev** [comment]
@9999years Do you have new commits about that which should be merged?

**Comment by 9999years** [comment]
Nope, let's close this; the patch in #172 should work for all of these cases.
