### ISSUE TITLE
`Feature` | Microsoft Store app update support

### ISSUE THREAD

**Issue by Andreas02-dev** [topgrade-rs/topgrade#912]
## I want to suggest a new step

Currently, `topgrade` does not have support for updating apps installed through the `Microsoft Store`.
As some apps/components are preinstalled and updated through the Microsoft Store, even if the user doesn't install MS Store apps themselves, they will still need to update the MS Store apps regularly.
- OS support: Windows
- Figuring out if the tool needs to be invoked: Doesn't seem like it would be possible?
- Exact command to be run by Topgrade in an administrative powershell session: `Get-CimInstance -Namespace "Root\cimv2\mdm\dmmap" -ClassName "MDM_EnterpriseModernAppManagement_AppManagement01" | Invoke-CimMethod -MethodName UpdateScanMethod`
- It does not seem to have a `--dry-run` option.
- The user does not need to confirm execution, so a `--yes` option isn't needed for this step.

## More information

The setting to automatically download and install app updates must be turned on for this to work correctly. This setting should be on by default, but perhaps there might be a way to check and warn the user when this is turned off?

![MS_Store_setting](https://github.com/user-attachments/assets/6ec721ab-1f43-4197-bc32-04e123d4e2ff)

**Comment by SteveLauC** [comment]
> Figuring out if the tool needs to be invoked: 
>
>Doesn't seem like it would be possible?

Perhaps one can read the app list, and see if Microsoft Store is installed or not.

> Exact command to be run by Topgrade **in an administrative powershell session**

Can we do that with sudo?

------

I am not a Windows user and I know almost nothing about Windows, so I could not implement this feature:<

**Comment by Andreas02-dev** [comment]
> > Figuring out if the tool needs to be invoked:
> > Doesn't seem like it would be possible?
> 
> Perhaps one can read the app list, and see if Microsoft Store is installed or not.
> 
> > Exact command to be run by Topgrade **in an administrative powershell session**
> 
> Can we do that with sudo?
> 
> I am not a Windows user and I know almost nothing about Windows, so I could not implement this feature:<

Now that I think about it, Microsoft Store should always be installed according to https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app. So it would be logical for the tool to be invoked on every Windows system.

Sudo is unfortunately not available on every Windows machine, but I believe Topgrade already has the ability to run commands in admin mode as other steps also require this, so we should be able to re-use that logic.

1 pain-point of this is that the Microsoft Store still has to be opened at least once for the command to work, and I'm not sure how we could detect this.
This is because the command only refreshes the list with available updates, and then relies on the Microsoft Store to automatically download and install these updates.

However, we could let users know by printing in the console and automatically opening the Microsoft Store with `start ms-windows-store://downloadsandupdates` and then storing that we have opened the Microsoft Store at least once in Topgrade state.

I could try to implement this for Topgrade, however I'm not sure what the best way of using Topgrade-specific state is. Do you have more information about this?

**Comment by SteveLauC** [comment]
> but I believe Topgrade already has the ability to run commands in admin mode as other steps also require this, so we should be able to re-use that logic.

Ahh, I am aware of this, looking at the code, looks like the System step will be executed in admin mode.

> However, we could let users know by printing in the console and automatically opening the Microsoft Store with start ms-windows-store://downloadsandupdates and then storing that we have opened the Microsoft Store at least once in Topgrade state.

Yeah, this looks feasible.

> I could try to implement this for Topgrade,

Thanks!

> however I'm not sure what the best way of using **Topgrade-specific state** is. Do you have more information about this?

[Here](https://github.com/topgrade-rs/topgrade/blob/main/CONTRIBUTING.md#adding-a-new-step) documents how to add a new step for Topgrade. For your state question, you mean the state that we have launched the store app? I guess we can use a variable to do it? I kinda think I didn't understand the question, sorry:<

**Comment by Andreas02-dev** [comment]
> For your state question, you mean the state that we have launched the store app? I guess we can use a variable to do it? I kinda think I didn't understand the question, sorry:<

No problem. I meant to persist the state that we have launched the store app at least once, as we only need to make sure the store app is launched once instead of having to launch it everytime the step is executed or the machine is rebooted.

Do you know if one of the other steps might also do something like this, or if Topgrade has some helper functions to persist and retrieve some state for a step?

If not, maybe it would be best to see if we or someone could implement that before I start working on this feature, so we have a well thought-out API we could potentially re-use for other steps too if they need to persist data.

**Comment by SteveLauC** [comment]
> I meant to persist the state that we have launched the store app at least once, as we only need to make sure the store app is launched once instead of having to launch it everytime the step is executed or the machine is rebooted.

Emmm, I thought we need to launch it or ensure it is opened during every execution? Is it possible that the app could be closed by the users after an execution?


> Do you know if one of the other steps might also do something like this, or if Topgrade has some helper functions to persist and retrieve some state for a step?

AFIK, no. 😣

> If not, maybe it would be best to see if we or someone could implement that before I start working on this feature, so we have a well thought-out API we could potentially re-use for other steps too if they need to persist data.

If needed, I think we can simply use a lightweight KV database, such as sled, though sled is technically not that lightweight.

**Comment by Andreas02-dev** [comment]
> > I meant to persist the state that we have launched the store app at least once, as we only need to make sure the store app is launched once instead of having to launch it everytime the step is executed or the machine is rebooted.
> 
> Emmm, I thought we need to launch it or ensure it is opened during every execution? Is it possible that the app could be closed by the users after an execution?
> 
> > Do you know if one of the other steps might also do something like this, or if Topgrade has some helper functions to persist and retrieve some state for a step?
> 
> AFIK, no. 😣
> 
> > If not, maybe it would be best to see if we or someone could implement that before I start working on this feature, so we have a well thought-out API we could potentially re-use for other steps too if they need to persist data.
> 
> If needed, I think we can simply use a lightweight KV database, such as sled, though sled is technically not that lightweight.

Sorry for my late reply, I've been a bit busy.

I've looked into the 'must launch MS Store once' requirement, and I've only found 1 (unofficial) source claiming this, so I don't think we need it.

I plan on implementing this step on October 18th and October 19th, could you assign this feature request to me?

**Comment by SteveLauC** [comment]
> I plan on implementing this step on October 18th and October 19th

Thanks!

> could you assign this feature request to me?

Sure:)

**Comment by niStee** [comment]
I would like to contribute the following suggestions for adding Microsoft Store app update support to the Topgrade tool:

**Using the MDM_EnterpriseModernAppManagement_AppManagement01 class:**
The approach proposed by @Andreas02-dev using the `Get-CimInstance` and `Invoke-CimMethod` cmdlets to call the `UpdateScanMethod` on the `MDM_EnterpriseModernAppManagement_AppManagement01` class is an interesting one. However, this method seems more suitable for managed devices and the Mobile Device Management (MDM) domain. It would be worth exploring the limitations and potential issues with using this approach for the Topgrade tool and its target audience.

**Using winget:**
Leveraging the `winget` command-line tool to upgrade Microsoft Store apps is another option worth considering. As noted, this feature is said to be improving over time, so it may become a more viable solution in the future. It would be helpful to test the current capabilities of `winget` for updating Microsoft Store apps and evaluate its suitability for the Topgrade use case. [Discussion on winget-cli repository](https://github.com/microsoft/winget-cli/discussions/2184)

**Re-registering Windows Store apps:**
The approach of using the PowerShell command `Get-AppxPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}` to re-register all Windows Store apps is an interesting alternative. This method may be able to trigger updates for the installed Microsoft Store apps. It would be valuable to test this approach and assess its reliability and effectiveness for the Topgrade tool.[Discussion on superuser.com](https://superuser.com/questions/1649375/windows-store-application-re-install)

I believe it's important to carefully evaluate the pros and cons of each approach, considering factors such as reliability, maintainability, and the overall user experience for Topgrade users. The community's feedback and further research will be crucial in determining the most suitable solution for this feature request.

**Comment by Andreas02-dev** [comment]
> I would like to contribute the following suggestions for adding Microsoft Store app update support to the Topgrade tool:
> 
> **Using the MDM_EnterpriseModernAppManagement_AppManagement01 class:** The approach proposed by @Andreas02-dev using the `Get-CimInstance` and `Invoke-CimMethod` cmdlets to call the `UpdateScanMethod` on the `MDM_EnterpriseModernAppManagement_AppManagement01` class is an interesting one. However, this method seems more suitable for managed devices and the Mobile Device Management (MDM) domain. It would be worth exploring the limitations and potential issues with using this approach for the Topgrade tool and its target audience.
> 
> **Using winget:** Leveraging the `winget` command-line tool to upgrade Microsoft Store apps is another option worth considering. As noted, this feature is said to be improving over time, so it may become a more viable solution in the future. It would be helpful to test the current capabilities of `winget` for updating Microsoft Store apps and evaluate its suitability for the Topgrade use case. [Discussion on winget-cli repository](https://github.com/microsoft/winget-cli/discussions/2184)
> 
> **Re-registering Windows Store apps:** The approach of using the PowerShell command `Get-AppxPackage | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}` to re-register all Windows Store apps is an interesting alternative. This method may be able to trigger updates for the installed Microsoft Store apps. It would be valuable to test this approach and assess its reliability and effectiveness for the Topgrade tool.[Discussion on superuser.com](https://superuser.com/questions/1649375/windows-store-application-re-install)
> 
> I believe it's important to carefully evaluate the pros and cons of each approach, considering factors such as reliability, maintainability, and the overall user experience for Topgrade users. The community's feedback and further research will be crucial in determining the most suitable solution for this feature request.

Hi @niStee ,

Thanks for your detailed input, I've looked into your suggestions.

Re-registering the Windows Store apps sounded promising, however even a 'simple' Windows Photos (which I didn't open manually) fails with `Add-AppxPackage : Deployment failed with HRESULT: 0x80073D02, The package
could not be installed because resources it modifies are currently in use.
error 0x80073D02: Unable to install because the following apps need to be
closed Microsoft.Windows.Photos_2024.11090.27004.0_x64__8wekyb3d8bbwe.
NOTE: For additional information, look for [ActivityId]`.
Therefore I don't think this approach would be very reliable.

I also agree that Winget should be the way forward, however it cannot handle every MS Store app yet as the version information still can't be found for some MS Store packages. This would result in some apps being outdated even though the Winget step ran successfully. When Winget works correctly for all MS Store apps, we could consider just using Winget for both Winget and MS Store app update instead, however that would take time which I hope my suggested approach could bridge.

While my suggested approach using the MDM class does seem to be more suitable for managed devices and the Mobile Device Management (MDM) domain, it also works correctly for devices in home use which are not part of any MDM domain or managed.
When doing research, this also seemed the most-used approach to update MS Store apps.

My suggestion would be to create a MS Store update step using the `Get-CimInstance` and `Invoke-CimMethod` cmdlets, and re-evaluate using Winget for this functionality in the future, when the missing version information no longer causes apps to become outdated with Winget. Do let me know your thoughts on this.
