### ISSUE TITLE
error "Running Aura with sudo is not necessary" if aura is arch_package_manager

### ISSUE THREAD

**Issue by ProfP30** [topgrade-rs/topgrade#913]
## Erroneous Behavior
topgrade brings following error message if aura is set as "arch_package_manager"
```
aura :: Running Aura with sudo is not necessary.
System update failed:
0: Command failed: `/usr/bin/sudo /usr/bin/aura -Au`
1: `/usr/bin/sudo` failed: exit status: 1
```
## Expected Behavior
topgrade runs without error if aura is set as "arch_package_manager"

## Steps to reproduce
Login to arch or derivate distro
modify topgrade.toml file
set "aura" as package manger for arch in section [Linux]:
```toml
[linux]
arch_package_manager = "aura"
```

## Possible Cause (Optional)
newer versions of aura don't neet sudo anymore

## Problem persists without calling from topgrade
Execute the erroneous command directly to see if the problem persists

- [ x] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [ x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml
[linux]
arch_package_manager = "aura"
```

## Additional Details
- Operation System/Version
  
CachyOS Linux x86_64

- Installation
  

- Topgrade version (`topgrade -V`)
Topgrade 15.0.0

- Aura version (`aura -V`)
aura 4.0.7

## Verbose Output (`topgrade -v`)

<details>
<pre>

</pre>
</details>

**Comment by SteveLauC** [comment]
Fixed in #908, I guess I will release the new version within 2 weeks, please wait a bit:)

**Comment by SteveLauC** [comment]
Or you can use [this build](https://github.com/SteveLauC/topgrade/releases/tag/pr908) if you want to try it out.

**Comment by SteveLauC** [comment]
Close as fixed, feel free to reopen if you have any further questions:)

**Comment by ProfP30** [comment]
Test build from PR908. Works. Thanks!
