### ISSUE TITLE
armv7 (raspberry pi) version missing

### ISSUE THREAD

**Issue by reini-1** [topgrade-rs/topgrade#93]
## What did you expect to happen?
armv7 version for e.g. raspberry pi is missing as it existed before in the r-darwish repo.

## Additional Details
- Which operating system or Linux distribution are you using?
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
- How did you install Topgrade?
cannot, new version missing
- Which version are you running? Topgrade 9.0.1

<details>

<pre>

</pre>
</details>

**Comment by DottoDev** [comment]
You can install it using cargo install topgrade or wait for the next release, 10.1.0, which will reintroduce armv7. Currently their are some problems with the new version which makes it fail the CD pipeline but after those problems are fixed the new version will be released.
