### ISSUE TITLE
Support Different Ports Per SSH Host

### ISSUE THREAD

**Issue by gozzarda** [topgrade-rs/topgrade#95]
## I want to suggest some general feature
Topgrade should allow the user to specify (in topgrade.toml) what port to use for each host.
Currently users may only specify port in the ssh arguments that are used for every host.
This means that if the user wants to update multiple hosts with SSH running on different ports (such as behind a NAT) this is not possible.

## More information
I would be comfortable helping test this feature.

I would also be willing to work on this feature, but it's a coinflip as to whether I will have the time in the next couple of months, so don't wait on me.

**Comment by ssmendon** [comment]
I was working on implementing this inside `topgrade` (and I've just about finished it), but then I wanted to figure out if there's a good use case for this feature to be implemented inside `topgrade` itself.

Is there a specific reason the following workarounds are not optimal for your use case, @gozzarda? I did a preliminary test, and it seems to work. 

For the following, assume we want to connect to a remote hostname `foo` on port `1234`.

## Workarounds

### add host-specific ~/.ssh/config modifications

`topgrade` uses the environment of the shell that invokes it, and it picks up my `.ssh/config` details directly from that file.

#### Example

```ssh-config
# ~/.ssh/config
Host foo
  Port 1234
```

### specify port in `topgrade.toml`'s `remote_topgrades` value

For clarity, [`man ssh`][ssh-manpage] describes [the field `topgrade` calls "hostname"][topgrade-hostname] as `destination`[^ssh-destination].

#### Example

```toml
remote_topgrades = [
  "ssh://foo:1234",
]
```  

[^ssh-destination]: Quote from [`man ssh`][ssh-manpage] > DESCRIPTION: 
    > ssh connects and logs into the specified *destination*, which may be specified as either [user@]hostname or a URI of the form ssh://[user@]hostname[:port].

[topgrade-hostname]: <https://github.com/topgrade-rs/topgrade/blob/ecbaf52156142832e9c742eeeae7db0626156412/src/steps/remote/ssh.rs#L10>
[ssh-manpage]: <https://www.man7.org/linux/man-pages/man1/ssh.1.html#DESCRIPTION>

**Comment by gozzarda** [comment]
@ssmendon nice catch... I must have butchered the URI because I tried that and it didn't work for me. That would certainly work for my purposes.

Something to consider before closing the issue though: Are there any other options that should be configurable per-host? Even if these can be done in `.ssh/config` I would think that either they should be able to be done in topgrade as well or we should leave all configuration to `.ssh/config`, assuming that is possible.

One way or another, I think if we are going to have SSH options it should be possible to specify them per host. That's just my opinion though, and I don't have the time to work on this any time soon, so I am happy for this to be closed if any contributor thinks SSH options are fine as-is.
