### ISSUE TITLE
Topgrade fails trying to self update.  Same errors when attempting cargo install topgrade.

### ISSUE THREAD

**Issue by cvondra** [topgrade-rs/topgrade#959]
## Erroneous Behavior
What actually happened?  Running topgrade it attempts to upgrade itself from 16.0.0 to 16.1.1.  Error results in:

error: the `-Z unstable-options` flag must also be passed to enable the flag `ch                                                                                                                             eck-cfg`

error: could not compile `topgrade` (build script)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `topgrade v16.0.1`, intermediate artifacts can be found at `/tmp/cargo-installAPbYo0`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Updated 0 packages.
Failed to update topgrade.

Package  Installed  Latest  Needs update

No git packages need updating.
Overall updated 0 packages.
Overall failed to update 1 package: topgrade.
cargo failed:
   0: Command failed: `/home/myuser/.cargo/bin/cargo-install-update install-update --git --all`
   1: `/home/myuser/.cargo/bin/cargo-install-update` failed: %{exit_satus}

Location:
   /home/myuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-16.0.0/src/steps/generic.rs:74
Retry? (y)es/(N)o/(s)hell/(q)uit

## Expected Behavior
Expected it to upgrade itself w/no error.

## Steps to reproduce

Enter Topgrade 

## Problem persists without calling from topgrade

- [x] Yes
- [ ] No

## Did you run topgrade through `Remote Execution`

- [x ] Yes
- [ ] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [x ] Yes
- [ ] No

## Configuration file (Optional)

```toml

```

## Additional Details
- Operation System/Version
 Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-47-generic x86_64)
- Installation
 
cargo install topgrade  

- Topgrade version: topgrade 16.0.0

## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Current system locale is en-US
DEBUG Configuration at /home/cvondra/.config/topgrade.toml
DEBUG Loaded configuration: ConfigFile { include: None, misc: Some(Misc { pre_sudo: None, sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, no_retry: None, run_in_tmux: None, tmux_session_mode: None, cleanup: None, notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None }), pre_commands: Some({}), post_commands: None, commands: Some({}), python: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), containers: None, windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: None }
DEBUG Version: 16.0.0
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/home/cvondra/.cargo/bin/topgrade")
DEBUG self-update Feature Enabled: false
DEBUG Configuration: Config { opt: CommandLineArgs { edit_config: false, show_config_reference: false, run_in_tmux: false, cleanup: false, dry_run: false, no_retry: false, disable: [], only: [], custom_commands: [], env: [], verbose: true, keep_at_end: false, skip_notify: false, yes: None, disable_predefined_git_repos: false, config: None, remote_host_limit: None, show_skipped: false, log_filter: "warn", gen_completion: None, gen_manpage: false, no_self_update: false }, config_file: ConfigFile { include: None, misc: Some(Misc { pre_sudo: None, sudo_command: None, disable: None, ignore_failures: None, remote_topgrades: None, remote_topgrade_path: None, ssh_arguments: None, tmux_arguments: None, set_title: None, display_time: None, assume_yes: None, no_retry: None, run_in_tmux: None, tmux_session_mode: None, cleanup: None, notify_each_step: None, skip_notify: None, bashit_branch: None, only: None, no_self_update: None, log_filters: None }), pre_commands: Some({}), post_commands: None, commands: Some({}), python: None, composer: Some(Composer { self_update: None }), brew: Some(Brew { greedy_cask: None, greedy_latest: None, greedy_auto_updates: None, autoremove: None, fetch_head: None }), linux: Some(Linux { yay_arguments: None, aura_aur_arguments: None, aura_pacman_arguments: None, arch_package_manager: None, show_arch_news: None, garuda_update_arguments: None, trizen_arguments: None, pikaur_arguments: None, pamac_arguments: None, dnf_arguments: None, nix_arguments: None, nix_env_arguments: None, apt_arguments: None, enable_tlmgr: None, redhat_distro_sync: None, suse_dup: None, rpm_ostree: None, emerge_sync_flags: None, emerge_update_flags: None, home_manager_arguments: None }), git: Some(Git { max_concurrency: None, arguments: None, repos: None, pull_predefined: None }), containers: None, windows: Some(Windows { accept_all_updates: None, self_rename: None, open_remotes_in_new_terminal: None, wsl_update_pre_release: None, wsl_update_use_web_download: None }), npm: Some(NPM { use_sudo: None }), yarn: None, vim: None, firmware: Some(Firmware { upgrade: None }), vagrant: None, flatpak: Some(Flatpak { use_sudo: None }), distrobox: Some(Distrobox { use_root: None, containers: None }), lensfun: None }, allowed_steps: [AM, AppMan, Asdf, Atom, Aqua, Audit, AutoCpufreq, Bin, Bob, BrewCask, BrewFormula, Bun, BunPackages, Cargo, Certbot, Chezmoi, Chocolatey, Choosenim, ClamAvDb, Composer, Conda, ConfigUpdate, Containers, CustomCommands, DebGet, Deno, Distrobox, DkpPacman, Dotnet, Elan, Emacs, Firmware, Flatpak, Flutter, Fossil, Gcloud, Gem, Ghcup, GithubCliExtensions, GitRepos, GnomeShellExtensions, Go, Guix, Haxelib, Helm, HomeManager, Jetpack, Julia, Juliaup, Kakoune, Helix, Krew, Lure, Lensfun, Macports, Mamba, Miktex, Mas, Maza, Micro, Mise, Myrepos, Nix, Node, Opam, Pacdef, Pacstall, Pearl, Pip3, PipReview, PipReviewLocal, Pipupgrade, Pipx, Pixi, Pkg, Pkgin, PlatformioCore, Pnpm, Poetry, Powershell, Protonup, Pyenv, Raco, Rcm, Remotes, Restarts, Rtcl, RubyGems, Rustup, Rye, Scoop, Sdkman, SelfUpdate, Sheldon, Shell, Snap, Sparkle, Spicetify, Stack, Stew, System, Tldr, Tlmgr, Tmux, Toolbx, Uv, Vagrant, Vcpkg, Vim, VoltaPackages, Vscode, Waydroid, Winget, Wsl, WslUpdate, Xcodes, Yadm, Yarn, Zvm] }
DEBUG Detected "/snap/bin/pwsh" as "pwsh"
DEBUG Executing command `/snap/bin/pwsh -NoProfile -Command 'Split-Path $profile'`
DEBUG Path "/home/cvondra/.config/emacs" doesn't exist
DEBUG Path "/home/cvondra/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Detected "/usr/bin/sudo" as "sudo"
DEBUG Step "packer.nu"
DEBUG Step "System update"

── 13:05:28 - System update ────────────────────────────────────────────────────
DEBUG Cannot find "apt-fast"
DEBUG Cannot find "mist"
DEBUG Executing command `/usr/bin/sudo apt-get update`
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists... Done
DEBUG Executing command `/usr/bin/sudo apt-get dist-upgrade`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libgit2-1.7 libhttp-parser2.9 libssh2-1t64 libstd-rust-1.75 libstd-rust-dev linux-headers-5.15.0-122 linux-headers-5.15.0-122-generic linux-image-5.15.0-122-generic linux-modules-5.15.0-122-generic
  linux-modules-extra-5.15.0-122-generic
Use 'sudo apt autoremove' to remove them.
The following upgrades have been deferred due to phasing:
  gir1.2-gtk-3.0 gtk-update-icon-cache initramfs-tools initramfs-tools-bin initramfs-tools-core libgtk-3-0t64 libgtk-3-bin libgtk-3-common snapd
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
DEBUG Step "config-update"
DEBUG Step "am"
DEBUG Step "appman"
DEBUG Step "deb-get"
DEBUG Step "toolbx"
DEBUG Step "snap"
DEBUG Detected "/usr/bin/snap" as "snap"

── 13:05:36 - snap ─────────────────────────────────────────────────────────────
DEBUG Executing command `/usr/bin/sudo /usr/bin/snap refresh`
All snaps up to date.
DEBUG Step "pacstall"
DEBUG Step "pacdef"
DEBUG Step "protonup"
DEBUG Step "distrobox"
DEBUG Step "dkp-pacman"
DEBUG Step "pihole"
DEBUG Step "Firmware upgrades"
DEBUG Step "Restarts"
DEBUG Detected "/usr/sbin/needrestart" as "needrestart"
DEBUG Cannot find "apt-fast"
DEBUG Cannot find "mist"

── 13:05:37 - Check for needed restarts ────────────────────────────────────────
DEBUG Executing command `/usr/bin/sudo /usr/sbin/needrestart`
Scanning processes...
Scanning processor microcode...
Scanning linux images...

Running kernel seems to be up-to-date.

The processor microcode seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
DEBUG Step "Flatpak"
DEBUG Step "Brew"
DEBUG Step "LURE"
DEBUG Step "Waydroid"
DEBUG Step "auto-cpufreq"
DEBUG Step "yadm"
DEBUG Step "nix"
DEBUG Step "nix upgrade-nix"
DEBUG Step "guix"
DEBUG Step "home-manager"
DEBUG Step "asdf"
DEBUG Step "mise"
DEBUG Step "pkgin"
DEBUG Step "bun-packages"
DEBUG Step "zr"
DEBUG Step "antibody"
DEBUG Step "antidote"
DEBUG Step "antigen"
DEBUG Step "zgenom"
DEBUG Step "zplug"
DEBUG Step "zinit"
DEBUG Step "zi"
DEBUG Step "zim"
DEBUG Step "oh-my-zsh"
DEBUG Step "oh-my-bash"
DEBUG Detected "/usr/bin/bash" as "bash"
DEBUG Step "fisher"
DEBUG Step "bash-it"
DEBUG Step "oh-my-fish"
DEBUG Step "fish-plug"
DEBUG Step "fundle"
DEBUG Step "tmux"
DEBUG Step "TLDR"
DEBUG Step "pearl"
DEBUG Step "Gnome Shell Extensions"
DEBUG Detected "/usr/bin/gdbus" as "gdbus"
DEBUG Step "pyenv"
DEBUG Step "SDKMAN!"
DEBUG Detected "/usr/bin/bash" as "bash"
DEBUG Step "rcm"
DEBUG Step "maza"
DEBUG Step "apm"
DEBUG Step "fossil"
DEBUG Step "elan"
DEBUG Step "rye"
DEBUG Step "rustup"
DEBUG Detected "/usr/bin/rustup" as "rustup"

── 13:05:37 - rustup ───────────────────────────────────────────────────────────
DEBUG Executing command `/usr/bin/rustup update`
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: cleaning up downloads & tmp directories
DEBUG Step "juliaup"
DEBUG Step ".NET"
DEBUG Step "choosenim"
DEBUG Step "cargo"
DEBUG Path "/home/cvondra/.cargo" exists
DEBUG Detected "/home/cvondra/.cargo/bin/cargo" as "cargo"
DEBUG Path "/home/cvondra/.cargo/.crates.toml" exists

── 13:05:38 - Cargo ────────────────────────────────────────────────────────────
DEBUG Detected "/home/cvondra/.cargo/bin/cargo-install-update" as "cargo-install-update"
DEBUG Executing command `/home/cvondra/.cargo/bin/cargo-install-update install-update --git --all`
    Polling registry 'https://index.crates.io/'....

Package       Installed  Latest   Needs update
topgrade      v16.0.0    v16.0.1  Yes
cargo         v0.82.0    v0.82.0  No
cargo-index   v0.2.7     v0.2.7   No
cargo-update  v15.0.0    v15.0.0  No

Updating topgrade
    Updating crates.io index
  Installing topgrade v16.0.1
    Updating crates.io index
     Locking 284 packages to latest compatible versions
      Adding addr2line v0.21.0 (latest: v0.24.2)
      Adding backtrace v0.3.71 (latest: v0.3.74)
      Adding bitflags v1.3.2 (latest: v2.6.0)
      Adding encode_unicode v0.3.6 (latest: v1.0.0)
      Adding generic-array v0.14.7 (latest: v1.1.0)
      Adding gimli v0.28.1 (latest: v0.31.1)
      Adding globwalk v0.8.1 (latest: v0.9.1)
      Adding hashbrown v0.14.5 (latest: v0.15.0)
      Adding hermit-abi v0.3.9 (latest: v0.4.0)
      Adding itertools v0.11.0 (latest: v0.13.0)
      Adding lazy_static v1.4.0 (latest: v1.5.0)
      Adding libyml v0.0.4 (latest: v0.0.5)
      Adding linux-raw-sys v0.4.14 (latest: v0.6.5)
      Adding malloc_buf v0.0.6 (latest: v1.0.0)
      Adding matchers v0.1.0 (latest: v0.2.0)
      Adding miniz_oxide v0.7.4 (latest: v0.8.0)
      Adding mio v0.8.11 (latest: v1.0.2)
      Adding nu-ansi-term v0.46.0 (latest: v0.50.1)
      Adding object v0.32.2 (latest: v0.36.5)
      Adding once_cell v1.19.0 (latest: v1.20.2)
      Adding owo-colors v3.5.0 (latest: v4.1.0)
      Adding quick-xml v0.31.0 (latest: v0.36.2)
      Adding regex v1.10.6 (latest: v1.11.0)
      Adding regex-automata v0.1.10 (latest: v0.4.8)
      Adding regex-syntax v0.6.29 (latest: v0.8.5)
      Adding serde_yml v0.0.11 (latest: v0.0.12)
      Adding syn v1.0.109 (latest: v2.0.79)
      Adding tauri-winrt-notification v0.2.1 (latest: v0.6.0)
      Adding tempfile v3.10.1 (latest: v3.13.0)
      Adding tokio v1.38.1 (latest: v1.40.0)
      Adding toml v0.7.8 (latest: v0.8.19)
      Adding toml_edit v0.19.15 (latest: v0.22.22)
      Adding unicode-width v0.1.14 (latest: v0.2.0)
      Adding wasi v0.11.0+wasi-snapshot-preview1 (latest: v0.13.3+wasi-0.2.2)
      Adding widestring v0.4.3 (latest: v1.1.0)
      Adding windows v0.56.0 (latest: v0.58.0)
      Adding windows-core v0.52.0 (latest: v0.58.0)
      Adding windows-core v0.56.0 (latest: v0.58.0)
      Adding windows-implement v0.56.0 (latest: v0.58.0)
      Adding windows-interface v0.56.0 (latest: v0.58.0)
      Adding windows-result v0.1.2 (latest: v0.2.0)
      Adding windows-sys v0.48.0 (latest: v0.59.0)
      Adding windows-sys v0.52.0 (latest: v0.59.0)
      Adding windows-targets v0.48.5 (latest: v0.52.6)
      Adding windows_aarch64_gnullvm v0.48.5 (latest: v0.52.6)
      Adding windows_aarch64_msvc v0.48.5 (latest: v0.52.6)
      Adding windows_i686_gnu v0.48.5 (latest: v0.52.6)
      Adding windows_i686_msvc v0.48.5 (latest: v0.52.6)
      Adding windows_x86_64_gnu v0.48.5 (latest: v0.52.6)
      Adding windows_x86_64_gnullvm v0.48.5 (latest: v0.52.6)
      Adding windows_x86_64_msvc v0.48.5 (latest: v0.52.6)
      Adding winnow v0.5.40 (latest: v0.6.20)
      Adding winsafe v0.0.19 (latest: v0.0.22)
      Adding zerocopy v0.7.35 (latest: v0.8.5)
      Adding zerocopy-derive v0.7.35 (latest: v0.8.5)
   Compiling proc-macro2 v1.0.88
   Compiling unicode-ident v1.0.13
   Compiling serde v1.0.210
   Compiling crossbeam-utils v0.8.20
   Compiling pin-project-lite v0.2.14
   Compiling memchr v2.7.4
   Compiling cfg-if v1.0.0
   Compiling libc v0.2.159
   Compiling autocfg v1.4.0
   Compiling quote v1.0.37
   Compiling version_check v0.9.5
   Compiling syn v2.0.79
   Compiling log v0.4.22
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.15.0
   Compiling once_cell v1.19.0
   Compiling futures-core v0.3.31
   Compiling aho-corasick v1.1.3
   Compiling indexmap v2.6.0
   Compiling fastrand v2.1.1
   Compiling regex-syntax v0.8.5
   Compiling parking v2.2.1
   Compiling concurrent-queue v2.5.0
   Compiling rustix v0.38.37
   Compiling bitflags v2.6.0
   Compiling futures-io v0.3.31
   Compiling regex-automata v0.4.8
   Compiling tracing-core v0.1.32
   Compiling linux-raw-sys v0.4.14
   Compiling serde_derive v1.0.210
   Compiling serde_json v1.0.128
   Compiling tracing-attributes v0.1.27
   Compiling toml_datetime v0.6.8
   Compiling event-listener v5.3.1
   Compiling slab v0.4.9
   Compiling typenum v1.17.0
   Compiling itoa v1.0.11
   Compiling crossbeam-epoch v0.9.18
   Compiling event-listener-strategy v0.5.2
   Compiling tracing v0.1.40
   Compiling bstr v1.10.0
   Compiling generic-array v0.14.7
   Compiling serde_yml v0.0.11
   Compiling crunchy v0.2.2
   Compiling same-file v1.0.6
   Compiling winnow v0.6.20
   Compiling lazy_static v1.4.0
   Compiling walkdir v2.5.0
   Compiling globset v0.4.15
   Compiling crossbeam-deque v0.8.5
   Compiling regex v1.10.6
   Compiling tiny-keccak v2.0.2
   Compiling toml_edit v0.22.22
   Compiling ignore v0.4.23
   Compiling serde_spanned v0.6.8
   Compiling zerocopy-derive v0.7.35
   Compiling zvariant_utils v2.1.0
   Compiling futures-lite v2.3.0
   Compiling bitflags v1.3.2
   Compiling futures-sink v0.3.31
   Compiling proc-macro-crate v3.2.0
   Compiling regex-syntax v0.6.29
   Compiling heck v0.5.0
   Compiling powerfmt v0.2.0
   Compiling utf8parse v0.2.2
   Compiling byteorder v1.5.0
   Compiling zerocopy v0.7.35
   Compiling anstyle-parse v0.2.5
   Compiling deranged v0.3.11
   Compiling futures-channel v0.3.31
   Compiling regex-automata v0.1.10
   Compiling globwalk v0.8.1
   Compiling getrandom v0.2.15
   Compiling futures-macro v0.3.31
   Compiling enumflags2_derive v0.7.10
   Compiling proc-macro-error-attr v1.0.4
   Compiling memoffset v0.9.1
   Compiling atomic-waker v1.1.2
   Compiling smallvec v1.13.2
   Compiling ryu v1.0.18
   Compiling cfg_aliases v0.2.1
   Compiling winnow v0.5.40
   Compiling num-conv v0.1.0
   Compiling futures-task v0.3.31
   Compiling time-core v0.1.2
   Compiling overload v0.1.1
   Compiling shlex v1.3.0
   Compiling anstyle v1.0.8
   Compiling pin-utils v0.1.0
   Compiling anstyle-query v1.1.1
   Compiling is_terminal_polyfill v1.70.1
   Compiling colorchoice v1.0.2
   Compiling syn v1.0.109
   Compiling async-task v4.7.1
   Compiling anstream v0.6.15
   Compiling cc v1.1.30
   Compiling futures-util v0.3.31
   Compiling time v0.3.36
   Compiling toml_edit v0.19.15
   Compiling nu-ansi-term v0.46.0
   Compiling nix v0.29.0
   Compiling tempfile v3.10.1
   Compiling piper v0.2.4
   Compiling rand_core v0.6.4
   Compiling enumflags2 v0.7.10
   Compiling const-random-macro v0.1.16
   Compiling matchers v0.1.0
   Compiling zvariant_derive v4.2.0
   Compiling ppv-lite86 v0.2.20
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling sharded-slab v0.1.7
   Compiling async-lock v3.4.0
   Compiling async-channel v2.3.1
   Compiling tracing-log v0.2.0
   Compiling thread_local v1.1.8
   Compiling proc-macro-error v1.0.4
   Compiling num-traits v0.2.19
   Compiling rustversion v1.0.18
   Compiling either v1.13.0
   Compiling strsim v0.11.1
   Compiling libyml v0.0.4
   Compiling arc-swap v1.7.1
   Compiling stable_deref_trait v1.2.0
   Compiling endi v1.1.0
   Compiling static_assertions v1.1.0
   Compiling clap_lex v0.7.2
   Compiling zvariant v4.2.0
   Compiling clap_builder v4.5.20
   Compiling triomphe v0.1.14
   Compiling itertools v0.11.0
   Compiling tracing-subscriber v0.3.18
   Compiling blocking v1.6.1
   Compiling rand_chacha v0.3.1
   Compiling digest v0.10.7
   Compiling const-random v0.1.18
   Compiling toml v0.7.8
   Compiling backtrace v0.3.71
   Compiling clap_derive v4.5.18
   Compiling polling v3.7.3
   Compiling eyre v0.6.12
   Compiling gimli v0.28.1
   Compiling adler v1.0.2
   Compiling option-ext v0.2.0
   Compiling normpath v1.3.0
   Compiling siphasher v1.0.1
   Compiling base62 v2.0.2
   Compiling cpufeatures v0.2.14
   Compiling sha1 v0.10.6
   Compiling rust-i18n-support v3.1.2
   Compiling addr2line v0.21.0
   Compiling clap v4.5.20
   Compiling dirs-sys v0.4.1
   Compiling miniz_oxide v0.7.4
   Compiling async-io v2.3.4
   Compiling dlv-list v0.5.2
   Compiling rand v0.8.5
   Compiling async-fs v2.1.2
   Compiling tracing-error v0.2.0
   Compiling zbus_names v3.0.0
   Compiling async-executor v1.13.1
   Compiling rust-i18n v3.1.2
   Compiling zbus_macros v4.4.0
   Compiling async-broadcast v0.7.1
   Compiling async-trait v0.1.83
   Compiling serde_repr v0.1.19
   Compiling ordered-stream v0.2.0
   Compiling xdg-home v1.3.0
   Compiling object v0.32.2
   Compiling hex v0.4.3
   Compiling rustc-demangle v0.1.24
   Compiling hashbrown v0.14.5
   Compiling home v0.5.9
   Compiling indenter v0.3.3
   Compiling thiserror v1.0.64
   Compiling glob v0.3.1
   Compiling semver v1.0.23
   Compiling owo-colors v3.5.0
   Compiling rust-i18n-macro v3.1.2
   Compiling color-spantrace v0.2.1
   Compiling zbus v4.4.0
   Compiling ordered-multimap v0.7.3
   Compiling strum_macros v0.26.4
   Compiling merge_derive v0.1.0
   Compiling dirs v5.0.1
   Compiling futures-executor v0.3.31
   Compiling thiserror-impl v1.0.64
   Compiling mio v0.8.11
   Compiling signal-hook-registry v1.4.2
   Compiling num_cpus v1.16.0
   Compiling unicode-width v0.1.14
   Compiling trim-in-place v0.1.7
   Compiling bytes v1.7.2
   Compiling roff v0.2.2
   Compiling topgrade v16.0.1
   Compiling iana-time-zone v0.1.61
error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg`

error: could not compile `topgrade` (build script)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `topgrade v16.0.1`, intermediate artifacts can be found at `/tmp/cargo-installmEwWFW`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Updated 0 packages.
Failed to update topgrade.

Package  Installed  Latest  Needs update

No git packages need updating.
Overall updated 0 packages.
Overall failed to update 1 package: topgrade.
DEBUG Command failed: Err(
   0: Command failed: `/home/myuser/.cargo/bin/cargo-install-update install-update --git --all`
   1: `/home/myuser/.cargo/bin/cargo-install-update` failed: %{exit_satus}

Location:
   /home/myuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-16.0.0/src/steps/generic.rs:74)
DEBUG Step "cargo" failed:
   0: Command failed: `/home/cvondra/.cargo/bin/cargo-install-update install-update --git --all`
   1: `/home/myuser/.cargo/bin/cargo-install-update` failed: %{exit_satus}

Location:
   /home/myuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-16.0.0/src/steps/generic.rs:74
cargo failed:
   0: Command failed: `/home/myuser/.cargo/bin/cargo-install-update install-update --git --all`
   1: `/home/myuser/.cargo/bin/cargo-install-update` failed: %{exit_satus}

Location:
   /home/myuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-16.0.0/src/steps/generic.rs:74
Retry? (y)es/(N)o/(s)hell/(q)uitmyuser@nuc:~$

</pre>
</details>

**Comment by SteveLauC** [comment]
Emm, mind showing:


```sh
$ cargo --version
```

And, can you build topgrade from source:

> When you build from source, Topgrade overwrites the toolchain to use to 1.76.

```sh
$ git clone https://github.com/topgrade-rs/topgrade.git && cd topgrade
$ cargo build 
```

-------

I just built it on my mac:

```sh
$ cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)

$ cargo install topgrade
   Finished `release` profile [optimized] target(s) in 1m 20s
   Replacing /Users/steve/.cargo/bin/topgrade
    Replaced package `topgrade v16.0.0 (https://github.com/topgrade-rs/topgrade#49327000)` with `topgrade v16.0.1` (executable `topgrade`)
```

**Comment by cvondra** [comment]
cargo 1.81.0

**Comment by cvondra** [comment]
After trying to build it with cargo build I get the following error:  (I only put part of the 558 errors.)

warning: unused import: `self`
  --> src/steps/containers.rs:12:20
   |
12 | use crate::error::{self, TopgradeError};
   |                    ^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::sync::Mutex`
 --> src/terminal.rs:5:5
  |
5 | use std::sync::Mutex;
  |     ^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0425, E0514.
For more information about an error, try `rustc --explain E0425`.
warning: `topgrade` (bin "topgrade") generated 2 warnings
error: could not compile `topgrade` (bin "topgrade") due to 558 previous errors;                                                                                                                              2 warnings emitted
myuser@nuc:~/topgrade$

**Comment by cvondra** [comment]
built topgrade and installed.  All is happy again.  Thx

**Comment by SteveLauC** [comment]
Ok, though the issue still looks pretty weird. And, since you manually build it from source, it won't get automatic updates. `cargo install --git https://github.com/topgrade-rs/topgrade.git` will give you auto-update, but the auto-update will happen on every git commit.

**Comment by cvondra** [comment]
Check that its fk'd worse.

**Comment by cvondra** [comment]
error: the `-Z unstable-options` flag must also be passed to enable the flag `check-cfg`

error: could not compile `topgrade` (build script)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `topgrade v16.0.1 (https://github.com/topgrade-rs/topgrade.git#a5d4f2ee)`, intermediate artifacts can be found at `/tmp/cargo-installAD4bAD`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
cvondra@chadsnuc:~$

**Comment by cvondra** [comment]
Full removal and reinstall.

**Comment by SteveLauC** [comment]
> Full removal and reinstall.

Glad that worked.
