### ISSUE TITLE
Add list of supported package managers to GitHub

### ISSUE THREAD

**Issue by OnyxAbove** [topgrade-rs/topgrade#960]
I came across this tool in my search for a utility that does just this, and I find it particularly appealing because it is very active in development and written in Rust. Is there a list of supported programs/package managers somewhere on the GitHub? 

I use openSUSE Tumbleweed (so zypper) with the additional package managers Nix, Homebrew, and Antidote (ZSH Plugin Manager).

EDIT: I don't know how to change the label to documentation, sorry for labeling it as feature request.

**Comment by SteveLauC** [comment]
>  Is there a list of supported programs/package managers somewhere on the GitHub?

Currently no, we should do this, though I don't have time to (at least for now).

> I use openSUSE Tumbleweed (so zypper) with the additional package managers Nix, Homebrew, and Antidote (ZSH Plugin Manager).

Looks like they are all supported by Topgrade.

> EDIT: I don't know how to change the label to documentation, sorry for labeling it as feature request.

No need to be sorry, it is ok:)

**Comment by OnyxAbove** [comment]
Thank you for the quick reply. I used topgrade for the first time a few hours ago and it did upgrade everything. Thank you for the great utility!

**Comment by OnyxAbove** [comment]
I will now close this issue and make another, more concise one for future discussion (not that htere needs to be much discussion, only someone willing to undertake the task).

**Comment by OnyxAbove** [comment]
I will now close this issue and make another, more concise one for future discussion (not that htere needs to be much discussion, only someone willing to undertake the task).
