### ISSUE TITLE
Add Fedora Support via RPMFusion

### ISSUE THREAD

**Issue by TheOceanBreeze** [topgrade-rs/topgrade#994]
## I want to suggest adding an official way to use Topgrade on Fedora via RPMFusion.

RPMFusion is a repo that contains tons of Fedora packages. It can be found at https://rpmfusion.org/. More information about Fedora Linux can be found at https://fedoraproject.org/.

Having a native package on Fedora would be absolutely amazing seeing as other distros I've used in the past also have native packages.

**Comment by li-lay** [comment]
Hi @TheOceanBreeze, I'm also a long time Fedora user, I decided to package topgrade via Fedora COPR (I will be maintaining this).
Here the link: [topgrade](https://copr.fedorainfracloud.org/coprs/lilay/topgrade/) in case anyone want an easy install on fedora.
As of now I have only have built for Fedora 41.

**Comment by SteveLauC** [comment]
Hi @li-lay, if you want, you can have it documents [here](https://github.com/topgrade-rs/topgrade/blob/dc9d8d55f217bd58cdca8cde0acba8d8a6c434c5/README.md?plain=1#L33), something like 


"Fedora: [Copr](https://copr.fedorainfracloud.org/coprs/lilay/topgrade/) (limited to Fedora 41, currently)"

**Comment by li-lay** [comment]
@SteveLauC Should I make a PR?

**Comment by TheOceanBreeze** [comment]
Looks good! I'll close the issue.
